### ISSUE TITLE
Is there any way to detect reflected calls?

### ISSUE THREAD

**Issue by heyuxiang1996** [TNG/ArchUnit#1031]
If there is such a line of code in a class
`Class.forName("com.xxxx.xxx").getMethod("methodName", null).invoke(getClass(), null);`
I can't use `getAccessesFromSelf()` detect what method is called by this class through reflection,Is there any way to detect reflected calls?

**Comment by hankem** [comment]
I don't think that there is a way to detect method calls through reflection.

**Comment by codecholeric** [comment]
Yes, sorry, ArchUnit only deals with static code structures. The use of Reflection is by nature dynamic, so ArchUnit doesn't know anything about it. Since the method name and parameter types used in the Reflection API can also be dynamic, there is never a save way to analyze this purely statically.
Does this answer your question?

**Comment by heyuxiang1996** [comment]
> Yes, sorry, ArchUnit only deals with static code structures. The use of Reflection is by nature dynamic, so ArchUnit doesn't know anything about it. Since the method name and parameter types used in the Reflection API can also be dynamic, there is never a save way to analyze this purely statically. Does this answer your question?

Thank you very much
