### ISSUE TITLE
Private modifier not working with Kotlin 

### ISSUE THREAD

**Issue by chirdeeptomar** [TNG/ArchUnit#1032]
I am using Kotlin and would like all classes under a package `features` to be private. I have the classes marked as `private` but I am not getting the code below to pass even after excluding the Kotlin generated classes like $Reference etc. 

```kotlin
 @Test
    fun `application features are marked private`() {
        val classes = ClassFileImporter()
            .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
            .importPackages("com.xxx.core")

        val featuresRule: ArchRule = classes()
            .that()
            .resideInAPackage("..features..")
            .should()
            .bePrivate()

        featuresRule.check(classes)
    }
```

If I change the bePrivate to notBePublic, then it works but it's not what I would want. 

Error:

```Class <com.xxx.core.features.MyClassUseCaseImpl> does not have modifier PRIVATE in (MyClassUseCaseImpl.kt:0)```

Thanks for your help.

**Comment by codecholeric** [comment]
I think the problem is that a top-level Kotlin class that is private doesn't have a modifier `private` in the bytecode. AFAIK that isn't even legal on the bytecode level. So a Kotlin toplevel class that is declared `private` will result in a package-private class on the bytecode level AFAIS. Since ArchUnit can only check what is in the bytecode the Kotlin `private` modifier is not visible.

I could imagine a couple of ways, but they are all not super pretty:

1) just accept that the classes are package-private and test for that (since Kotlin doesn't have a package-private modifier, this might even be equivalent anyway? :thinking:)
2) use Kotlin Reflection, e.g.
  ```
  val kotlinPrivate: DescribedPredicate<JavaClass> =
    DescribedPredicate.describe("Kotlin private") { clazz ->
      clazz.reflect().kotlin.visibility == KVisibility.PRIVATE
    }
  
  // You might need that if you have classes not supported by Kotlin Reflection,
  // not sure if there is a cleaner way
  val areSupportedByKotlinReflection: DescribedPredicate<JavaClass> =
    DescribedPredicate.describe("are supported by Kotlin Reflection") { clazz ->
    try {
      clazz.reflect().kotlin.visibility
      true
    } catch (_: UnsupportedOperationException) {
      false
    }
  }
  
  classes()
    .that(areSupportedByKotlinReflection)
    .should(ArchConditions.be(kotlinPrivate))
  ```
3) the info might also be contained in the generated `@MetaData` annotation on the `JavaClass`. But AFAIK this is some non-public Protobuf-serialized info, so I'm not sure if it's a good idea to rely on that after reverse-engineering (at least I haven't found the necessary info when I searched the net real quick for it)

Option 2) is probably the cleanest with respect to Kotlin visibility, but it is somewhat slower, because every class has to be loaded via Reflection and it depends on all relevant classes being on the classpath of the test JRE.

Does this help you?

**Comment by chirdeeptomar** [comment]
Thanks for the insight. I will just live with the first option as the tests are running slower as is.
