### ISSUE TITLE
PlantUml Tests should allow different classes in one package

### ISSUE THREAD

**Issue by PaulienVa** [TNG/ArchUnit#108]
Using functional packaging, the desired architecture can have several domain classes in one package. When moddelling this in a plant uml, I would like to declare the following: 
 
```
@startuml

skinparam componentStyle uml2
skinparam component {
  BorderColor #grey
  BackgroundColor #white
}
 [ObjectA] <<..example..>>
 [ObjectB] <<..example..>> 

[ObjectA] -->  [ObjectB]
@enduml
```

However this returns the error: `com.tngtech.archunit.library.plantuml.IllegalDiagramException: Stereotype '..example..' should be unique`

Could it be possible to support this?

**Comment by codecholeric** [comment]
Thanks for the feedback about the PlantUML feature, I really appreciate it :smiley: 
As you might have guessed from the specific exception, this usage was not the intention behind the implementation, but was considered a probable diagram error.
Your example looks like you want to specify the relations at the class level? I honestly wasn't sure, if this brings the desired benefit. The idea behind the PlantUML feature was, to split your domain (or technical structure) in modules / components and define how these should depend on each other.
My instinct tells me, that the chance that this test is red because the module wants to evolve internally is a lot bigger, than the chance that this is really a mistake with respect to the desired architecture.
Do you really not have any subpackages that would separate `ObjectA` and `ObjectB`?
In my mind this would always be something like `..myapp.order.. -> ..myapp.customer..` or similar to stay within the simple shopping domain.
If you really have classes within a flat structure `com.example.ObjectA` and `com.example.ObjectB` and you want to define dependencies `ObjectA -> ObjectB`, I could do a short spike that you could easily copy into your project to try if this really feels good (the PlantUML feature is a pretty simple satellite that would be easy to pull out and modify it a little).

**Comment by PaulienVa** [comment]
Ah check. I actually understood that we could check the relations on class level. This is why I asked the question like that ;)

But yes we do have several domain classes in one package and I hoped to be able to test whether the domain model was well implemented and thereby also have some documentation for our domain model (as we are making the plan uml's anyways). I fully understand if that is not the designed behavior.

**Comment by codecholeric** [comment]
I'm really not sure, if this is the right granularity (also I'd probably have chosen a class diagram then, instead of a component diagram). Because to me it seems like architecture tests you need, when the human mind starts to have trouble with complexity. If you have a couple of classes, it seems like you can comprehend the intention in little time and then it would be a conscious decision to wander off the given path because the model needs to evolve.
I would just guess, that anybody who wants to go a different path would just start to always adjust the tests as well and it might be more burden than value.
But I don't know your exact use case of course. If you want I can look into it a little, maybe relax those constraints and change dependency checking at the package level to checking at the class level, so you could try how it feels and if you think it would really bring value to your project (I'm always interested in experiences from other projects :wink:)
Other than that, the code should be pretty strongly isolated within this package
https://github.com/TNG/ArchUnit/tree/master/archunit/src/main/java/com/tngtech/archunit/library/plantuml
so you could also clone this, play around a little yourself and use the modified condition (just dumping those classes into your test code and start modifying should do the trick).
Other than that, moving your classes to subpackages like `..example.subdomain_a.ObjectA` and `..example.subdomain_b.ObjectB` would do the trick as well, of course :wink:

**Comment by codecholeric** [comment]
I've hacked around a little bit, if you want to try how such tests feel, you could check out https://github.com/TNG/ArchUnit/blob/plantuml-classes-in-same-package/archunit-example/example-plain/src/test/java/com/tngtech/archunit/exampletest/PlantUmlClassesInSamePackageTest.java
It's really quick and dirty, but you can grab the code in https://github.com/TNG/ArchUnit/tree/plantuml-classes-in-same-package/archunit/src/main/java/com/tngtech/archunit/library/plantuml and adjust it further to your need, if necessary.
As I said, if I would add this to ArchUnit itself, I would do it as a class diagram. But I would only do it, if there are sufficient arguments from real life projects to convince me, that these tests provide more value than costs :wink: (besides maybe on an academic level, e.g. to validate exercises for university courses)

**Comment by codecholeric** [comment]
Since I haven't heard anything back, I'll close this issue for now. Feel free to reopen, if any new points to discuss should arise.

**Comment by mimousewu** [comment]
We try to use this as DDD arch check. We want to use puml to describe the dependency in one package. But the example code can not access anymore.
Because we just want to describe the business logic inside the domain. all classes will be in the same package. 
BTW, the concept of Package is not Stereotype. We can use parent class as Stereotype.

It's really a good feature to binding UML design diagram with source code in a light way. But we can not use this because of this restrict.

**Comment by codecholeric** [comment]
Can you maybe give me an example of a diagram that you would want to check and a class graph that would pass / violate it? That would really help me to understand what other use cases are out there :smiley:
