### ISSUE TITLE
implements check fail

### ISSUE THREAD

**Issue by davidkarlsen** [TNG/ArchUnit#110]
```
package com.edb.fs.tac.jfr.srv.model.dhub;

import java.io.Serializable;

public class TestClass implements Serializable {
}
```

The test:
```

@AnalyzeClasses(packages = "com.edb.fs.tac.jfr.srv.model")
public class ArchUnitTest {

    @ArchTest
    public static ArchRule classesInModelPackageAreSerializable = classes().that().resideInAPackage("..model..")
            .should(ArchConditions.implement(Serializable.class));

}
```

fails with:
class com.edb.fs.tac.jfr.srv.model.dhub.TestClass doesn't implement java.io.Serializable in (TestClass.java:0)

???

**Comment by codecholeric** [comment]
The problem is, that you aren't importing all related classes. In other words, since `java.io.Serializable` is not contained within your import, ArchUnit doesn't know, that it is an interface (yes, it could be derived from the fact, that it appears within an `implements` declaration at some place, but that would raise the complexity of the import even further).
So there are two ways to solve this

* also import `Serializable` if you want to have tests based on that
* reconfigure ArchUnit's resolution behavior with respect to missing classes (compare https://www.archunit.org/userguide/html/000_Index.html#_configuring_the_resolution_behavior)

I usually configure `resolveMissingDependenciesFromClassPath=true` as mentioned there, because it causes less surprise like yours. The reason this is not default is simply because it decreases performance and might not be necessary in many cases (e.g. if you only write rules with respect to classes in your own imported project).

BTW: The API already provides this method `.should().implement(Serializable.class)`, no reason to refer to `ArchConditions` :wink:

**Comment by codecholeric** [comment]
I have to admit though, that I'm starting to wonder if maybe `resolveMissingDependenciesFromClassPath=true` would be the better default behavior, since you're not the first person confused about this...

**Comment by davidkarlsen** [comment]
great - that worked - and yes, IMHO I think it would make a good default

**Comment by codecholeric** [comment]
No problem, glad I could help :smiley: 
I think I'll switch the default around with the next release (with a sufficiently prominent notification :wink: ) since people can still switch resolving from the classpath off, if performance is too bad, but it seems to be the path of least surprise...
