### ISSUE TITLE
Get modifiers of JavaParameter

### ISSUE THREAD

**Issue by priyanthabuddhika** [TNG/ArchUnit#1230]
I am trying to create a custom arch unit rule to validate if method parameters have a final modifier. However, JavaParameter class does not seems to have a getModifiers method like JavaMethod class.  Is this achievable with current ArchUnit API ? 

I'm using ArchUnit 1.2.1 version.

This is a code sample of what I'm trying to achieve.

```
public void check(JavaMethod method, ConditionEvents events) {
            boolean allParametersAreFinal = true;

            for (JavaParameter parameter : method.getParameters()) {
                if (!parameter.getModifiers().contains(JavaModifier.FINAL)) {  // <---------- Something like this ?
                    allParametersAreFinal = false;
                    events.add(SimpleConditionEvent.violated(method,
                            String.format("Parameter %s of method %s is not final",
                                    parameter.getOwner().getFullName(), method.getSourceCodeLocation())));
                }
            }

            if (allParametersAreFinal) {
                events.add(SimpleConditionEvent.satisfied(method,
                        "Parameters of method " + method.getFullName() + " are final"));
            }
        }
    }
```

**Comment by hankem** [comment]
I fear that final method parameters might just exist in the Java language, but and in the byte code/JVM. 
(I'm saying "might" because I don't know much about the JVM specification...)

I've just observed that for the simple example
```java
class C {
   void method(int p1, final int p2) {
   }
}
```
`javap` does not show any difference between the parameters `p1` and `p2` in the byte code:
```
  void method(int, int);
    descriptor: (II)V
    flags: (0x0000)
    Code:
      stack=0, locals=3, args_size=3
         0: return
```
So the `descriptor: (II)V` might be everything that is available to ArchUnit. (I'm saying "might"...)

**Comment by codecholeric** [comment]
Yes, from all that I found I also think that the parameter final modifier is erased during compile. Likely because it doesn't provide any benefit at runtime anymore, for a field, etc., the final modifier still makes sense when using via Reflection, etc. But for a parameter there is no way at runtime to interact with in a way that would make the final modifier relevant AFAIS.
As such I don't think this is technically feasible at the moment, but anyone feel free to reopen this issue if a possible hint is found that this could be feasible somehow.
