### ISSUE TITLE
Assert interface that extends

### ISSUE THREAD

**Issue by kosani** [TNG/ArchUnit#130]
Hi, I would like to make assertions on interfaces that extend a certain interface. 

For example, I would like to assert that Spring Data repositories reside in a certain package. The following test always passes regardless of the residing package:

```java
@ArchTest
    public static final ArchRule jpa_repository_should_be_in_right_package = classes()
      .that().areInterfaces().and().implement(org.springframework.data.repository.Repository.class)
      .should().resideInAPackage("..repository");
```

Best regards,
Alen

**Comment by codecholeric** [comment]
ArchUnit tries to model the domain of the Java language very closely. Since you write `interface Foo extends Bar`, the syntax `classes().that().areInterfaces().and().implement(..)` doesn't match anything (it would have to be `.extend(..)`).
I admit that this might be a little inconsistent (since there is no syntax element `.extend(..)`), but you can use the generic `classes().that().areInterfaces().and().areAssignableTo(Repository.class)` and it will match your case.
Originally ArchUnit only offered `assignableTo(..)`, since I considered that the relevant case. But there was public demand for `.implement(..)` so I added it :wink: I admit that it might be confusing that there is no `.extend(..)`... Do you think you wouldn't have been confused if ArchUnit would offer `.extend(..)` ? Or would you still have used `.implement(..)` in your case?
Independently of that, does this solve your problem?

**Comment by kosani** [comment]
I actually first started to look for `.extend(..)`, but then thought that `.implements(..)` covers my case. I haven't noticed the `assignableTo(..)`, so I guess it covers my case.

Oh, and the library is really nice. Great work!

**Comment by codecholeric** [comment]
I should give it some though to maybe add `.extend(..)`. Unfortunately it's quite some work to add all the variants to the syntax, which is why I've refrained so far, but if it saves some people from being confused, it might be worth it...

**Comment by kosani** [comment]
I've changed it to `assignableTo(..)` and it works. This solution seems quite sufficient.
