### ISSUE TITLE
Test fails falsely on kotlin code

### ISSUE THREAD

**Issue by davidkarlsen** [TNG/ArchUnit#132]
I have this test:
```
    public static final ArchRule classesWithConstraintAnnotatedParametersAreValidated =
            classes().that(hasAMethodWithConstrainAnnotations)
                    .and().areNotInterfaces()
                    .and().areNotAnnotatedWith("com.edb.fs.tac.jfr.srv.ws.jaxrs.TacJaxRsService")
                    .and().resideOutsideOfPackage(MODEL_PACKAGE)
            .should(beAnnotatedWith(Validated.class));
```

Which works fine on java code - but when converting some classes over to Kotlin, still with the @Validated annotation, it fails with:
```
Architecture Violation [Priority: MEDIUM] - Rule 'classes that has executable constraint annotations and are not interfaces and are not annotated with @TacJaxRsService and reside outside of package '..model..' should be annotated with @Validated' was violated (1 times):
class com.edb.fs.tac.jfr.srv.service.customer.CustomerService$DefaultImpls is not annotated with @Validated in (CustomerService.kt:0)
```

even though I can see the annotation there when decompiling the bytecode:
```
// IntelliJ API Decompiler stub source generated from a class file
// Implementation of methods is not available

package com.edb.fs.tac.jfr.srv.service.customer

@org.springframework.stereotype.Service @org.springframework.validation.annotation.Validated @org.springframework.transaction.annotation.Transactional @io.micrometer.core.annotation.Timed public open class CustomerServiceImpl public constructor(customerDao: com.edb.fs.tac.jfr.srv.dao.customer.CustomerDao) : com.edb.fs.tac.jfr.srv.service.customer.CustomerService {
```

**Comment by codecholeric** [comment]
I think this might be one of the magic parts of Kotlin, where byte code doesn't necessarily match source code. If you look at the error message, it reports that `CustomerService$DefaultImpls` violates your rule. From what I can tell from your output, you look at `CustomerServiceImpl` with the decompiler, which is simply another place.
So what I would guess is that

* you don't use `@JvmDefault`
* you added a default implementation to the interface `CustomerService`?

Because AFAIK, the Kotlin compiler will then transparently create an inner class `DefaultImpls` to house those default implementations. Compare https://realjenius.com/2018/06/29/jvm-default/
So from my point of view you have two choices. Either try out `@JvmDefault` if you use Java >= 8 and want the Kotlin compiler to create a default implementation within the interface. Or make sure that your rule ignores those generated classes, e.g. `that().dontHaveSimpleName(KOTLIN_DEFAULT_IMPL_NAME)`.
Can you solve your problem with these pointers?

**Comment by davidkarlsen** [comment]
@codecholeric Thanks a lot - you are absolutely right - the defaultimpl got created because we had parameters with default values. The strange this is that the inner class would not show in intellij target/classes - only from the filesystem - but running javap on it revealed it's contents.

Thanks again!

**Comment by codecholeric** [comment]
No problem, glad I could help :smiley: I would guess that either

* IntelliJ is opinionated to hide those classes generated for Kotlin from the poor developer
* IntelliJ was out of sync with the file system (which actually happens quite often to me :wink:)
