### ISSUE TITLE
Extract AssertJ extension into separate test module

### ISSUE THREAD

**Issue by mkjensen** [TNG/ArchUnit#1370]
It looks like you have a nice extension of AssertJ ([com.tngtech.archunit.testutil.Assertions](https://github.com/TNG/ArchUnit/blob/main/archunit/src/test/java/com/tngtech/archunit/testutil/Assertions.java)) in the test part of `com.tngtech.archunit:archunit`.

Could it make sense to extract that into a separate module that can be used by everyone to test their own rules?

**Comment by codecholeric** [comment]
The problem is, that I don't really want to apply the same standards to this as to the regular ArchUnit code that is released. In particular backwards compatibility. If we'd release this, then we would need to make sure not to break users' code, we'd need to deprecated methods and give a long grace period, etc. We couldn't refactor freely anymore as needed. And the testing API wasn't really developed with that in mind either 🤔 I'm just afraid it would slow down development if we need to think about the testing infrastructure like an API that needs to be stable.
So, from my point of view it would be preferable if users would just copy & paste the parts that they need and then develop it independently.

**Comment by mkjensen** [comment]
That's fair, thanks for answering.
