### ISSUE TITLE
Support onlyDependOnClassesThat and onlyAccessClassesThat with Kotlin Enums and Kotlin Delegated Properties

### ISSUE THREAD

**Issue by JonasHavers** [TNG/ArchUnit#140]
### Use Case

I want to check that domain classes do not access other classes other than domain classes and classes of the Java- or Kotlin standard lib. I have Kotlin enums and Kotlin classes with delegated properties in my domain packages.

### Issue

The methods `onlyDependOnClassesThat` and `onlyAccessClassesThat` do not work with Kotlin Enums and Kotlin Delegated Properties.

ArchUnit Version: 0.9.3

### Example with 'onlyDependOnClassesThat'

**Test Code:**
```
ArchRuleDefinition
.classes()
.that().resideInAPackage("domain..")
.should().onlyDependOnClassesThat().resideInAnyPackage("domain..", "java..", "kotlin..")
```
(or using `ArchRuleDefinition.noClasses()` vice-versa)

**Result:**
```
Field <domain.DomainEnumClass.$VALUES> has type <[Ldomain.DomainEnumClass;> in (DomainEnumClass.kt:0)
Field <domain.DomainClass.$$delegatedProperties> has type <[Lkotlin.reflect.KProperty;> in (DomainClass.kt:0)
Method <domain.DomainEnumClass.values()> calls method <[Ldomain.DomainEnumClass;.clone()> in (DomainEnumClass.kt:5)
Method <domain.DomainEnumClass.values()> has return type <[Ldomain.DomainEnumClass;> in (DomainEnumClass.kt:0)
```

### Example with 'onlyAccessClassesThat'

**Test Code:**
```
ArchRuleDefinition
.classes()
.that().resideInAPackage("domain..")
.should().onlyAccessClassesThat().resideInAnyPackage("domain..", "java..", "kotlin..")
```

**Result:**
```
Method <domain.DomainEnumClass.values()> calls method <[Ldomain.DomainEnumClass;.clone()> in (DomainEnumClass.kt:5)
```

If the information is not sufficient, I will gladly provide a project with an example.

Thanks in advance!

**Comment by codecholeric** [comment]
Thanks for raising the issue, I think this is on the one hand related to #98 and on the other hand due to the fact, that any array type has no package (which for ArchUnit is considered the same as empty).
I don't really know how this should be handled. Originally I thought there is no need to distinguish between default/empty package and no package, but now I'm not so sure anymore, since those types should probably always ignored with regards to package rules.
Anyway, can you try as a workaround to allow your domain classes to depend on the empty package, too?
I.e. `.onlyDependOnClassesThat().resideInAnyPackage("domain..", "java..", "kotlin..", "")

**Comment by codecholeric** [comment]
Thinking about it, maybe it would make sense to break with the reflection API compatibility at that place and (in relation to #139) implement `getPackageName()` for arrays as `getComponentType().getPackageName()` simply because from an architecture test point of view I probably want to treat `some.MyClass[]` similar to `some.MyClass` with regard to the package.

**Comment by JonasHavers** [comment]
Thanks Peter, the workaround with the empty package you've mentioned works! As you suggested, I would also like to treat `some.MyClass[]` similar to `some.MyClass` with regard to the package which probably means to use reflection at that point.
