### ISSUE TITLE
orShould().beAnInterface().orShould().beAnEnum().orShould().beAnInnerClass()

### ISSUE THREAD

**Issue by crehn** [TNG/ArchUnit#172]
First of all: ArchUnit is great! I've been looking for something like this for many years and it turns out ArchUnit is much better than everything I've used before and even better than what I had wished for. Keep going!

I'd like to have a rule that checks that the data package only consists of certain types of classes. That's pretty straightforward to do:

```java
    @ArchTest
    public static final ArchRule shouldOnlyHaveCertainClassesInDataPackage = 
            classes().that().resideInAPackage("..data..")
            .should().haveSimpleNameEndingWith("Repository")
            .orShould().beAnnotatedWith(Entity.class)
            .orShould().notBePublic();
```

Then I realized that there are some checks that are not supported out of the box. I'd like to have methods `beAnInterface()`, `beAnEnum()`, and `beAnInnerClass()`.

Fortunately it's easy to specify these conditions yourself:

```java
private static ArchCondition<JavaClass> beAnEnum() {
        return new ArchCondition<JavaClass>("be an Enum") {
            @Override
            public void check(JavaClass javaClass, ConditionEvents events) {
                String message = javaClass + (javaClass.isEnum() ? "is an Enum" : "is not an Enum");
                events.add(new SimpleConditionEvent(javaClass, javaClass.isEnum(), message));
            }
        };
    }
```

Nevertheless I feel like this should be part of the standard API.

**Comment by hankem** [comment]
I agree; your `ArchCondition<JavaClass> beAnEnum()` would fit very well into ArchUnit's `ArchConditions`, and the `ClassesThat` and `ClassesShould` API could easily provide corresponding methods.
Do you want to create a pull request? 😉

Regarding `beAnInterface()`:
There is already [`classes().should().beInterfaces()`](https://javadoc.io/page/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/syntax/elements/ClassesShould.html#beInterfaces()) since [ArchUnit 0.5.0](https://github.com/TNG/ArchUnit/releases/tag/v0.5.0). ☺

**Comment by codecholeric** [comment]
I'm happy you like ArchUnit :smile: 
I agree that `should().beEnums()` and `should().beInnerClasses()` would be good extensions of the API. As @hankem pointed out, the interface assertion is already present.
I'll see if anyone wants to pitch in, since this would be a good starter issue (limited scope, straight forward implementation).

**Comment by codecholeric** [comment]
Overlaps in parts with #207
