### ISSUE TITLE
Import classes from another project

### ISSUE THREAD

**Issue by C-Side** [TNG/ArchUnit#176]
Hey ArchUnit Team,

I hope I'm in the right place to ask my question:

Is it possible to import the classes from a project outside of the one where the tests are written? I tried using a LocationProvider but the framework is only able to find the classes of the project where the tests are located in. Maybe I'm using the Location Provider the wrong way? Any help is appreciated.

```
class ProjectClasses implements LocationProvider {
@Override
public Set<Location> get(Class<?> testClass) {
    Set<Location> result = new HashSet<>();
    result.add(Location.of(Paths.get("/git/Bachelorarbeit/testProject/")));
    result.add(Location.of(Paths.get("/git/Bachelorarbeit/anotherProject/")));
    result.add(Location.of(Paths.get("/git/Bachelorarbeit/aThirdProject/")));
    return result;
  }
}
```

The files for the `testProject` (where the tests are present) are found while the files of `anotherProject` and `aThirdProject` are missing.

**Comment by codecholeric** [comment]
To answer your first question, yes, ArchUnit can import classes from anywhere, they don't have to be contained within the same project / the project's classpath. You need a `LocationProvider` if you want to use the JUnit support (i.e. `@AnalyzeClasses` and `@ArchTest`). Otherwise you can simply use `classFileImporter.importPaths(paths)`.

Your approach is correct and should work, I don't see a problem with the snippet you've provided.
Does your test look like this?

```
@AnalyzeClasses(locations = ProjectClasses.class)
class MyArchitectureTest {
    @ArchTest
    static final ArchRule rule = ...
}
```

You can set a break point into your location provider to check if it gets called and to check if the locations match the correct folders.

**Comment by C-Side** [comment]
Thanks in advance for your reply and yes, I'm trying to use the JUnit4 Support. My test class got the following header (I renamed the ProjectClasses class to ProjectLocationProvider):
```
@RunWith(ArchUnitRunner.class)
@AnalyzeClasses(locations = ProjectLocationProvider.class)
```

I already tried debugging a little bit and found out that the ProjectLocationProvider is called and my `result` set is filled with the following three locations:
```
Location{uri=file:/C:/git/Bachelorarbeit/testProject/}
Location{uri=file:/C:/git/Bachelorarbeit/anotherProject/}
Location{uri=file:/C:/git/Bachelorarbeit/aThirdProject/}
```
I then set another breakpoint in my test and tried to use the JavaClasses to see which files were actually imported. The ProjectLocationProvider only added the files of the `testProject`

**Comment by codecholeric** [comment]
Sorry for the delay, I had big issues to find any time recently :frowning_face: 
Could you solve this problem?
If the location provider is called like this and returns three locations, that looks good. Are you sure there are compiled class files inside of these folders? If you only have `*.java` files in there, it won't work, since it only takes bytecode.
You could set a break point into `com.tngtech.archunit.core.importer.ClassFileImporter.importLocations` and see what `ClassFileSources` are used in the end. In particular you can check out the constructor `com.tngtech.archunit.core.importer.ClassFileSource.FromFilePath()`

**Comment by codecholeric** [comment]
I'll close this for now, feel free to reopen if the issue persists!

**Comment by C-Side** [comment]
Yeah sry for the lat answer aswell, I was busy writing my bachelor thesis. This can stay closed, the missing bytecode was indeed the problem. Thanks for the help
