### ISSUE TITLE
empty layers should fail the test

### ISSUE THREAD

**Issue by Bananeweizen** [TNG/ArchUnit#177]
Copy the layered architecture example from the user guide into an arbitrary project and run it. The test passes, since none of the layer definitions maps to any class, field etc. in that project.

I suggest to fail every test where at least one layer definition does not contain any java artifact. This helps avoiding errors in multiple scenarios:
* When starting such tests initially and getting the layer setup wrong.
* When refactoring an existing code base and therefore no longer matching anything. E.g. rename the "persistence" package in the example to "database", and the layered architecture check stops doing anything useful, but it is still green in every test run.

**Comment by codecholeric** [comment]
I think the reason it was originally not done like this, is the possibility to define your layered architecture right in the beginning, even if the layers are not filled yet. But I see your point, it might indeed be better to just fail and force people to only add layers once they also have a class in that layer :wink:

I'd be definitely open for a change here, if anybody wants to jump in and submit a PR. Otherwise I'll change it once I get around to it, but my task pipe is horribly crowded :frowning_face:

**Comment by davidkarlsen** [comment]
Do you have a suggestion for workaround?
I used to have a common test included in all my modules, which stated the layers, among them that my top-layers could not be accessed by any layer.
e.g. layers:
- dao
- service
- common
- model
and then 
- batch
- web

batch cannot be called by any module (as it is a final application module) and the ws-module cannot be called by any else.

I could extract these tests into the layers (e.g. batch and web) - but of course these would never catch anything as a layer can never state anything about others layers access INTO this layer.

**Comment by davidkarlsen** [comment]
ah - I see an `withOptionalLayers(true)` - I'll go with that
