### ISSUE TITLE
Add support for asserting on classpath files

### ISSUE THREAD

**Issue by bobtiernay-okta** [TNG/ArchUnit#185]
It would be good to be able to assert things like:

- "All modules like `<condition>` should have a `logback-test.xml` file"
- "All test classes should have fixtures in `src/test/resources/<test-package>`"
- "No top-level folders other than `src/main`, `src/test`  should exist"
- "All modules should be named `<app>-<module>` and all packages within them should be under `com.example.<app>.<module>`"

Having a way to support other classpath elements (and maybe file system?) would be very useful in enforcing architectural constraints on more classpath resources.

**Comment by kapep** [comment]
I would really like to have support to read resources that define dependencies and architecture, like OSGi dependencies in the `META-INF/MANIFEST.MF`, ServiceLoader configurations in `META-INF/services` or maybe analyzing `module-info.java` files.

Technically META-INF is not a class path resource though, so it might only be available when analyzing classes that are packaged in e.g. jar files. Directories like `src/main` also sound like they aren't part of the classpath but of the project directory structure. I guess if the class path location is well known (e.g. always the `bin` or `target/classes` subdirectory of the project root directory), then you could just read those files but depending on your build infrastructure the project directory might not be always available.

**Comment by codecholeric** [comment]
This is an interesting idea, but I'm not sure I can grasp all the implications yet. Maybe we can discuss this a little. First of all, I see multiple aspects there, one is classpath element, one is file system.
And then there is the question how to bring this together with ArchUnit.
ArchUnit is essentially independent of the classpath. It offers some convenience to use the classpath of a project as an import source, but once the barrier of locating class files has been crossed, the concept of "classpath" is gone. Same with the file system, you can `importer.importPaths(..)` on some file system paths, but then the concept is gone.
So far there is no "module" or "archive" later on, besides the `JavaClass.source` element which refers back to the original location the class was imported from.
I guess it would be possible to import meta information, but often there are multiple project configurations used at the same time. Take a Maven multi module project, if you execute an ArchUnit test with Maven, the classes will be imported from all the single JARs the project is composed of. If you execute the same test within your IDE all classes might come from the file system. META-INF might reside within the JAR file or within the `target/classes` file path, depending on how the test is executed.

Maybe to elaborate a little where I see problems: Theoretically I could do `importer.importPaths("/")` and import all classes in my whole file system. Sometimes I'll encounter a `Foo.class`, sometimes I encounter some random file `foo.txt` and sometimes some folder `META-INF`. How would I bring this back together? It's relatively easy with `importer.importJar(jarFile)`, and `importer.importClasspath()` might be somewhat straight forward as well.

**Comment by kapep** [comment]
One more issue is that it's also possible that META-INF is only generated by Maven in the packaging phase and does not exist when building with an IDE. Likewise the IDE project could contain interesting resources that are excluded by Maven builds and not available if the test loads dependencies from a Maven repository instead of from the file system.

In some cases it should be possible to try loading the same resources from different locations depending on how the module was imported (e.g. load the resource from the jar archive if run with Maven, otherwise load it from a configured path). In other cases I guess rules would need to be enabled/disabled depending on whether they are rules for file system resources in IDE projects or for resources in archives.

Anyway importing modules could require the user to import each module path individually. It would be less convenient but I think its hard to distinguish later which files belong to which module if everything is loaded at once.

**Comment by kapep** [comment]
So I experimented a bit to get a better feeling for what is possible when importing classes from paths and from the classpath.

I created a Maven multi-module project and implemented some predicates and conditions for for doint assertions on resources. I ran tests in Maven with both Surefire and Failsafe since both plugins load classes differently. Unit tests with Maven Surefire load classes from `file://project/target/classes/` and integration test with Maven Failsafe load classes from `file://project/target/resource-test-0.0.1-SNAPSHOT.jar`. Some tests import classes from the classpath and some import from file system paths.

Generally I got the impression that a "module" concept is not actually necessary for assertions on resources. Instead a "resource" and "code source" concept could suffice. These concepts seem suitable for various build systems and architectures and they don't impose any definition of what a "module" actually is (does it mean compilation module or runtime module? Is it a Java 9 Module or something more generic?). I'm thinking about something like this:

- A "resource" provides a generic API for assertions that does not depend on where the resource is loaded from (it could be loaded from the classpath, file system or an archive).
- A "code source" is the location from where classes are loaded from. This could be an archive or a file system directory. This location is scanned for containing resources.
- When importing already loaded classes from the classpath, resources can be accessed as usual (`javaClass.reflect().getResource()`) or scanned by Guava's `ClassPath` utility.
- When importing from paths without loading the classes, we need to require that package names match the directory structure of a class (I think this is a JVM requirement anyway). Then we can calculate the code source of every imported class and scan that directory for resources. For example if `importPaths("/")` finds class "org.example.Foo" in `~/project/bin/org/example/Foo.class`, then `~/project/bin/` is the code source (and also the classpath root). Files not contained in a code source can be ignored during import.
- When importing from archives without loading classes, the whole archive is the code source and can be scanned for resources. The manifest defines the classpath(s) within the archive.

In some cases the code source is the same as the classpath root of a class (e.g. the `target/classes/` directory) but it's possible that the classpath root is a subdirectory of the code source (this is usually the case for web applications) or even that there are multiple classpaths in an archive.

I implemented a few simple rules as proof of concept. Here are some examples of what is already possible:
		
    // Check existence of classpath resources for certain classes
    ArchRule uiComponentShouldHaveIcon = classes().that().areAssignableFrom(UIComponent.class).should(haveClassPathResource("icon.png"));
    ArchRule iconShouldHaveThumbnail = classes().that(haveExistingClassPathResource("icon.png")).should(haveClassPathResource("icon-thumbnail.png");
    
    // Check classpath resource
    ArchRule propertyShouldBeSet = resources().that(resideInClassPathOf(Foo.class)).and().that(haveNameMatching("foo.properties")).should(containText("foo=bar"));
    ArchRule fileShouldNotExist = resources().that(resideInCodeSource("example.jar")).should().not(haveNameMatching("debug.properties"));
    
    // Check non-classpath resource
    ArchRule allBundlesShouldHaveActivator = resources().that(haveNameMatching("META-INF/MANIFEST.MF")).should(containText("Bundle-Activator:"));

---

I'm haven't thought that much about how arbitrary file system resources might be handled yet. I think it would be nice to be able to do assertions on files relative to a code source. Maybe like this:

    /** Ensure all projects contain a readme file and document folder in the project root dir (path is relative to the code source location)*/
    ArchRule projectsShouldHaveReadmeFile = codeSources().shouldHaveFile("../../README");
    ArchRule projectsShouldHaveDocumentationFolder = codeSources().shouldHaveFolder("../../documentation/");
    
    /** Ensure all archives contain a license file (path is within the code source) */
    ArchRule archivesShouldContainLicenseFile codeSources().thatAreArchives().shouldContainFile("/license.txt");

**Comment by codecholeric** [comment]
Thanks for the detailed analysis :smiley: Yes, I guess by matching class names / packages and folder / archive structures it's possible to match resources.
I guess you can talk about a "classpath" with respect to all the classes you look at during the import. I.e. no matter from where you import classes, in the end you can always determine a set of root URLs from where the set of classes was imported.
Then on that set, or a specific root relative to a class, assertions could be made.
The only question is, what should happen if you import a package "com.foo", should you still be able to access all resources, or would that only import resources within `${root}/com/foo`.
I guess to be compatible with the current API it would be necessary that `JavaClasses` then also know the resources relative to the single classes. Maybe via `CodeSource` since this is close to the file system / archive.
If this should be integrated into ArchUnit, I think it should be independent of the classpath, yet consistent if you would use tools like `org.reflections`.

**Comment by codecholeric** [comment]
I'm going to close this for now since there has been no progress and I don't see any capacity for myself to deal with this in the foreseeable future.
