### ISSUE TITLE
ClassFileImporter().importPackages("...") does Scan java/lang packages 

### ISSUE THREAD

**Issue by smsnheck** [TNG/ArchUnit#186]
Hi there, 

I am trying to implement some archunit tests with your great test-framework.
But I have a major problem with the ```importClasses()``` method. 

Lets say I have a very huge system with more than 30k Classes (please, don't ask) and I want only to check certain classes that match a regex (or in this case: a package name)

The problem is, when I define 
```JavaClasses j = new ClassFileImporter().importPackages("some.package.prefix.file");``` to check only the classes of the file package, the DEBUG log says it scans also classes like 

```
2019-06-24 22:49:12 INFO  JavaClassProcessor:101 - Analysing class 'java/lang/CloneNotSupportedException'
2019-06-24 22:49:12 INFO  JavaClassProcessor:101 - Analysing class 'java/lang/InterruptedException'
2019-06-24 22:49:12 INFO  JavaClassProcessor:101 - Analysing class 'java/lang/Throwable'
```

Works the importPackages method like designed? Or am I doing something wrong to import only classes from a certain package?

**Comment by codecholeric** [comment]
This is indeed as designed, because by default (at least since `0.10.0` I think) ArchUnit looks for missing dependencies on the classpath. I.e. if the classes in your package depend on `java.lang.Throwable` (which seems not too far fetched :wink:), then ArchUnit will import that class from the classpath.

If you don't want this behavior and create stubs for missing classes instead (which then lack a lot of information!) you can reconfigure the resolution behavior, compare 
https://www.archunit.org/userguide/html/000_Index.html#_dealing_with_missing_classes 
and 
https://www.archunit.org/userguide/html/000_Index.html#_configuring_the_resolution_behavior

Does this help you?

**Comment by smsnheck** [comment]
Yes, indeed this could help. I‘ll have a look at it on monday and give you some feedback.

**Comment by codecholeric** [comment]
Did you get any chance to check it out?

**Comment by smsnheck** [comment]
Yes, it works with the properties `resolveMissingDependenciesFromClassPath, classResolver, and classResolver.args`
