### ISSUE TITLE
onlyDependOnClassesThat().resideInAnyPackage fails on array of primitive type

### ISSUE THREAD

**Issue by gtiwari333** [TNG/ArchUnit#191]
It looks ```onlyDependOnClassesThat().resideInAnyPackage``` fails on array of primitive type. 

**Failing Test:**
```
 package app.domain;
 public class User {
 	private int thisWorks;  
 	private int[] thisDoesntWork;
 	private String [] thisWorks2;
 }

 @Test
 @Disabled
 void domainClassesShouldOnlyDependOnDomainOrStdLibClasses() {
       JavaClasses classes = new ClassFileImporter()
             .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
             .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_ARCHIVES)
             .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_JARS)
             .importPackages("app..");
 
     ArchRule rule = ArchRuleDefinition.classes()
         .that().resideInAPackage("app.domain..")
         .should().onlyDependOnClassesThat().resideInAnyPackage( "java.."  );
 
     rule.check(classes);
 }
```
	

**Exception:**

java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'app.domain..' should only depend on classes that reside in any package ['java..']' was violated (1 times):
Field <app.domain.User.thisDoesntWork> has type <[B> in (User.java:0)

	at com.tngtech.archunit.lang.ArchRule$Assertions.assertNoViolation(ArchRule.java:91)
	at com.tngtech.archunit.lang.ArchRule$Assertions.check(ArchRule.java:81)
	at com.tngtech.archunit.lang.ArchRule$Factory$SimpleArchRule.check(ArchRule.java:195)
	at com.tngtech.archunit.lang.syntax.ObjectsShouldInternal.check(ObjectsShouldInternal.java:81)
	at architecture.CodingRulesTest.domainClassesShouldOnlyDependOnDomainOrStdLibClasses(CodingRulesTest.java:119)
 
 
**Possible Cause:**

	com.tngtech.archunit.core.domain.JavaType#isPrimitive returns false for array when array holds primitive type. 
 	com.tngtech.archunit.core.domain.JavaClass#nonPrimitive evaluates ``!getRelevantType.apply(member).isPrimitive() `` to true and addes to the result.
	
I'm using version 0.10.2

**Comment by codecholeric** [comment]
The reason is, that the package of `int[]` or similar is empty from ArchUnit's point of view. So to cover that case you would have to use (notice the empty string as argument)

```
ArchRule rule = ArchRuleDefinition.classes()
         .that().resideInAPackage("app.domain..")
         .should().onlyDependOnClassesThat().resideInAnyPackage("java..", "");
```

And yes, that's not pretty :frowning_face: I just don't know which behavior would be better. With ArchUnit `0.10.2` the package of an array type equals the package of the component type, but still a primitive as a component type has an empty package. The only other way I could think of would be to make package optional and consider primitives to have package `Optional.absent()`, but that would complicate the API in many other places.

**Comment by hankem** [comment]
@codecholeric: Maybe one could think of an additional API that allows for `java` and empty packages out of the box, if it turns out that this is what one _usually™_ wants?

**Comment by codecholeric** [comment]
@hankem In the end in many places you would probably want an application root package and only consider dependencies in there. Originally I thought of `Architectures...` as a more comfortable API, like `layeredArchitecture()` which circumvents this problem at the moment. In the end that would sound more like a ArchUnit "library" function to me.

**Comment by codecholeric** [comment]
I'll close this for now, but I'm open for a new issue with a concrete suggestion for such an API or even a PR :wink:

**Comment by dominikbrandon** [comment]
Thanks for the explanation, I've bumped into the same problem - `int[]` is indeed for some reason without a package and ArchUnit does not handle that. Allowing empty packages is a solution somehow but it's true that it's not too pretty. Another solution, which looks better to me, is to allow this particular class instead of the whole empty package. This can be done this way:
```groovy
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.belongToAnyOf
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.resideInAnyPackage

ArchRule rule = ArchRuleDefinition.classes()
         .that().resideInAPackage("app.domain..")
         .should().onlyDependOnClassesThat(resideInAnyPackage("java..") | belongToAnyOf(int[]))
```
Please note that it's a Groovy syntax, for Java you may need to change it a bit.
