### ISSUE TITLE
Support for Junit5 `@Nested` annotation

### ISSUE THREAD

**Issue by 51systems** [TNG/ArchUnit#201]
Methods / fields tagged with `@ArchTest` appearing in [nested tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested) are not executed.

**Comment by codecholeric** [comment]
Yes, that is expected behavior, I think they also never will. The reason is that `@Nested` is part of the JUnit Jupiter API, while the ArchUnit `TestEngine` only depends on the Jupiter Platform.
That means in particular the Jupiter `TestEngine` reacting to `@Nested` doesn't know about `@ArchTest` and the ArchUnit `TestEngine` doesn't know about `@Nested`. The only way to solve that would be to depend on the Jupiter API from ArchUnit's JUnit 5 support, but I don't believe that's how the JUnit team intended the extension.
This is also one reason why there is `@ArchTag` instead of `@Tag` of the Jupiter API. But ArchUnit also would not be able to use `@Tag` because it doesn't allow to target fields. In particular back when I wrote the `TestEngine` and discussed with the JUnit team a lot, I figured that the Jupiter API was just not suitable to be used as ArchUnit JUnit 5 API, because the focus is different and naturally the JUnit team does not want to adjust their code to the needs of test support clients, because that's what the platform is for.

The question is, if you really need that nested test support, if you also have inclusions like https://github.com/TNG/ArchUnit/blob/master/archunit-example/example-junit5/src/test/java/com/tngtech/archunit/exampletest/junit5/RuleSetsTest.java?
You could probably refer to inner classes which would be pretty similar to `@Nested` :wink: (except for a little redundancy)

**Comment by 51systems** [comment]
Thank you for the detailed response, `ArchRules.in` works well for my use case!
