### ISSUE TITLE
Record Method Calls to the same Class

### ISSUE THREAD

**Issue by waschmittel** [TNG/ArchUnit#209]
I want to create an ArchRule to make sure that methods annotated with Spring's @Async annotation are not called from the same class.

(These methods should not be called from the same class because Spring needs to create a proxy to make @Async work.)

So I made this rule:

```java
    @ArchTest
    public static final ArchRule asyncMethodsShouldNotBeCalledFromTheSameInstance = noClasses()
            .should()
            .callMethodWhere(DescribedPredicate.describe("no async from same class", input ->
                    {
                        return input.getTarget().isAnnotatedWith(Async.class) &&
                                input.getOriginOwner().equals(input.getTargetOwner());
                    }
            ))
            .as("@Async Methods should never be called from the same class because no proxy can be used then.");
```

Unfortunately, this does not work because apparently method calls to the same class do not seem to be collected. Is there any way I can configure this?

**Comment by codecholeric** [comment]
You are right, once upon a time people complained, that those self accesses would be utterly useless, because you're *always* interested in accesses to *other* classes :wink: So I changed the behavior to please the masses.
I'm really sorry, but I think at the moment you need to add a little boilerplate, e.g. like this:

```
noClasses().should(callAsyncMethodsFromTheSameClass())
    .because("it circumvents Spring's proxy mechanism");

private ArchCondition<JavaClass> callAsyncMethodsFromTheSameClass() {
    return new ArchCondition<JavaClass>("call @Async Methods from the same class") {
        @Override
        public void check(JavaClass javaClass, ConditionEvents events) {
            if (!javaClass.isAnnotatedWith(Async.class)) {
                return;
            }

            for (JavaMethodCall call : javaClass.getMethodCallsFromSelf()) {
                boolean originIsTarget = call.getOriginOwner().equals(call.getTargetOwner());
                events.add(new SimpleConditionEvent(call, originIsTarget, call.getDescription()));
            }
        }
    };
}
```

**Comment by codecholeric** [comment]
This reminds me that `ArchCondition` also needs some lambda'ification factory method :wink:

**Comment by honnel** [comment]
Thanks for your attention and quick reply!

We had to slightly customize the workaround for `@Async`annotated methods:

```java
   @ArchTest
    public static final ArchRule asyncMethodsShouldNotBeCalledFromTheSameInstance = noClasses()
            .should(callAsyncMethodsFromTheSameClass())
            .as("@Async Methods should never be called from the same class because no proxy can be used then.");

    private static ArchCondition<JavaClass> callAsyncMethodsFromTheSameClass() {
        return new ArchCondition<JavaClass>("call @Async Methods from the same class") {
            @Override
            public void check(JavaClass javaClass, ConditionEvents events) {
                if (!hasAsyncAnnotatedMethod(javaClass)) {
                    return;
                }

                for (JavaMethodCall call : javaClass.getMethodCallsFromSelf()) {
                    boolean originIsTarget = call.getOriginOwner().equals(call.getTargetOwner());
                    events.add(new SimpleConditionEvent(call, originIsTarget, call.getDescription()));
                }
            }

            private boolean hasAsyncAnnotatedMethod(JavaClass javaClass) {
                return javaClass.getAllMethods().stream()
                        .filter(m -> m.isAnnotatedWith(Async.class))
                        .map((Function<JavaMethod, Object>) JavaMethod::getClass)
                        .count() > 0;
            }
        };
    }
```

**Comment by waschmittel** [comment]
@honnel 's code causes complaints about any method call in a class that  has @Async methods.
@codecholeric the annotation is on the method, not on the class

Here's what works for me right now:

```java
    @ArchTest
    public static final ArchRule asyncMethodsShouldNotBeCalledFromTheSameInstance = noClasses()
            .should(callAsyncMethodsFromTheSameClass())
            .as("@Async Methods should never be called from the same class because no proxy can be used then.");


    private static ArchCondition<JavaClass> callAsyncMethodsFromTheSameClass() {
        return new ArchCondition<JavaClass>("call @Async Methods from the same class") {
            @Override
            public void check(JavaClass javaClass, ConditionEvents events) {
                for (JavaMethodCall call : javaClass.getMethodCallsFromSelf()) {
                    boolean originIsTarget = call.getOriginOwner().equals(call.getTargetOwner());
                    if (call.getTarget().isAnnotatedWith(Async.class)) {
                        events.add(new SimpleConditionEvent(call, originIsTarget, call.getDescription()));
                    }
                }
            }
        };
    }
```

Thanks @codecholeric for the really fast workaround for this :-) Do you plan to include the self accesses again now that there is a valid use case? I tried to fix it myself and make a pull request, but could not find where they are filtered out, sorry.

**Comment by codecholeric** [comment]
@waschmittel Ah, yes, you're right, overlooked that you were interested in target methods annotated with `@Async`. But great that you were able to solve it :smiley: 
The place where it is filtered out is `com.tngtech.archunit.lang.conditions.JavaAccessCondition#check`, the problem is that now I don't know exactly how to integrate it in the existing API. I guess to be clean the original method would have to be called something like `callMethodOfOtherClassWhere(..)` or similar so that the non-filtering method could take it's place. But that would not be backwards compatible...
Also the `JavaAccessCondition` is unfortunately used in different places, where the behavior might have to be kept the old way. But yes, it's probably a bad idea that this has such a generic name but then includes special behavior like ignoring accesses from the class to the class itself.
BTW: This was the original issue, number 3 :wink:: https://github.com/TNG/ArchUnit/issues/3

**Comment by waschmittel** [comment]
@codecholeric thanks for the info about #3 although I don't quite understand how self-accesses would lead to a problem in the example

```java
classes().that().resideInAPackage("..bar..").should().onlyBeAccessedByAnyPackage("..foo..", "..bar..")
```

To me it seems like self-access should not be a problem according to this rule because access from ..bar.. to ..bar.. is allowed. I assume I am missing something.

Any of the following things would be/have been helpful for me:

- checking self access by default
- checking self access with an explicit method (callOwnMethodWhere(...))
- a clear hint in the documentation that self-access is excluded (I spent about an hour debugging)

Anyway: Thanks for the quick help - the issue is resolved for me personally - Since I can't help with the things mentioned above, I'll leave it to you to decide if you want to implement any of the improvements above or just close the issue.

**Comment by codecholeric** [comment]
The original idea in the example was, that people don't want to write the second `..bar..` since that is always inherently wanted. So the way it's written there is no problem, but people would want to skip the second `..bar..`. Anyway, the only thing that was possible to achieve back then was to ignore self accesses from the same class. But this only helps in very simple cases, so I'm really not sure if it's worth it to have this exclusion at all.
However, now it's released behavior and any change would possibly break tests out there :frowning_face: 
I'll think about it, maybe I'll still change it with a big warning. Looking back at it now, I think the way of least surprise would have been to just treat all calls the same. I completely understand why this cost you time to debug, so sorry for that!
Just that if you treat all accesses the same, you can still exclude it, even if it's a little less convenient. The other way round, now that self accesses are excluded by default, there is no way one can get those accesses back.

**Comment by waschmittel** [comment]
Thanks, now I get it. Although I do wonder how many people still explicitly include the self accesses in their Rules because they assume that they have to. I did, at least.

**Comment by codecholeric** [comment]
I think I'll drop this filtering with the next release. You're right, it's not intuitive and it doesn't serve the original purpose anyway. Higher level API like `LayeredArchitecture` does a way better job for this.

**Comment by waschmittel** [comment]
Just updated to 0.12.0 and it works. Thanks @codecholeric :-)

**Comment by guija** [comment]
Where can I find that library?
I absolutely agree, in our project it keeps happening to us.

**Comment by codecholeric** [comment]
I basically just meant the library layer of ArchUnit :wink: -> https://github.com/TNG/ArchUnit/tree/master/archunit/src/main/java/com/tngtech/archunit/library
There are already some rules that are generally useful, like 
https://github.com/TNG/ArchUnit/blob/master/archunit/src/main/java/com/tngtech/archunit/library/GeneralCodingRules.java
or
https://github.com/TNG/ArchUnit/blob/master/archunit/src/main/java/com/tngtech/archunit/library/DependencyRules.java

**Comment by hankem** [comment]
@guija, just as a (functionally irrelevant) side note:
There is also [`ArchRule.because(String)`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/ArchRule.html#because(java.lang.String)), so you can probably use the auto-generated rule description and just add 
> .because("no proxy can be used then.");

instead of overwriting the entire rule description with
> .as("@﻿Async methods should never be called from the same class because no proxy can be used then.");

and
> .as("@﻿Transactional methods should never be called from the same class because no proxy can be used then.");

**Comment by codecholeric** [comment]
FYI @waschmittel @guija -> https://github.com/TNG/ArchUnit/pull/539 :wink:

**Comment by guija** [comment]
Really nice, thanks @codecholeric . We will definetly use this. @Schreitmueller

**Comment by waschmittel** [comment]
Thanks a lot for the notice @codecholeric :-) Using it now.
