### ISSUE TITLE
Test fails on Windows

### ISSUE THREAD

**Issue by SpearThruster** [TNG/ArchUnit#210]
It seems this commit should have fixed the issue - but they still fail on Windows: https://github.com/TNG/ArchUnit/commit/b040d90a987e6e032bc0534ea5e7efdbfe1e1c53

On Mac/Linux everything is fine.

**Comment by codecholeric** [comment]
This is very strange, because I ran the build myself on Windows several times after this fix and everything was fine. Can you tell me a little more details about your problem? What's the exact stacktrace, and which version of Windows and JDK are you using?

**Comment by SpearThruster** [comment]
It seems that the Test just runs in a loop, re-checking all classes and stuff until it crashes and it sounds eerily similar to what's described in the commit message. :)

I am using Java 11.0.2 openjdk. Here is the output from mvn build.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project ekap-domain-model:
There are test failures.
[ERROR]
[ERROR] Please refer to C:\apps\my-app\target\surefire-reports for the i
ndividual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Java\jdk\64\11.0.2\bin\java -jar C:\Users\XYZ\AppData\Local\Temp\surefire122265300964698000

**Comment by hankem** [comment]
I'm confused:
* The mentioned commit b040d90a987e6e032bc0534ea5e7efdbfe1e1c53 hardens the `FreezingArchRule` feature just introduced with [ArchUnit v0.11.0](https://github.com/TNG/ArchUnit/releases/tag/v0.11.0) regarding ArchUnit's own test suite.
* The failure you're reporting (_"project ekap-domain-model"_ in _"C:\apps\my-app"_) seems to be in a project other than ArchUnit.

I'm sorry, I don't yet see the relation between those two points, nor did I understand already which test is actually failing.

If your _"project ekap-domain-model"_ uses ArchUnit: 
* Can you show your failing test?
    * I haven't used Maven for quite some time, but do you get more useful output when building with `mvn --debug`?
* Which version of ArchUnit are you using?
    * Has the error appeared with an update of ArchUnit, or ever been there?
* Which maven version and configuration (`MAVEN_OPTS` or `JAVA_OPTS` environment variables) are you using?

I'm wondering whether you're trying to import too many classes which don't fit into your heap (a setting like `MAVEN_OPTS=-Xmx2G` might help in this case) – but that's just a wild guess... 😉

**Comment by codecholeric** [comment]
I'll close this due to inactivity (and as log as @hankem's questions are not answered, there is nothing further we can do about this). Feel free to reopen with further information!

**Comment by abeyecon** [comment]
I think I'm hitting the same issue.
I have an ArchUnit test that works in STS / Eclipse.  It runs there in 0.4seconds and prints out 500 lines of debug before passing.
When I run the test via maven via the windows command line the console can't keep up with the amount of debug messages it is creating and eventually runs out of memory.
The test has importOptions = {... DoNotIncludeJars.class} but must be pulling in something additional to analyze.
If I @ArchIgnore all arch tests in the class then the command line issue goes away.

**Comment by abeyecon** [comment]
The command line output contains debug log messages which don't appear when running in eclipse:
10:41:21.583 [main] DEBUG com.tngtech.archunit.core.importer.ClassFileProcessor$RecordAccessHandler - Found call of method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder; in line 35
10:41:21.583 [main] DEBUG com.tngtech.archunit.core.importer.ClassFileProcessor$RecordAccessHandler - Found GET access to field com/xxx/GameEventLedger.summary:Lcom/xxx/GameEventLedgerSummary; in line 36

**Comment by abeyecon** [comment]
Eclipse debug messages are only from com.tngtech.archunit.core.importer.JavaClassProcessor
Console has com.tngtech.archunit.core.importer.JavaClassProcessor
com.tngtech.archunit.core.importer.ClassFileProcessor$RecordAccessHandler

**Comment by abeyecon** [comment]
Tried without success all of:
ImportOption.DoNotIncludeTests.class, DoNotIncludeJars.class, DoNotIncludeArchives.class

**Comment by abeyecon** [comment]
First three lines of debug are the same in both cases:
11:16:10.009 [main] INFO com.tngtech.archunit.core.PluginLoader - Detected Java version 11.0.2
11:16:10.019 [main] DEBUG com.tngtech.archunit.core.PluginLoader - Current Java version is compatible to JAVA_9 => Loading Plugin com.tngtech.archunit.core.importer.ModuleImportPlugin
11:16:10.056 [main] DEBUG com.tngtech.archunit.core.importer.UrlSource$From - Found URLs on sun.boot.class.path: []

**Comment by abeyecon** [comment]
mvn console has extra debug line after that:
11:11:15.307 [main] DEBUG com.tngtech.archunit.core.importer.UrlSource$From - Found URLs on java.class.path: [file:/C:/Users/xxx/target/test-classes/, file:/C:/Users/xxx/target/classes/, jar:file:/C:/Users/xxx/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar!/, ...]

**Comment by abeyecon** [comment]
OK if I pipe the maven build output to a file then the build passes...

**Comment by abeyecon** [comment]
line number with timestamps:
00100 11:32:30.203 [main] DEBUG com.tngtech.archunit.core.importer.UrlSource$From - Found URLs on sun.boot.class.path: []
02560 11:32:31.000 [main] DEBUG com.tngtech.archunit.core.importer.ClassFileProcessor$RecordAccessHandler - Found call of method java/lang/StringBuilder.toString:()Ljava/lang/String; in line 30
11805 11:32:32.015 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Done analyzing java.lang.Enum
13051 11:32:33.000 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing method java.util.Collections.checkedSortedMap:(Ljava/util/SortedMap;Ljava/lang/Class;Ljava/lang/Class;)Ljava/util/SortedMap;
14310 11:32:34.000 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing method java.nio.charset.Charset.displayName:()Ljava/lang/String;
15633 11:32:35.010 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Done analyzing java.util.Deque

**Comment by abeyecon** [comment]
I have a very bad workaround,but it gets the tests passing from maven in the command line:

```package com.eyecon.stellav.integration.domain;

import org.junit.runners.model.InitializationError;
import org.slf4j.LoggerFactory;

import com.tngtech.archunit.junit.ArchUnitRunner;

public class SilentArchUnitRunner extends ArchUnitRunner {
    public SilentArchUnitRunner(final Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    static {
        final ch.qos.logback.classic.Logger LOG = (ch.qos.logback.classic.Logger) LoggerFactory
                .getLogger("com.tngtech.archunit.core.importer.JavaClassProcessor");
        LOG.setLevel(ch.qos.logback.classic.Level.INFO);
        final ch.qos.logback.classic.Logger LOG2 = (ch.qos.logback.classic.Logger) LoggerFactory
                .getLogger("com.tngtech.archunit.core.importer.ClassFileProcessor$RecordAccessHandler");
        LOG2.setLevel(ch.qos.logback.classic.Level.INFO);
    }
}```

**Comment by abeyecon** [comment]
Microsoft Windows [Version 10.0.17134.1069]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\ab>mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T04:41:47+10:00)
Maven home: C:\Program Files\Apache\Maven_3.6.0\bin\..
Java version: 11.0.2, vendor: Amazon.com Inc., runtime: C:\Program Files\Amazon Corretto\jdk11.0.2_9
Default locale: en_AU, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

C:\Users\ab>java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)

**Comment by abeyecon** [comment]
I think this means that ArchUnit will cause out of memory errors if com.tngtech.archunit.core.importer.ClassFileProcessor$RecordAccessHandler is set to log level of debug.
e.g. the root logger is set to debug.

**Comment by codecholeric** [comment]
Hmm, it seems a little strange to me though, that logging should cause an out of memory error? I wonder, if that is a Windows problem with the (less than optimal) default CMD?
It would be good to know, how exactly your test setup is, i.e. how you use `@AnalyzeClasses`. Because `DontIncludeArchives` should prevent any classes from JARs or JRTs to be imported. Only thing left might be dependencies automatically imported from the classpath. You can control those as described in https://www.archunit.org/userguide/html/000_Index.html#_configuring_the_resolution_behavior

**Comment by abeyecon** [comment]
@AnalyzeClasses(packages = "com.eyecon.stellav.integration.domain", importOptions = {
        ImportOption.DoNotIncludeTests.class, DoNotIncludeJars.class, DoNotIncludeArchives.class })

**Comment by codecholeric** [comment]
Okay, I don't see a problem there :confused:
BTW `DoNotIncludeArchives` is stronger than `DoNotIncludeJars`, i.e. the additional `DoNotIncludeJars` has no effect. I'll try to log a bigger amount in DEBUG on the Windows default command line and compare it to e.g. Bash, when I get around to it.
How many classes are you actually importing? Did you compare the result in Eclipse or on the command line? Eclipse and Maven can have a massively different classpath unfortunately.

**Comment by abeyecon** [comment]
I tried adding resolveMissingDependenciesFromClassPath=false to archunit.properties.  It still gives Out Of Memory.  Verified that archunit.properties got put into target/test-classes

**Comment by abeyecon** [comment]
I didn't do 100% comparison but the standout thing was that the ClassFileProcessor$RecordAccessHandler doesn't log in eclipse, but does on windows.  I'll try to do a class comparison.

**Comment by abeyecon** [comment]
The other bizarre thing is that piping the windows run to file works fine.

**Comment by abeyecon** [comment]
prelim:
JavaClassProcessor message eclipse 89, windows 938

**Comment by codecholeric** [comment]
What do those numbers mean?
Is it possible that you haven't imported the whole project into Eclipse, thus resulting in a different classpath?
Also often the build tool might refer to JARs of other modules of the project, while the IDE might directly reference the compiled classes, but that doesn't make sense in your case, since Eclipse runs faster.

**Comment by abeyecon** [comment]
The eclipse run is analyzing 9 classes, windows run is analyzing ~90 before crashing.  The project has 225 classes that should be getting analyzed...

**Comment by abeyecon** [comment]
The 9 classes that eclipse picks up seem to have no pattern to them, but running eclipse multiple times always results in those exact 9 being analyzed in exactly the same order.  There are only two 'packages' in the project to be analyzed /domain and /domain/builders.  The eclipse run picks up 8 classes from /domain and only 1 class from builders.

**Comment by abeyecon** [comment]
If I debug onArchUnitRunner.runChild() then JavaClasses classes is an array that contains 227 entries (sounds correct).

**Comment by abeyecon** [comment]
I think in eclipse the unit test is finished quicker than the output can be flushed to console so the remainder that is queued up to be output is dropped, whereas this doesn't happen in windows cmd...

**Comment by abeyecon** [comment]
If I stick a breakpoint on ArchUnitRunner.runChild():notifier.fireTestFinished then the eclipse console ends up showing Analyzing class 218 times (approx correct)

**Comment by codecholeric** [comment]
Hmm, those numbers are really small though. I ran ArchUnit in projects with 50000 classes and it ran okay (provided it had a sufficient amount of heap, but 8GB was always enough)
Crashing after 90 classes, there must be some other problem I think?
I did just run all of ArchUnit's test on the Windows CMD with DEBUG log level, and I also notice that the terminal freezes. If I run Git Bash with the same settings on the same Windows box, it passes (about half as fast, but no further problem).
I guess have to attribute this behavior to the bad Windows CMD.

**Comment by codecholeric** [comment]
However, it sounds like there is something strange going on with your setup. I don't understand though, above you write Eclipse would only pick up 9 classes? But then below you write about `JavaClasses` containing 227 entries? The difference between "Analyzing class" and the set of classes might be "pseudo classes" like `byte[].class` or similar...

**Comment by abeyecon** [comment]
No, It is just eclipse stops outputting to console after tests finish.  SO it correctly picks up all 225 classes, but only has time to print output up to the 9th class before it successfully completes.

**Comment by codecholeric** [comment]
Ah okay, now I understand. It still sounds strange that the Windows CMD would not even be able to print the DEBUG log for 90 classes, but I have to admit, I don't really use the CMD for development, so I don't know. If you would have a second terminal (e.g. Git Bash), you could compare. But in general I think you don't want to have ArchUnit's DEBUG logs anyway, for everyday test runs :wink:

**Comment by abeyecon** [comment]
Verified works with git bash.
Agree I don't want to run our tests in debug mode, but that is how this project is set up.  The logging config for it is 'non-standard' so I don't know how to adjust it to filter out archunit debug logging.
Using the SilentArchUnitRunner works around our problem.

**Comment by codecholeric** [comment]
Yeah, I'm glad you have the `SilentArchUnitRunner` as a workaround for your case :smiley:
I don't think this is a real ArchUnit issue then, but a Windows CMD issue, do you agree?

**Comment by abeyecon** [comment]
That's not up to me to decide.  :)  I can see it technically as not an archunit issue, but I can also see it as something that maybe 5-10% of companies trying it could hit.  
What to do to prevent or assist the scenario is not clear.  detect running in windows command before allowing debug printing?  setting the debug print to trace?  Just documenting the issue recommending not to log in debug, or how to filter out archunit debug logs?
I'll leave it to you since I'm working around it successfully.

**Comment by SpearThruster** [comment]
Hi both,

I would say that this is definitely an issue with `ArchUnit` because no other maven task fails when run through the Windows CMD. 

Also big thanks to @abeyecon for the detailed investigation, which I didn't have the time to do. <3

**Comment by codecholeric** [comment]
@SpearThruster I would argue that if this was an issue with ArchUnit, there should be at least one other terminal where this problem arises, besides CMD.
As far as I can tell, this problem happens only

 * if you enable debug
 * and are on Windows CMD

And only, because Windows CMD can't handle big outputs. Or am I wrong here? What would be the solution? That ArchUnit doesn't log any more on debug, because one terminal out there can't handle big outputs? Theoretically it might be possible to detect, if ArchUnit is running on Windows CMD, and then skip debug logging, but I would consider that also surprising, and I don't know, if that is the place where the issue needs to be fixed.

**Comment by hankem** [comment]
Would it help if ArchUnit logged a warning when running on Windows cmd with debug log enabled?
> Note that ArchUnit seems to be invoked from `cmd.exe`, which may not be capable to handle its debug log output. In case of problems, consider reducing the log level or using another shell.

**Comment by codecholeric** [comment]
I just don't know, if we can really reliably detect it? Maybe we could just print a general warning on DEBUG level in the beginning that certain terminals like Windows CMD can't handle big log outputs.
Or put it in the user guide, but who reads the manual :wink:

**Comment by abeyecon** [comment]
The simplest pragmatic solution I think would be to set the log level of the problem message to TRACE, but that has the downside of being surprising to ArchUnit devs, and also the problem would still occur if someone was running their tests at trace or ALL level (trace seems unlikely but perhaps ALL is more common?).
If you are trying to fix the situation altogether then maybe log aggregation is the best solution?  (e.g. rather than print one log per item handled, print one message per x timeunit OR per x calls OR per class listing all items)

**Comment by codecholeric** [comment]
But as you say, that would not really solve the problem, because if anyone sets the log level to TRACE then, the same problem arises. 
I mean, log level DEBUG is not meant to be run all the time, it's more something you would turn up, if things behave strangely, wouldn't it?
I understand your specific situation, that you have no control about the log level, but in general I consider it somewhat strange to switch the level to DEBUG and then complain that a lot of log outputs are generated :thinking: 
I mean the beauty of a logging framework in general is, that you can configure every logger to the level and output you want, right? The only bad thing is the Windows CMD having such an unexpected behavior when confronted with big log outputs.
But I'll look into it again, maybe it would make sense to log the problematic statement for Windows CMD on TRACE. 
And then when an issue is opened about Windows CMD dying on debug level TRACE, I'll just pour a glass of whiskey and drown my sorrows :wink:

**Comment by abeyecon** [comment]
20 years ago I worked on a govt department project to make a web based application for their core business.  About 500 people for two years.  Three months before go-live they realized that they wouldn't be able to work if the internet went down, and so we had to make a thick client for them.
I think every project hits a whiskey point at some stage.

**Comment by SpearThruster** [comment]
I think tacking this at the core of the library would be the most noble approach. 

Many people that program in Java actually use Windows (and hence the Windows CMD). I recently switched to a Mac as main dev machine, but up until now no java jar in the past 7 years had this kind of Windows CMD incompatibility in my projects. :)

**Comment by codecholeric** [comment]
FYI, with #291 I have reduced the log level for the real gory details (which method gets imported, which access has been found) to `TRACE` :wink: 
I don't think there is much more that ArchUnit can do (except adding some kill switch to completely disable logging maybe :wink:), since detecting Windows and dynamically adjusting the logging if run on CMD is super brittle I think.
So on `DEBUG` the most output should come from every class being logged once on import, but not too much more, so I think even Windows CMD should be able to handle it in most cases (but I couldn't test it extensively). Of course if someone configures ArchUnit to log on `TRACE`, it will be the same story all over again :wink:. But `TRACE` should be a lot less common...

**Comment by arundotin** [comment]
I am also facing the same issue in my mac terminal

The test cases are failing in IntelliJ. But when i run `mvn clean install` in my terminal, none of the archunit test cases are failing (genuine failures)

Below is the only log i see

```
[INFO] Running com.paypal.risk.chargebacks.archrules.CommonArchRulesSpec
20:21:01.365 [main] INFO  c.tngtech.archunit.core.PluginLoader - Detected Java version 1.8.0_232
```

**Comment by henrykuijpers** [comment]
Running into the following issue:

```
[INFO] Running nl.x.x.architecture.GeneralCodingRulesTest
/bin/sh: line 1:   674 Terminated           '/usr/java/jdk-11.0.16.1/bin/java' '-javaagent:/home/waas/.m2/repository/org/jacoco/org.jacoco.agent/0.8.10/org.jacoco.agent-0.8.10-runtime.jar=destfile=/home/jenkins/workspace/xxx-xxx@2/services/target/jacoco-unit.exec' '-jar' '/home/jenkins/workspace/xxx-xxx@2/services/target/surefire/surefirebooter-20240117101537250_9.jar' '/home/jenkins/workspace/xxx-xxx@2/services/target/surefire' '2024-01-17T10-13-31_364-jvmRun1' 'surefire-20240117101537250_7tmp' 'surefire_1-20240117101537250_8tmp'
```

It seems that I'm hitting the same issue?

What is a good workaround to tackle this problem? I also don't properly understand the issue, as for us the issue doesn't occur *always*, it occurs regularly,but retrying the build (on jenkins) often is succesful. It's just hurting our CI/CD.
