### ISSUE TITLE
Layered architecture by names

### ISSUE THREAD

**Issue by blackfoxoh** [TNG/ArchUnit#228]
Hi
I really like the idea of the layerd architecture check but sadly it seems to depend on the layers beeing identifyed by package.
We use packages by feature and have xxxFacade and xxxService in the same package per feature. Would it be possible to add something like `layer('Facade').definedByClassSimpleNameContaining('Facade')` ?
Or is there something I missed to achieve this with current version of ArchUnit?

**Comment by codecholeric** [comment]
Honestly I think that if you care about clear layers within your features, you should introduce a subpackage structure modelling that :wink: (i.e. `com.myapp.order.facade` and `com.myapp.order.service`). Typically it's not just those toplevel classes called `*Facade` or `*Service`, but any parameters or utilities that those classes need, where the borders start to get fuzzy.
Nevertheless, I think it would be a good idea to make `LayeredArchitecture` more powerful. I think this could simply be accomplished by offering a more generic

```
// predicate.apply(..) == true <==> JavaClass in layer
layer("foo").definedBy(describedPredicate)
```

Then the existing `definedBy(packageIdentifier)` would simply be a special case of the generic API and everything should be consistent. And it would naturally be powerful enough to cover your use case.
However, I won't have time for a while to implement this. I think this would be a good start to contribute though, because it's a very limited scope and easy to describe. So I'll keep it open and see if anyone wants to help here :smile_cat:
