### ISSUE TITLE
Support Java 14

### ISSUE THREAD

**Issue by sormuras** [TNG/ArchUnit#230]
Seems like the bundled ASM version doesn't support `class file major version 58` yet:

```
13:42:00.069 [Test worker] WARN  com.tngtech.archunit.core.importer.ClassFileProcessor - Error during import from jrt:/java.base/java/lang/Byte.class, falling back to simple import
java.lang.IllegalArgumentException: Unsupported class file major version 58
    at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:195) ~[archunit-0.11.0.jar:0.11.0]
    at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:176) ~[archunit-0.11.0.jar:0.11.0]
    at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:162) ~[archunit-0.11.0.jar:0.11.0]
    at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:283) ~[archunit-0.11.0.jar:0.11.0]
    at com.tngtech.archunit.core.importer.ClassFileProcessor$UriImporterOfProcessor.tryImport(ClassFileProcessor.java:186) ~[archunit-0.11.0.jar:0.11.0]
```

https://github.com/junit-team/junit5/runs/215132755#step:4:984 running an ArchUnit test on OpenJDK 14.

**Comment by sormuras** [comment]
According to https://asm.ow2.io/versions.html did ASM `7.2 beta` _add support for Java 14_.

**Comment by codecholeric** [comment]
Yes, you're right. How urgent is this for you? If you need this ASAP I could release a new version bundling ASM `7.2 beta` (test coverage is IMHO good enough to be confident that this version is stable enough for ArchUnit, if it passes the test suite).
Otherwise the release cycles on https://asm.ow2.io/versions.html suggest that there might be a stable version coming out soon. So if it's not dead urgent for you, I'd release as soon as the stable `7.2` is released.
Alternatively I could do a quick "`java14-SNAPSHOT` release", where "`java14-SNAPSHOT`" means I could publish to Maven Central SNAPSHOTs and never touch it again afterwards, until the stable release is out :wink: 
Which would you prefer? Quick but "stable" SNAPSHOT until the real release of ASM `7.2`, full release with ASM `7.2-beta` or simply wait for ASM `7.2` and live with the fact that ArchUnit won't work for JDK 14 till then? (hoping that it will only be a couple of weeks, of course)

**Comment by codecholeric** [comment]
Okay, cool, even though I would be confident that ArchUnit would work, if all the tests run, I still feel better not to release it with a beta version inside of its guts :wink:

**Comment by hankem** [comment]
I noticed that ASM 7.2 has been out for one and a half weeks already. 😉

**Comment by sormuras** [comment]
Thanks for the heads-up and the PR. @codecholeric ... merge and release? 🤓 

https://github.com/junit-team/junit5/commit/1e96d9435def02bf3a5a84a5afc2ccf55d8f97d2/checks?check_suite_id=263277116#step:4:1083

**Comment by codecholeric** [comment]
Yes, I'm on it! I'll merge those open PRs and release ASAP :smiley:
