### ISSUE TITLE
consistent methods for classes() and methods()

### ISSUE THREAD

**Issue by destan** [TNG/ArchUnit#239]
`classes().that().haveSimpleNameStartingWith()` is available but `methods().that().haveSimpleNameStartingWith()` is not.

we need to use `methods().that().haveNameMatching()`

wouldn't it be nice to have the methods of `classes()` and `methods()` as consistent as possible? or is there a specific reason not to?

**Comment by codecholeric** [comment]
Ay, sorry for getting back so late! The reason here was, that ArchUnit is aligned closely with the Java Reflection API to be familiar to Java developers. So there is `Class.getSimpleName()`, but there is no `Method.getSimpleName()`. Inconsistencies are mainly taken over from the Java Reflection API, but I think it's worth it in general.
From an ArchUnit point of view, it should maybe be `JavaClass.getFullName()` for the FQN, `JavaClass.getName()` for the simple name, and the same for methods, but due to the decision to be consistent to the Reflection API, that's not how it is at the moment.
To be consistent with the current API, we could extend `members()...haveName{startingWith,containing,endingWith}(..)` similar to `classes()` with the simple name.

**Comment by codecholeric** [comment]
If anybody wants a good starter task :wink:, it would be nice to extend the fluent API (i.e. `MembersThat` and `MembersShould`) with methods

* `members().that().haveNameStartingWith(..)`
* `members().that().haveNameContaining(..)`
* `members().that().haveNameEndingWith(..)`
* `members().should().haveNameStartingWith(..)`
* `members().should().haveNameContaining(..)`
* `members().should().haveNameEndingWith(..)`
