### ISSUE TITLE
Freezing Architecture Tests doesn't work well with Lambdas

### ISSUE THREAD

**Issue by Rocketeer007** [TNG/ArchUnit#248]
I have a problem with a frozen rule when building on my CI server.

I'm using the standard rule `NO_CLASSES_SHOULD_ACCESS_STANDARD_STREAMS` - but due to lots of legacy code, I've had to freeze the rule as a starting point:
```
@ArchTest
    public final ArchRule no_new_access_to_standard_streams = freeze(NO_CLASSES_SHOULD_ACCESS_STANDARD_STREAMS);
```

In the saved rules file, I have something like this (class names redacted):
```
Method <my.company.package.MyClass.lambda$myFunction$2()> calls method <java.io.IOException.printStackTrace()> in (MyClass.java:123)
```

However, when this builds on Jenkins, I'm getting a test failure like this:
```
Method <my.company.package.MyClass.lambda$myFunction$114()> calls method <java.io.IOException.printStackTrace()> in (MyClass.java:123)
```

I guess that something is slightly different on the CI server compared to my local build, and as a result the Lambda is getting a different ID.

Unfortunately, I can see that this would be a problem even with a local build - if I added a new lambda at the top of a class, I would expect the lambdas later on to get renumbered, and that would cause the freezing to fail.

Is there any way we can get the ID of lambdas to be ignored - in the same way that line numbers are ignored to support refactoring?

**Comment by hankem** [comment]
[`FreezingArchRule`](https://static.javadoc.io/com.tngtech.archunit/archunit/0.11.0/com/tngtech/archunit/library/freeze/FreezingArchRule.html) allows you to [reconfigure the `ViolationLineMatcher`](https://static.javadoc.io/com.tngtech.archunit/archunit/0.11.0/com/tngtech/archunit/library/freeze/FreezingArchRule.html#associateViolationLinesVia(com.tngtech.archunit.library.freeze.ViolationLineMatcher)), which decides which lines of a violation description are known already.

Therefore, you could probably use something like this:
```java
private static final ViolationLineMatcher FUZZY_LINE_NUMBER_MATCHER = new FuzzyLineNumberMatcher();

private static String normalizeLambdaViolation(String line) {
    return line.contains("lambda$") ? line.replaceFirst("\\$[0-9]+", "\\$") : line;
}

@ArchTest
public static final ArchRule no_new_access_to_standard_streams =
        freeze(NO_CLASSES_SHOULD_ACCESS_STANDARD_STREAMS)
                .associateViolationLinesVia((line1, line2) ->
                        FUZZY_LINE_NUMBER_MATCHER.matches(
                                normalizeLambdaViolation(line1),
                                normalizeLambdaViolation(line2)
                        )
                );
```
Unfortunately, `com.tngtech.archunit.library.freeze.ViolationLineMatcherFactory.FuzzyLineNumberMatcher` is currently (as of ArchUnit 0.11.0) not public, so you might have to copy its code in order to (re)use it.

**Comment by codecholeric** [comment]
As a follow up we could ponder, if we want to adjust the default line matcher to ignore lambda and anonymous class infixes in general? It does not seem to be useful to distinguish between a violation being caused by the class itself or a lambda in the class. In particular if for lambdas the numbering is not deterministic...
I.e. make `FuzzyLineNumberMatcher` a `FuzzyClassMatcher` that ignores all `\$\d` and `:\d`.

**Comment by kristofdepypere** [comment]
I just bumped on the same exact issue. It would be great to include this in the default line matcher.

**Comment by codecholeric** [comment]
Okay, I think it makes sense, let's add that to the next release :smiley: 
Until then I hope you're okay with configuring the extended fuzzy line number matcher from https://github.com/TNG/ArchUnit/issues/248#issuecomment-541129944
