### ISSUE TITLE
Idea: Rules on statement-level

### ISSUE THREAD

**Issue by tvinke** [TNG/ArchUnit#260]
There are a few possible use cases I'm looking for to find out if ArchUnit supports this. These have to do with the kind of _static code analysis_ tools like Sonarqube can perform on **statement** level. 

I'd like to check (and possible enforce) these kind of (quality) 'rules' e.g.

* a method should not have more than X nested `if`-statements
* a method should not exceed Y lines/statements
* there should be a try-catch block around the calling of method Z

It seems next to the existing architectural units --  such as constructors, fields, methods, classes, etc -- ArchUnit would need to support (parsing) individual statements/expressions right? 

Is this on the roadmap already? Would this be a nice addition to the ArchUnit feature-set? If so, and nobody's working on this already, would you mind if I'd take a stab at it (initial contribution through the process of a PR etc) or just get a discussion going?

**Comment by destan** [comment]
Another very useful one would be "never catch generic exceptions".

**Comment by codecholeric** [comment]
Sorry that I never got this discussion going :disappointed: From my side personally this is due to the fact that I still haven't finished generics support and that I consider more to the core of ArchUnit (and I have a couple of other ideas in the pipeline that also deal more with "architecture" as opposed to code-style / best practices where I would put these features in). 
Nevertheless if it is not a fundamental hit to performance I could imagine this as a nice addition (and I know there are also people out there that would use it :wink:). I.e. if `JavaCodeUnit` would supply `getIfStatements()` or `getLength()`, and the import runs with a similar speed. Or alternatively to encapsulate this additional information and make it configurable, e.g. if the heap grows rapidly from all the additional information imported. I think that might be the way to go anyway, to integrate it in a non-obtrusive way and make it configurable (if measurements show, that it really has an impact for e.g. 50000 classes). I would not want to impact the core import in a noticeable way for users that need to import big projects and have no interest in these metrics.
So altogether I would be open for a PR taking a shot at this, and I can supply some support how to integrate it best, but I have no capacity to do any "real work" on it :wink: There also have been a couple of related issues in the past: #374, #227

**Comment by codecholeric** [comment]
Gonna close this due to inactivity. If anybody really has the capacity to tackle this, feel free to reopen!
