### ISSUE TITLE
Potential split-package issue

### ISSUE THREAD

**Issue by remal** [TNG/ArchUnit#261]
I'm using ArchUnit JUnit5 and, as I can see, it has a potential split-package issue - both `archunit-junit5-api` and `archunit-junit5-engine` artifacts have classes inside `com.tngtech.archunit.junit`.

But JPMS doesn't allow different modules to have classes in the same package.

Potentially this will cause some issues with running ArchUnit on JVM 9+.

**Comment by codecholeric** [comment]
Yes, I'm aware of that :frowning_face: I didn't want to break the API so far, because nobody has reported an actual issue (so far always just a potential one), but I think we should fix it. Maybe when we release 1.0 it would be a good time to do this.
Actually moving the engine shouldn't cause any breakages, since no user should depend on those classes.
Historically the reason it is as it is, is because `archunit-junit4` and `archunit-junit5*` share a lot of code from package `com.tngtech.archunit.junit`, so it seemed easiest to add everything to the same package, also enabling package visibility for classes that should not be exposed.
I'll look into it, maybe I can do something with the Shadow plugin, simply relocating some files in `archunit-junit5-engine`, we'll see...

**Comment by codecholeric** [comment]
Closing this in favor of #206
