### ISSUE TITLE
Is it possible to assert that a given set of classes are not accessed outside its parent package?

### ISSUE THREAD

**Issue by joaodias14** [TNG/ArchUnit#270]
Many thanks for this very useful library! Below you can find my use case.
Please consider the following packages structure:

- event
   - controller
      - ControllerClass.java
   - service
      - ServiceClass.java
   - repository
      - RepositoryClass.java

I want to assert that `ControllerClass.java` only access `ServiceClass.java` (controller must only access services inside the same parent package) and that `RepositoryClass.java` is only accessed by `ServiceClass.java` (repository must only be accessed by services inside the same parent package).
Moreover, I would like to make this generic, since I have a couple of packages with a similar structure (that should follow this same rule) and I want to avoid asserting each one of them explicitly. Is there any way to do this with slices?

Thanks!

**Comment by codecholeric** [comment]
I don't know if I understand all the constraints, but one possibility (considering only the details you told me) would be to combine `slices` and `layeredArchitecture` (because in the end you always want to enforce the same technical layers, and independence on a "business" level).

I'll call the things referred to by "couple of packages with a similar structure" `foo` :wink: (since I don't know the business background, maybe "event types" or similar from the little tree you provided? But I don't know enough) 
It depends a little on what should happen with respect to classes that are outside of your packages with similar structure. If you don't care about those, a quick attempt could be something like

```
@ArchTest
static final ArchRule foos_should_not_depend_on_each_other =
    slices().matching("..myapp.allfoos.(*)..").should().notDependOnEachOther();

@ArchTest
static final ArchRule technical_layers_have_correct_dependencies =
    layeredArchitecture()
        .layer("Controller").definedBy("..controller..")
        .layer("Service").definedBy("..service..")
        .layer("Repository").definedBy("..repository..")
        .whereLayer("Controller").mayNotBeAccessedByAnyLayer()
        .whereLayer("Service").mayOnlyBeAccessedByLayers("Controller")
        .whereLayer("Repository").mayOnlyBeAccessedByLayers("Service");
```

This assumes that your different "packages with a similar structure" reside directly under the package `allfoos` :wink: And pretty much, that all those children of `allfoos` should then be independent. If that is not the case, this can be further customized using a `SliceAssignment`...

Does this help you? Or did I misunderstand you?

**Comment by joaodias14** [comment]
Hi  @codecholeric, thanks for your answer.
I forgot to add an important detail, which is the fact that the one service may access another even if on different parent package.
Having said that, the first test will fail if I understood it correctly. Is there any way to further customize this test?

Thanks again!

**Comment by codecholeric** [comment]
Yes, if there is one thing that ArchUnit is, it's customizable :wink: 
One solution could for example be to write your own condition for slices:

```
@ArchTest
public static final ArchRule demo = slices()
    .matching("..allfoos.(*)..")
    .should(onlyDependOnServicesInOtherSlices());

private static ArchCondition<Slice> onlyDependOnServicesInOtherSlices() {
    return new ArchCondition<Slice>("only depend on services in other slices") {
        Set<JavaClass> allClassesInSlices;

        @Override
        public void init(Iterable<Slice> allSlices) {
            allClassesInSlices = StreamSupport.stream(allSlices.spliterator(), false)
                    .flatMap(Collection::stream)
                    .collect(toSet());
        }

        @Override
        public void check(Slice slice, ConditionEvents events) {
            slice.getDependenciesFromSelf().stream()
                .filter(dependency -> allClassesInSlices.contains(dependency.getTargetClass()))
                .filter(dependency ->
                        !dependency.getOriginClass().getName().contains(".service.") ||
                        !dependency.getTargetClass().getName().contains(".service."))
                .forEach(dependency -> events.add(SimpleConditionEvent.violated(dependency, dependency.getDescription())));
        }
    };
}
```

**Comment by joaodias14** [comment]
Many thanks @codecholeric !
