### ISSUE TITLE
Provide an Aggregator POM for archunit-junit5

### ISSUE THREAD

**Issue by joshiste** [TNG/ArchUnit#272]
Imho it would be great if you'd provide a maven bill of materials. So you can import it into the dependencyManagement and have all versions defined in one place.

**Comment by codecholeric** [comment]
Can you elaborate, what such a BOM for ArchUnit would contain in your view? Except for JUnit 5 support, including ArchUnit is literally adding one dependency to your POM. Can you describe how a BOM would make your life easier there? (because I usually like having a BOM, too, but in that case I don't feel like it would make my life much easier? To me it feels like a BOM is gaining value, if you have multiple dependencies and these dependencies might have different versions that need to match...)

**Comment by joshiste** [comment]
>Except for JUnit 5 support...

Exactly. I was just surprised to add two dependencies for the junit support.

**Comment by rweisleder** [comment]
We could do the same as JUnit 5 itself. They provide the artifact `junit-jupiter` which users add as test-scoped dependency. `junit-jupiter` has a compile-scoped dependency to `junit-jupiter-api` and a runtime-scoped (test-runtime-scoped) dependency to `junit-jupiter-engine`.

see [junit-jupiter](https://github.com/junit-team/junit5/blob/r5.5.2/junit-jupiter/junit-jupiter.gradle.kts)

**Comment by codecholeric** [comment]
@joshiste Ah, okay. I know that as an aggregator POM, not a BOM, so I was confused :wink:
The way I understand BOM, the purpose would be to ensure consistent versions between artifacts, but not to provide those as dependencies (i.e. you would still separately declare the dependencies, but the versions would match).
We could publish such a POM, I guess. For Maven it would actually be equivalent to simple add `archunit-junit5-engine` with scope `test` and just pull in `archunit-junit5-api` automatically :wink: (since Maven unfortunately has no scope `testRuntime`)
If you want, you can provide a PR and I'll merge it, otherwise I'll do it, when I get around to it (or with some luck someone else will jump in). I guess we would just add an almost empty directory to `archunit/juni5` containing just the Gradle config to create the aggregator POM.

**Comment by joshiste** [comment]
> Ah, okay. I know that as an aggregator POM, not a BOM

Sorry for confusing you. Yeah that are different things. After your first comment it came to my mind an aggregator pom should suffice.

> We could publish such a POM, I guess. For Maven it would actually be equivalent to simple add archunit-junit5-engine with scope test and just pull in archunit-junit5-api automatically 😉 (since Maven unfortunately has no scope testRuntime)

The aggregator pom, let's call it `archunit-junit5`, should have a api depency on `archunit-junit5-api` and a runtimeOnkly dependency on `archunit-junit5-engine`. (See [junit-jupiter](https://github.com/junit-team/junit5/blob/master/junit-jupiter/junit-jupiter.gradle.kts) as an example)
