### ISSUE TITLE
Sonar Rule "Empty Test" triggered for ArchUnit Tests

### ISSUE THREAD

**Issue by abeyecon** [TNG/ArchUnit#276]
Sonar squid:S2187 is violated by every ArchUnit test.  Need to get Sonar to update their rule?
Sonar Version: Community EditionVersion 7.7 (build 23042)

**Comment by codecholeric** [comment]
Thanks for raising the issue, but I think this is the wrong place, don't you think? There is not much ArchUnit can do about that, but I see several steps you could take:

* raise the issue at Sonar (because I think their detector is wrong with respect to ArchUnit)
* ignore those classes from being checked by Sonar
* use a different naming pattern (don't use `...Test...`)
* use plain JUnit tests for your ArchUnit tests (even though not optimal)

**Comment by abeyecon** [comment]
https://community.sonarsource.com/t/s2187-reports-all-archunit-tests-as-empty-java/17703

**Comment by codecholeric** [comment]
Thanks a lot! Is it okay to close this issue then for now?

**Comment by abeyecon** [comment]
Issue accepted in sonar:
https://jira.sonarsource.com/browse/SONARJAVA-3263
