### ISSUE TITLE
Add support for records (Java 14 preview feature)

### ISSUE THREAD

**Issue by rweisleder** [TNG/ArchUnit#295]
Java 14 will bring us [JEP 359](https://openjdk.java.net/jeps/359) (preview feature) which introduces records as a new kind of type declaration.

We should support records like we support enums. I suggest to add the following methods:
* JavaClass.isRecord
* classes().that().are[Not]Records()
* classes().should().[not]BeRecords()

ASM supports records since 7.3.1 (released yesterday). The [release notes](https://asm.ow2.io/versions.html) are not available yet, but the code contains the [merge request for records](https://gitlab.ow2.org/asm/asm/commit/db802e6eb64784567b81277f28734421b9dc878e). So I guess records should be part of that version.

So that we are able to test the implementation, we need to build ArchUnit against JDK 14 with enabled preview features.
Do we need an additional testing source set in our Gradle build? Or could this be done inside src/test/java?

**Comment by codecholeric** [comment]
Ah damn, could have merged that into `0.13.0`, but hey... Yes, we should support records then. I guess since the JDK looks likely to integrate this into `java.lang.Class`, it makes sense to extend `JavaClass` in a similar way.

As for the technical part, I would try to add a new source set `src/jdk14test/java`, because for these tests we will have to switch the source and target level to 14 and I think it would be confusing to do that with the normal `src/test/java` while keeping `src/main/java` at a source and target level 7 (which it needs to stay). Since we will not need any new `main` features that require Java 14 (ASM is the API and as long as ASM is compatible to JDK 7 ArchUnit will be, too), it should not be necessary to add a `src/jdk14main/java` source set, because any extension can just be made JDK 7 compatible within `src/main/java`.

Your proposed API extensions look good to me :smiley: 

Other than that, maybe one day we'll drop JDK 7 compatibility and can finally use Java 8 features within ArchUnit's own code :wink: (outside of JUnit 5 support). But I also want to support legacy projects... Should do some research at some point how widely spread JDK 7 still is (I would hope not far, but the question is, how low the threshold should be to drop JDK 7 compatibility)

**Comment by rweisleder** [comment]
Currently, I'm having issues with Gradle and JDK 14 EA. It looks like Gradle is not ready for JDK 14 yet: https://github.com/gradle/gradle/issues/10248

Nevertheless, I try to implement this as far as possible.
