### ISSUE TITLE
Having trouble to ignore classes

### ISSUE THREAD

**Issue by lsoares** [TNG/ArchUnit#297]
Hey,

I've trying to ignore some classes within a layered architecture rule but I can't. I've tried many combinations but the classes are never ignored. Is it because I'm using Kotlin? Because the `AppMainKt` can't be referenced from the codebase as it is generated. Is it because I'm using Javalin web server? Because it seems also to be classes generated inside `WebConfig` by Javalin.

[I posted problem and the source code at Stack Overflow](https://stackoverflow.com/questions/59678301/how-to-exclude-a-class-in-an-archunit-rule/59689433). The project is just a dummy one, so it's quite easy to run. 

Currently I get:

```
> java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'Layered architecture consisting of
> layer 'web handlers' ('..web.handlers')
> layer 'use cases' ('..usecases')
> layer 'persistence' ('..persistence')
> where layer 'web handlers' may not be accessed by any layer
> where layer 'use cases' may only be accessed by layers ['web handlers']
> where layer 'persistence' may only be accessed by layers ['use cases']' was violated (6 times):
> Method <users.AppMainKt.main()> calls constructor <users.persistence.MySqlUserRepository.<init>(org.jetbrains.exposed.sql.Database)> in (AppMain.kt:13)
> Method <users.AppMainKt.main()> calls method <users.persistence.MySqlUserRepository.createSchema()> in (AppMain.kt:13)
> Method <users.WebAppConfig$javalinApp$1$2.addEndpoints()> calls constructor <users.usecases.CreateUser.<init>(users.domain.UserRepository)> in (AppMain.kt:27)
> Method <users.WebAppConfig$javalinApp$1$2.addEndpoints()> calls constructor <users.usecases.ListUsers.<init>(users.domain.UserRepository)> in (AppMain.kt:26)
> Method <users.WebAppConfig$javalinApp$1$2.addEndpoints()> calls constructor <users.web.handlers.CreateUser.<init>(users.usecases.CreateUser)> in (AppMain.kt:27)
> Method <users.WebAppConfig$javalinApp$1$2.addEndpoints()> calls constructor <users.web.handlers.ListUsers.<init>(users.usecases.ListUsers)> in (AppMain.kt:26)
```

Thanks!

**Comment by codecholeric** [comment]
If you say "`AppMainKt` can't be referenced from the code base", do you mean you don't have a class `AppMain.kt` at all? Because AFAIK if you use `AppMain::class.java` it translates to a reference to the respective (generated) Java class.

Anyway, to solve the problem for generated code that you cannot access from your compile scope, I would suggest to try one of the following:

### Exclude synthetic code

If the byte code is generated by some framework, it often has the `SYNTHETIC` modifier to detect this. You could exclude this by adding

```
import static com.tngtech.archunit.base.DescribedPredicate.alwaysTrue;
import static com.tngtech.archunit.core.domain.JavaModifier.SYNTHETIC;
import static com.tngtech.archunit.core.domain.properties.HasModifiers.Predicates.modifier;
...

layeredArchitecture()
    ...
    .ignoreDependency(modifier(SYNTHETIC), alwaysTrue());
```

### Use a naming pattern

By using a regex you could just exclude all classes matching a certain pattern. You have to be careful to not use a too generic pattern that misses violations, but in your case, maybe something like

```
import static com.tngtech.archunit.base.DescribedPredicate.alwaysTrue;
import static com.tngtech.archunit.core.domain.properties.HasName.Predicates.nameMatching;
...

layeredArchitecture()
    ...
    .ignoreDependency(
        nameMatching(".*\\.AppMainKt").or(nameMatching(".*\\.WebAppConfig\\$.*")), 
        alwaysTrue())
```

Does that help you?

**Comment by lsoares** [comment]
hey! thank you for the reply

- it works using ` nameMatching(".*\\.AppMainKt").or(nameMatching(".*\\.WebAppConfig\\$.*"))`!! - regex works but it's not the "ideal", but since it's generated, I understand the compromise
- I tried using the `modifier(SYNTHETIC)` but didn't find any examples online and I was not sure how to adapt to my problem. can you help a little more?
- why doesn't `fullNameMatching` work for my case?
- `AppMain::class.java` does not exist at all, since `main()` is a global method in Kotlin. [Check it out](https://github.com/lsoares/clean-architecture-sample/blob/master/src/main/kotlin/users/AppMain.kt#L11)
- what's the difference from this technique to ignoring in the `check` phase? would it also work?

**Comment by codecholeric** [comment]
Oh, sorry that I didn't get back to you on this, somehow slipped through :frowning: 
Ah, sure, I forgot about the "scripty" way in Kotlin :wink: Yes, then you have no class (you could create one and move `main` to the companion object though, then you could refer to a class again, but just for the arch test makes this a little ugly...)
I don't know exactly what you mean by "`fullNameMatching` not working", because it's not in your example up here? It might be, because you did not supply a regex to `fullNameMatching`? Other than that, it should work...
I don't know what you mean by "ignoring in the `check` phase"? What's the difference with the way from my example? You declare some ignores and they will be ignored when `check` is called. Or do you mean input to the rule vs violations? Even if you filter some classes from the input classes, the others will still know their dependencies to the filtered classes, so rules still fail...
There is no "debug mode" per se, you can turn up logging, or usually set a break point within `com.tngtech.archunit.lang.ArchRule.Factory.SimpleArchRule#evaluate` because typically most rules in the end boil down to this. You can check which classes make it through the filtering by checking out the result of `classesTransformer.transform(..)`.

**Comment by codecholeric** [comment]
Closing this for now, feel free to reopen if you still have issues!
