### ISSUE TITLE
Exclude self from violations of onlyAccessedBy(..) by default

### ISSUE THREAD

**Issue by codecholeric** [TNG/ArchUnit#3]
When checking

```
classes()...should().onlyBeAccessedBy()...
```

it would make sense to ignore violations by self access by default. Often usecases look like

```
classes().that().resideInAPackage("..bar..").should().onlyBeAccessedByAnyPackage("..foo..", "..bar..")
```

because otherwise a ton of violations of '..bar..' calling itself would be reported.
It seems to never make sense, to report self-accesses, so this should be excluded by default, making rules easier to specify.

**Comment by codecholeric** [comment]
Actually this might be slightly harder, than I thought, since when checking for "onlyAccessedBy", it's not clear anymore, how the classes were filtered before (could be reside in package, but could also be annotated, named, or whatever), so it's hard to determine what "self" is. The class itself is no problem, but the package I chose on `that().resideIn()` would be much harder. This would be easier, if the rule would work on layers/slices as objects.

**Comment by nbrugger-tgm** [comment]
Is there a possibility at least the "self" part is revisited?

Here is what i try to :
```java
services
	.should().bePackagePrivate()
	.andShould().onlyBeAccessed().byItself()//doesnt exists
	.because("Service implementations should never be accessed directly");
```

**Comment by onepunchmagne** [comment]
Hey @codecholeric thanks for your work! I saw you fixed the initial issue with commit https://github.com/TNG/ArchUnit/commit/fbca4c92c2432ce26d35e33295a530861dbb2c21 which is packaged in `1.0.0-rc1` release, but I'm still having a problem with it. Could you have a look at this JHipster-Lite pull request please? https://github.com/jhipster/jhipster-lite/issues/2921  

Expected behavior is tested by proposed change `primaryJavaAdaptersShouldOnlyBeCalledFromSecondaries` based on an hexagonal architecture:  
```
classes()
  .that()
  .resideInAPackage("..primary..")
  .and()
  .areMetaAnnotatedWith(Component.class)
  .and()
  .haveSimpleNameStartingWith("Java")
  .should()
  .onlyBeAccessed()
  .byClassesThat()
  .resideInAPackage("..secondary..")
  .check(classes);
```
So basically I'm trying to pick all classes from a `..primary..` package (working) which are `@Component` or `@Service` etc (working) being a Java primary adapter i.e. starting with simple name "Java" (working) -> those classes should only be called by secondary adapters (working) BUT I get 3 violations from the class itself such as:  
>Constructor <tech.jhipster.lite.project.infrastructure.primary.JavaProjects.<init>(tech.jhipster.lite.project.application.ProjectsApplicationService)> sets field <tech.jhipster.lite.project.infrastructure.primary.JavaProjects.projects> in (JavaProjects.java:17)

>Method <tech.jhipster.lite.project.infrastructure.primary.JavaProjects.moduleApplied(tech.jhipster.lite.module.domain.JHipsterModuleApplied)> calls method <tech.jhipster.lite.project.infrastructure.primary.JavaProjects.projectActionToAdd(tech.jhipster.lite.module.domain.JHipsterModuleApplied)> in (JavaProjects.java:23)

>Method <tech.jhipster.lite.project.infrastructure.primary.JavaProjects.moduleApplied(tech.jhipster.lite.module.domain.JHipsterModuleApplied)> gets field <tech.jhipster.lite.project.infrastructure.primary.JavaProjects.projects> in (JavaProjects.java:23)

Would you have any understanding about that please? I wonder if the fix is not covering this case, or if I'm using the conjuction in a bad manner? Thank you!
