### ISSUE TITLE
Please annotate ArchTest annotation with meta-annotation Testable

### ISSUE THREAD

**Issue by remal** [TNG/ArchUnit#300]
Please annotate `com.tngtech.archunit.junit.ArchTest` annotation with meta-annotation `org.junit.platform.commons.annotation.Testable`.

From `Testable` [javadoc](https://junit.org/junit5/docs/5.3.0/api/org/junit/platform/commons/annotation/Testable.html):
> `@Testable` is used to signal to IDEs and tooling vendors that the annotated or meta-annotated element is testable.
> 
> In this context, the term "testable" means that the annotated method or class can be executed by a TestEngine as a test or test container on the JUnit Platform.

**Comment by rweisleder** [comment]
`@ArchTest` is already meta-annotated with `@Testable`:
https://github.com/TNG/ArchUnit/blob/v0.13.0/archunit-junit/junit5/api/src/main/java/com/tngtech/archunit/junit/ArchTest.java#L50-L54

Or is there something I'm missing?

**Comment by remal** [comment]
It's OK. Looks like I missed it. But... IDEA doesn't recognize class members annotated by ArchTest as something that would run tests and marks the members as unused... Do I miss smth? Do I have to elaborate on it?

**Comment by hankem** [comment]
Do you include the `archunit-junit5-engine` runtime dependency (or, new with ArchUnit 0.13.0, the combined `archunit-junit5` dependency, cf. [User Guide](https://www.archunit.org/userguide/html/000_Index.html#_junit_5))?

Does `example-junit5` from https://github.com/TNG/ArchUnit-examples work for you?

I just realized that IntelliJ IDEA (I'm currently using 2019.3.1) doesn't offer me to run individual tests based on `@ArchTest` annotated fields. But for me, it works at least for the entire test class:

![image](https://user-images.githubusercontent.com/4208552/73127424-545eef80-3fc0-11ea-95ba-77b3ff7bbefa.png)

**Comment by codecholeric** [comment]
Unfortunately IntelliJ can only run methods meta-annotated with `@Testable` :frowning_face:
That's why I originally created the artifact `archunit-junit5-engine-api`, which contains an API one could use to write an IntelliJ plugin that would in turn allow to execute `@ArchTest` fields. In the end the JUnit Platform AFAIS can be extended for new `DiscoverySelectors` and `ArchUnitTestEngine` already supports a `FieldSelector`, i.e. programmatically it would already be possible to request the engine to run one or multiple fields. But I could not find the time yet to write a plugin that would trigger that API :frowning_face:

**Comment by codecholeric** [comment]
Looking for a challenge, @klassm? :point_up:  :wink:

**Comment by klassm** [comment]
Hey @codecholeric - I can at least tell you that a reference implementation might be something like https://github.com/JetBrains/intellij-community/blob/master/plugins/junit/src/com/intellij/execution/junit/JUnit5Framework.java.

The relevant extension point would be "testFramework" referencing a "com.intellij.testIntegration.TestFramework".

Now here's the thing: I have no idea where to get that dependency from. It doesn't look like it has been published among the API of IntelliJ. And there's not much examples around ...

**Comment by rweisleder** [comment]
FYI: I created https://github.com/junit-team/junit5/issues/2168

**Comment by remal** [comment]
All in all IDEA does handle classes annotated by `com.tngtech.archunit.junit.AnalyzeClasses`. But there are some issues:
1. There is no opportunity to run the tests inside a class separately.
1. The tests are highlighted as "unused".

Please take a look at ![screenshot](https://user-images.githubusercontent.com/231188/73459883-a4ef9780-4388-11ea-9831-3ec0f194980f.png).

**Comment by codecholeric** [comment]
@klassm hmm, what I don't like is that there are a lot of `@Overrides` talking about `PsiMethod`, this seems very customized to being only able to run test methods but never anything else (like fields). 
What I don't see is where the actual delegation to JUnit Platform / Jupiter happens? I think it would make sense to contact Jetbrains before and ask them if they have any advice on where and how to hook in such an extension...

**Comment by codecholeric** [comment]
FYI: I created https://intellij-support.jetbrains.com/hc/en-us/requests/2472543 because I think this has to be solved in IntelliJ (and probably by us, I doubt anyone will do us the favor to integrate a special thing like executable fields in ArchUnit into a generic tool like IntelliJ :wink: And I doubt the JUnit team can do anything about it, either, since this is completely IDE specific, that IntelliJ does not know how to send `FieldSelectors` to the JUnit Platform)

**Comment by codecholeric** [comment]
@remal The second problem you can at least solve by adding `@ArchTest` members once to the list of exceptions, e.g. like this for some custom `@Example`:

![suppress_unused](https://user-images.githubusercontent.com/4095015/73468563-8e146980-43b7-11ea-9e9d-29035977a21e.png)

To have this automatically would IMHO also demand some plugin, since this is custom ArchUnit magic, that fields with `@ArchTest` are executable. Except if IntelliJ would decide to at least not show any member meta-annotated with `@Testable` as unused (which would kind of make sense, I guess, but again that would be an issue for Jetbrains)

**Comment by codecholeric** [comment]
I'll close this issue in favor of #341, since this issue's description does not match the problem we've worked out in the end.
