### ISSUE TITLE
Kotlin SAM type implementations are not always considered anonymous classes

### ISSUE THREAD

**Issue by marcphilipp** [TNG/ArchUnit#334]
When upgrading from 0.12.0 to 0.13.1, we replaced calls to `isAnonymous` to `isAnonymousClass`. However, some Kotlin SAM type implementations have an empty simple name and are no longer considered to be anonymous:
https://ge.junit.org/s/6slfzquelxlc4/tests/5uodjcz5nhszw-2vb5km5jsvlzc

Would it be possible/correct to use `innerName == null || innerName.isEmpty()` to determine whether a class is anonymous?

**Comment by codecholeric** [comment]
We changed some internals of ArchUnit, because checking for anonymous classes was a little shady before (as you noticed, we simply checked for `simpleName.isEmpty()`, which worked pretty well, but it felt a little like using some random trait to determine the type of the class).

In the last version we changed this (while refining the language and types of classes, e.g. ArchUnit was missing local classes, which seemingly almost nobody uses :rofl:). We now look into the byte code if this class has an `InnerClasses` tag but no name defined when we import this class. AFAIK by definition an anonymous class must have an enclosing class and thus the respective meta-information (you can see this from the definition of https://docs.oracle.com/javase/specs/jls/se14/html/jls-15.html#jls-15.9.5 -> "an anonymous class is always an inner class).

 I looked into your cases from the build scan / Junit repository and found some behavior I couldn't really explain. It seems that for `JavaInterface { /* SAM conversion by inline lambda */ }` and `JavaInterface(samConversionByLambdaPassedAsParameter)` the Kotlin compiler generates different bytecode. The former one will have an `InnerClasses` block and be detected as anonymous by the Reflection API, the latter one will not have one and also not be detected as anonymous by the Reflection API.

I really don't know where the difference comes from, I've opened a ticket with Jetbrains to ask about it: https://youtrack.jetbrains.com/issue/KT-37939

I understand that for the second case the reference is not really necessary. Still to me it seems semantically the same as the version with the inline lambda :thinking: 

However I'm puzzled now what the right behavior is. Because normally ArchUnit strives to be as close to the Reflection API as possible to keep confusion low. However the Reflection API in this case also behaves surprising :wink: (even though correct if you look at the bytecode). I will wait a little to see what Jetbrains have to say about this.

Meanwhile sorry for the inconvenience, I saw that you just added the old empty check as a workaround, so I guess your immediate pain is not terribly big?

**Comment by marcphilipp** [comment]
Thanks for looking into this! We don't have any immediate pain for now, I just wanted to let you know about the issue so we can sort out what would actually be the right behavior in this case. I've subscribed to the JetBrains issue. Let's see what they say.

**Comment by codecholeric** [comment]
This is an open Kotlin issue now, to create the inner class information in the latter case: https://youtrack.jetbrains.com/issue/KT-39907
I'll close this issue since it should be resolved as soon as the Kotlin issue is resolved. Feel free to open if you have any follow up questions / remarks! (and also if you notice that a future Kotlin version indeed doesn't have the problem anymore :wink: )
