### ISSUE TITLE
Simple class name make error message hard to understand or meaningless.

### ISSUE THREAD

**Issue by kosolart** [TNG/ArchUnit#338]
I try to write the unit test that test all method should not annotate with `javax.transaction.Transactional` and `javax.jdo.annotations.Transactional` 

```
MethodsShouldConjunction rule = ArchRuleDefinition.methods()
		.should()
		.notBeAnnotatedWith(javax.transaction.Transactional.class)
		.andShould()
		.notBeAnnotatedWith(javax.jdo.annotations.Transactional.class);
```

It evaluates rule name as `methods should not be annotated with @Transactional and should not be annotated with @Transactional`

Yeah, I got two @Transactional but I don't know what package it is.

Additionally, error message make me misunderstands too.
`Method <com.test.SimpleClass.doSomething(com.test.SimpleArgument)> is annotated with @Transactional in (SimpleClass.java:0)`

**Comment by codecholeric** [comment]
Yeah, you're right, that was one decision I made because for many other cases it reads better than the FQN. I don't think you can cover everything here, because I have a feeling the other way around there would be complaints that it is "too verbose" while it is clear from the simple name which annotation is meant :wink: 

However you can work around it in your case, e.g. with

```
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.equivalentTo;
import static com.tngtech.archunit.core.domain.properties.HasType.Functions.GET_RAW_TYPE;

// ...

ArchRule rule = methods()
    .should()
    .notBeAnnotatedWith(annotationType(javax.transaction.Transactional.class))
    .andShould()
    .notBeAnnotatedWith(annotationType(javax.jdo.annotations.Transactional.class))

// ...

private DescribedPredicate<HasType> annotationType(Class<? extends Annotation> type) {
    return GET_RAW_TYPE.is(equivalentTo(type)).as("@" + type.getName());
}
```

In other words supply your own `DescribedPredicate` to `notBeAnnotatedWith(..)` where you override the description to print "@ + FQN" of the type you pass in. This description will also be reused for the single reported violations, so your second problem should also be solved by this.

**Comment by kosolart** [comment]
It's work 😄 
Thanks for advice.
