### ISSUE TITLE
How to import a package without analyzing it?

### ISSUE THREAD

**Issue by daniel-shuy** [TNG/ArchUnit#339]
How can I import a package (eg. so that it will work with `JavaClass#isMetaAnnotatedWith(Class)`) without causing all classes in that package to be analyzed by ArchUnit?

For example, I have a test that checks if a class is annotated/meta-annotated with Spring's [@ContextConfiguration](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/ContextConfiguration.html). If I annotate a class with the [@SpringJUnitConfig](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/junit/jupiter/SpringJUnitConfig.html) meta-annotation (that composes [@ContextConfiguration](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/ContextConfiguration.html)), it will not pass the test, because [@SpringJUnitConfig](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/junit/jupiter/SpringJUnitConfig.html) is not imported by ArchUnit.

If I include the `org.springframework.test` package in [@AnalyzeClasses#packages](https://javadoc.io/static/com.tngtech.archunit/archunit-junit5-api/0.12.0/com/tngtech/archunit/junit/AnalyzeClasses.html#packages()), then it will also analyze all the classes in the `org.springframework.test`, which I don't want.

**Comment by codecholeric** [comment]
At the moment you unfortunately have to ensure that all the annotations involved are imported, too. I think this might be a little related to #142 and also to #274.
One solution might be to try to pimp the resolution from classpath to also cover annotations. At the moment for example with the standard config all super classes of the classes imported are imported as well. This might also make sense for annotations, but I couldn't get it to work when I tried it real quick for 30 min. So it is not completely trivial, but I think it would well worth it, since it's something that more people struggle with.
The only solution I can think about out of the box is to use a custom `ImportOption` similar to the suggestion in https://github.com/TNG/ArchUnit/issues/274#issuecomment-575199185
I know that is not as convenient as it should be...

**Comment by codecholeric** [comment]
I'll close this in favor of #342
