### ISSUE TITLE
archunit_ignore_patterns.txt not ignoring violations

### ISSUE THREAD

**Issue by gaurabdg** [TNG/ArchUnit#350]
contents of `archunit_ignore_patterns.txt`:
```
Method <com\.puppycrawl\.tools\.checkstyle\.api\.AutomaticBean\$RelaxedAccessModifierArrayConverter\.convert\(java\.lang\.Class, java\.lang\.Object\)> calls method <com\.puppycrawl\.tools\.checkstyle\.checks\.naming\.AccessModifier\.getInstance\(java\.lang\.String\)>.*

```

The first few lines of the violations produced:
```
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'slices matching 'com.puppycrawl.tools.checkstyle.(**)..' should be free of cycles' was violated (13 times):
Cycle detected: Slice api -> Slice checks.naming -> Slice api
Dependencies of Slice api
Method <com.puppycrawl.tools.checkstyle.api.AutomaticBean$RelaxedAccessModifierArrayConverter.convert(java.lang.Class, java.lang.Object)> calls method <com.puppycrawl.tools.checkstyle.checks.naming.AccessModifier.getInstance(java.lang.String)> in (AutomaticBean.java:398)
Dependencies of Slice checks.naming
```

4th line of the violation message is not getting ignored. Can someone please help me out?

**Comment by codecholeric** [comment]
Unfortunately `archunit_ignore_patterns.txt` is a very crude mechanism, that can probably not accommodate the complexity of the error message :frowning: Usually one line represents one error, so if you ignore the line you ignore the error. So to ignore all lines is equivalent to ignoring all errors. This is unfortunately not the case with cyclic dependencies, because if all dependencies of one edge are ignored, one would think all violations vanish. But `archunit_ignore_patterns.txt` does not support this, because you would need to match each line of the error message with your ignore pattern, even the one where it says "Cycle detected". This makes i.g. little sense.

Long story short, you should probably do one of two things

a) is this a violation that will be okay for all times? (because you have decided it's not worth the effort to correct it, a false positive, etc.) Then you can use the API method

```
slices()...should().beFreeOfCycles()
    .ignoreDependency(RelaxedAccessModifierArrayConverter.class, AccessModifier.class)
```
(or other variant of `ignoreDependency(..)` if you need to be more generic or don't have access to the class objects)

b) if you eventually want to fix this violation but don't have the time at the moment, you could look into https://www.archunit.org/userguide/html/000_Index.html#_freezing_arch_rules which is a more powerful version of the `archunit_ignore_patterns.txt`

Does this help you?

**Comment by gaurabdg** [comment]
@codecholeric Thanks a lot for your detailed explanation. I understood after I looked at the commit for this feature. I was looking for a alternate solution to freezing rule. Nevermind, I figured out a workaround, thanks again. I am closing this issue.

**Comment by codecholeric** [comment]
Glad you could solve it! :smiley:
