### ISSUE TITLE
How to check for string concatenation in logger statements

### ISSUE THREAD

**Issue by phermsdorf** [TNG/ArchUnit#354]
Hi,

is it possible to detect wrong usage of log statements of this kind:

logger.error("Some log message. Value: " + object.getValue());
logger.error("Some log message. Value: " + object.getValue(), e);

Correct usage would be:

logger.error("Some log message. Value: {}", object.getValue());
logger.error("Some log message. Value: {}", object.getValue(), e);

Thanks for any hints on this!

Bye Peter

**Comment by codecholeric** [comment]
Assertions like "as arguments of method x you may not use a String that has been constructed by concatenation" are unfortunately a little bit out of scope of ArchUnit :wink: (it would probably be possible to extract that kind of info from the bytecode, but ArchUnit doesn't extract such complex combinations.

What you can easily do is to forbid calls to the Method `Logger.error(String)` instead of the method `Logger.error(String, Object[])`, if you know there should always be some argument to log. But then you cannot by default log a simple message without an argument anymore.

Other than that IDEs like IntelliJ also have an inspection + quick fix for this, so maybe there is a tool better suited for your purpose...

**Comment by phermsdorf** [comment]
OK, thanks for the explanation.
