### ISSUE TITLE
Slices of Distinct Packages Should Not Collide

### ISSUE THREAD

**Issue by jzheaux** [TNG/ArchUnit#360]
I've got a GitHub project that demonstrates my situation probably a bit better than I'll explain it below: https://github.com/jzheaux/archunit-sample

---

If I have the following package structure:

```java
sample
--> a
------> A.java
--> b
------> B.java
--> a.b
------> C.java
```

And then create the following relationship:

```java
public class A {
    public A() {
        new C();
    }
}
```

```java
public class B {
    public B() {
        new A();
    }
}
```

Then the following construct will report a cycle:

```java
String pkg = "sample";
JavaClasses classes = new ClassFileImporter().importPackages(pkg);
slices().("..(*)..").should().beFreeOfCycles()
		.check(classes);
```

even though there isn't one.

If I create a `SliceAssignment`, like so:

```java
SliceAssignment fullyQualifiedPackageSlices = new SliceAssignment() {
	@Override
	public SliceIdentifier getIdentifierOf(JavaClass javaClass) {
		return SliceIdentifier.of(javaClass.getPackageName());
	}

	@Override
	public String getDescription() {
		return "FQ package slices";
	}
};
```

and then change the test to:

```java
String pkg = "sample";
JavaClasses classes = new ClassFileImporter().importPackages(pkg);
slices().assignedFrom(this.fullyQualifiedPackageSlices).should().beFreeOfCycles()
		.check(classes);
```

then no cycle is reported.

I believe the reason is because both `a.b.C` and `b.B` are placed in the same slice `b` by default, making `B` -> `A` -> `C` appear to be a cycle. When I use fully-qualified package names, the ambiguity is removed.

I think that slices, by default, should use the fully-qualified package name, or is there some reasoning I'm missing?

**Comment by codecholeric** [comment]
Thanks for your detailed explanation and example! I think the reason is, that the pattern you use `..(*)..` will translate to "arbitrary many packages, then capture a single relative package name". Which in particular means, every class will be assigned to a slice identified by the local package name only. And by that both classes that reside in some local package `b`, be it `a.b` or just `b` will belong to the same slice.

What you can do is to use the pattern `(**)`, which is in fact exactly what you implemented in your `fullyQualifiedPackageSlices` version. I.e. "capture arbitrary many package names (the full package name) as identifier". This will then check for cycles between any package in your code base, no matter on which level the package is.
But if what you really want to check is no cycles between the top-level packages beneath `sample` (in your example project), you could also use the pattern `..sample.(*)..`. This pretty much means "identify the slice of classes by the first package beneath sample", i.e. you provide an anchor and by that it does not match any local package name no matter how deeply nested.

Does that help you?

**Comment by jzheaux** [comment]
Yes, that's perfect. Thank you for the explanation. At this point, I'm not sure where I came up with `..(*)..`, but I've changed things to `(**)`, and it's working now how I'd like it to.
