### ISSUE TITLE
`instanceof` calls are not recogniced as dependencies

### ISSUE THREAD

**Issue by t-h-e** [TNG/ArchUnit#371]
If a class contains an `instanceof X` call, then `X` is not part of the dependencies of that class.

Following example class:
```java
public class DependsOnMyExceptionInstanceOf {

    private void bla(Exception e) {
        if (e instanceof MyException) {
            System.out.println(e);
        }
    }
}
```

with the following arch test fails:
```java
@ArchTest
static final ArchRule dependsOnMyExceptionInstanceOf = theClass(DependsOnMyExceptionInstanceOf.class)
    .should()
    .dependOnClassesThat()
    .areAssignableTo(MyException.class);
```

I checked the ArchUnit code and noticed that `MethodProcessor` does not override `visitTypeInsn` which recognises `instanceof` calls.

If I naively add the following code, `instanceof`
```java
@Override
public void visitTypeInsn(int opcode, String type) {
    if (opcode == Opcodes.INSTANCEOF) {
        accessHandler.handleMethodInstruction(type, CONSTRUCTOR_NAME, "()V");
    }
}
```

As I'm new to the codebase of ArchUnit this might not be the best solution 😅 
Any suggestions how to address this issue?

**Comment by codecholeric** [comment]
Yeah, I'm afraid you're right about ArchUnit not detecting this yet. From what I see, any `JavaCodeUnit` can check for `instanceof`, so I would guess to fit this in the existing design it could be something like

* instead of using `accessHandler`, simply add `JavaCodeUnitBuilder.instanceofChecks` (similar to `throwsDeclarations`)
* in the place you found add `codeUnitBuilder.withInstanceofCheck(JavaTypeImporter.createFromAsmObjectTypeName(type)`
* add something like a `JavaCodeUnit.instanceofChecks: Set<InstanceofCheck>` where `class InstanceofCheck{ JavaClass origin; JavaClass target }`
* in the constructor of `JavaCodeUnit` assign `codeUnitBuilder.getInstanceofChecks()` (which internally can use the meanwhile resolved `importedClasses` to resolve those types within the `instanceofChecks` that you have registered earlier)
* add `codeUnit.instanceofChecks` to the set returned by `codeUnit.getDirectDependencies{from/to}self()` through sth. like `Dependency.tryCreateFromInstanceofCheck(instanceofCheck)`

At least that's what comes to my mind without further research :thinking: 
If you want to give it a shot with a PR, I'm happy to support you with any questions :smiley:

**Comment by t-h-e** [comment]
I will give it a shot.
Don't expect it too soon 😅
