### ISSUE TITLE
Is it possible to Check for Class length and/or complexity?

### ISSUE THREAD

**Issue by phermsdorf** [TNG/ArchUnit#374]
Hi,

is there a way to check for class length? 
We have some "god-classes" which I would like to force not getting any longer, but wasn't able to create a check for that.

I know the checks are working on bytecode level, but I don't know enough about that to know if such a check is possible. 

If not, maybe a "workaround" would be to count methods per class and instructions in a method or all method's in a class?

Thanks for any hints on this!

Bye Peter

**Comment by codecholeric** [comment]
Yes, an exact check is not possible, because something like a curly brace closed in line 2099 is just not present in the bytecode (for that you need a tool based on source code). However you can create something like a crude approximation, because "executable code" has it's line number recorded (i.e. statements, not declarations). It might be good enough for your case to do something like

```
classes().should(haveLessLineNumbersThan(100))

// ...

private ArchCondition<JavaClass> haveLessLineNumbersThan(int number) {
  return new ArchCondition<JavaClass>("have less line numbers than " + number) {
    @Override
    public void check(JavaClass javaClass, ConditionEvents events) {
      int lastLineNumber = javaClass.getCodeUnits().stream()
        .flatMap(c -> c.getAccessesFromSelf().stream())
        .map(JavaAccess::getLineNumber)
        .mapToInt(n -> n)
        .max()
        .orElse(0);
      boolean satisfied = lastLineNumber < number;
      events.add(new SimpleConditionEvent(javaClass, satisfied, javaClass.getName() + " has more than " + lastLineNumber + " lines"));
    }
  };
}
```

Caveat: It is only an approximation, i.e. `lastLineNumber` is the line number of the last statement. Also I did not treat nested classes any different, so a nested class running through line 500 will count as a class with more than 500 lines :wink: (that could be mitigated with a little more effort, but I don't know if it's worth it)

You could combine this with https://www.archunit.org/userguide/html/000_Index.html#_freezing_arch_rules to freeze the current state of your God classes and make sure the direction is only downwards, until you reach the number that you want to reach (e.g. specify 200 lines, freeze all violations, from then on any change will only be allowed to reduce the number of lines in classes that violate the length rule).

Other than that you can also count methods, etc., but I think this is closer to what you wanted, isn't it?

**Comment by phermsdorf** [comment]
That's exactly what I was looking for!
Great idea to freeze the current state to enforce the classes don't get any longer.

Thank you very much!

**Comment by codecholeric** [comment]
Glad I could help :smiley:
