### ISSUE TITLE
JUnit 5 @Disabled annotation has no effect

### ISSUE THREAD

**Issue by hwellmann** [TNG/ArchUnit#380]
With JUnit 5, ArchUnit should not run tests annotated with `@Disabled`.

**Comment by codecholeric** [comment]
`@Disabled` is part of the JUnit 5 Jupiter API. Since ArchUnit only uses the JUnit Platform (and provides its own `TestEngine` to run fields as tests, something the Jupiter engine does not support), there is no dependency to Jupiter API classes (it also does not know `@Test` or `@Tag` from the Jupiter API).
Instead ArchUnit offers its own API, namely `@ArchIgnore` which has the same effect as `@Disabled` for JUnit Jupiter tests.
Does that help you?

**Comment by hwellmann** [comment]
Yes, thanks! I had noticed `@ArchTag` but not `@ArchIgnore`.

I had searched the ArchUnit User Guide for `disabled` and could not find anything useful. `@ArchIgnore` **is** documented, but not easy to find when looking for a different keyword, so it might do no harm to add a remark on `@Disabled` for the benefit of JUnit 5 users.

**Comment by codecholeric** [comment]
Yes, you're right, thanks to @rweisleder the respective change will be there soon :smiley:
