### ISSUE TITLE
Support for Eclipse to Exclude Test Classes

### ISSUE THREAD

**Issue by muraty999** [TNG/ArchUnit#396]
My test generated by JHIPSTER using "archunit" fails:

class ArchTest {

    @Test
    void servicesAndRepositoriesShouldNotDependOnWebLayer() {

        JavaClasses importedClasses = new ClassFileImporter()
            .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
            .importPackages("com.cloudnesil.delivery.order");

        noClasses()
            .that()
                .resideInAnyPackage("com.cloudnesil.delivery.order.service..")
            .or()
                .resideInAnyPackage("com.cloudnesil.delivery.order.repository..")
            .should().dependOnClassesThat()
                .resideInAnyPackage("..com.cloudnesil.delivery.order.web..")
        .because("Services and repositories should not depend on web layer")
        .check(importedClasses);
    }
}

This is because in "public interface ImportOption", "final class DoNotIncludeTests implements ImportOption"  does not take into account the eclipse ide binary output folder. I suggest this for DoNotIncludeTests class as:

....
+private static final Pattern ECLIPSE_PATTERN = Pattern.compile(".*/bin/default/([^/]+/)?test/.*");

-private static final Set<Pattern> EXCLUDED_PATTERN = ImmutableSet.of(MAVEN_PATTERN, GRADLE_PATTERN, INTELLIJ_PATTERN);
+private static final Set<Pattern> EXCLUDED_PATTERN = ImmutableSet.of(MAVEN_PATTERN, GRADLE_PATTERN, INTELLIJ_PATTERN, ECLIPSE_PATTERN);

**Comment by hankem** [comment]
Thanks for reporting!

Just FYI: You can already define and use a custom `ImportOption`, cf. https://github.com/TNG/ArchUnit/pull/379#issuecomment-644406139.

**Comment by codecholeric** [comment]
Yes, I always was aware that this is untested in Eclipse and probably does not work. But since for the last 3 years nobody created an issue, I thought Eclipse might just use the Maven layout in most cases or something like that.
But yes, I think we should support Eclipse out of the box, we should just check if different versions of Eclipse use different compile layouts. Unfortunately I have not much experience there, since I don't use Eclipse. But I'd be happy about every Eclipse user dropping a quick comment what version they are using and where Eclipse by default compiles test classes to.
If there are no comments I would go for the pattern `**/bin/**/test/**`, what do you think @muraty999 ? Or is this too rough? But I can't imagine many cases where there is production code in some folder `**/bin/**/test/**` :thinking: I just think I saw Eclipse output folders in the past where the compiled files have not been dumped into a subfolder `/default/`, but I might be wrong...

**Comment by codecholeric** [comment]
@muraty999 can I ask you, what sort of project you have created? Maven? Gradle? Because I just checked Eclipse with a Maven project and it seems to simply reuse `target/test-classes/` like Maven would. I think it must in many cases use the convention of the build tool, otherwise there would have been an issue way earlier, I think :thinking:

**Comment by muraty999** [comment]
Hi @codecholeric, thanks for replies. I use Spring Tool Suite 3, Version: 3.9.12.RELEASE based on Eclipse 2020-03 (4.15.0). We use gradle in our project, when I run as a gradle test task it succeeds (as you mentioned but with maven, differs when in gradle). I run tests using eclipse for some reasons (more control, one test at a time, debugging, JUnit configuration, my coverage tool works in that way). 

Default output folder is as (underlined with blue):  
![output_folder](https://user-images.githubusercontent.com/24798420/87586811-cc91ac80-c6e9-11ea-8a87-77fd856ead8d.png)

However what I noticed today is JUnit run configuration also uses this path, there is not a 'test' folder. So neither my suggestion (`"./bin/default/([^/]+/)?test/."`) nor yours (`**/bin/**/test/**`) would work in that case. I followed @hankem comment (thank you hankem), in which you suggested another way doing it. As a solution, my code looked like this and runs perfectly for our project:

```
public class ArchTest {
	
	static class DoNotIncludeTestSetsForEclipse implements ImportOption {
	    private static final Pattern ECLIPSE_PATTERN = Pattern.compile("(?si).*\\Qtest\\E.*", Pattern.CASE_INSENSITIVE);

	    @Override
	    public boolean includes(Location location) {
	        return !location.matches(ECLIPSE_PATTERN);
	    }
	}

    @Test
    void servicesAndRepositoriesShouldNotDependOnWebLayer() {
    	
    	DoNotIncludeTestSetsForEclipse importOptionForEclipse = new DoNotIncludeTestSetsForEclipse();

        JavaClasses importedClasses = new ClassFileImporter()
            .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
            .withImportOption(importOptionForEclipse)
            .importPackages("com.cloudnesil.delivery.order");

        noClasses()
            .that()
                .resideInAnyPackage("com.cloudnesil.delivery.order.service..")
            .or()
                .resideInAnyPackage("com.cloudnesil.delivery.order.repository..")
            .should().dependOnClassesThat()
                .resideInAnyPackage("..com.cloudnesil.delivery.order.web..")
        .because("Services and repositories should not depend on web layer")
        .check(importedClasses);
    }
}
```

This solution assumes all test classes' names include the word "test", as you guess.

**Comment by codecholeric** [comment]
Hmm, but then I guess the reason there have been little complaints so far is that Eclipse just uses the Maven convention when in a Maven project, but for a default configuration that does not distinguish between main and test and throws everything together in one folder there is no clean way anyway :thinking: 
Maybe this needs to stay something that users who use a common folder for main and test classes have to figure out individually, using a custom `ImportOption` like you did.

**Comment by muraty999** [comment]
I agree. Thank you very much for helping out. Shall I close the issue?

**Comment by codecholeric** [comment]
I'll just close it, since I don't see any real way to improve anything here. Thanks for reporting though, gave me some more insights how Eclipse behaves :+1: Anyone who notices a real default pattern for Eclipse that's not covered, feel free to reopen this issue or create a new one! I definitely want this to be a smooth experience with Eclipse as well :smiley: (I used it once with Eclipse, but that project was huge and used OSGI, so I had to resort to custom `ImportOptions` and `LocationProvider` anyway :wink:)
