### ISSUE TITLE
How to detect member usage only in Supplier?

### ISSUE THREAD

**Issue by phermsdorf** [TNG/ArchUnit#403]
Hi,

we have Message classes used for localization. These are more or less expensive to initialize. 
Recently I found code that only uses this Message classes for error handling in Optional.orElseThrow cases.
IS it possible to detect that the class member is only used in Suppliers? (there are of course cases where the member is used on multiple places in the class)

Example code:

```
public class MyClass {

	private final Messages messages = MessageUtil.getMessageByService(Messages.class, EclipseUtil.getLocale());

	@Override
	protected Menu createMenu(final ToolBar toolBar) {
            <code not using the messages member>
	}

	@Override
	protected Color getColor() {
		return ServiceSupplier.runWithFunction(IColorMgr.class, getClass(), s -> s.getColor(COLOR_BACKGROUND))
				.orElseThrow(() -> new IllegalStateException(messages.error_service_color_manager)); // only called on error
	}
}
```
Thank's for any hints or ideas!

Peter

**Comment by codecholeric** [comment]
Hmm, I did not find any way to check, if it is only read within a `Supplier`, because the way ArchUnit reads the origin of a field access at the moment. I guess it would be possible (even though a little hacky :wink:) to check if such a field is only be accessed by lambdas (I hope the naming is consistent through the generations of JDKs :wink: )

```
fields().that().haveRawType(Messages.class).should(notOnlyBeReadByLambdas())

----

private ArchCondition<JavaField> notOnlyBeReadByLambdas() {
    return new ArchCondition<JavaField>("not only be read by lambdas") {
        @Override
        public void check(JavaField field, ConditionEvents events) {
            boolean fieldOnlyReadByLambdas = field.getAccessesToSelf().stream()
                    .filter(access -> access.getAccessType() == AccessType.GET)
                    .map(JavaAccess::getOrigin)
                    .allMatch(userOfField -> userOfField.getName().contains("lambda$"));
            if (fieldOnlyReadByLambdas) {
                events.add(SimpleConditionEvent.violated(field,
                        String.format("Field %s is only read by lambdas in %s",
                                field.getFullName(), field.getSourceCodeLocation())));
            }
        }
    };
}
```

Maybe you can refine this, so it is good enough for your requirements? 
I wonder if it would be possible to let ArchUnit read a couple of more details from the bytecode :thinking: Because `invokeDynamic` is not specifically handled (resulting in just a `JavaMethod` with a somewhat weird name)

**Comment by phermsdorf** [comment]
I've tested this with some of my examples and it works pretty good.

I'm always impressed how you manage to build this crazy expressions for this corner cases :smiley:

Thank's again for your help!

Bye Peter
