### ISSUE TITLE
Freezing rule violations as SonarQube metric

### ISSUE THREAD

**Issue by stefanroeck** [TNG/ArchUnit#425]
[Freezing rules](https://www.archunit.org/userguide/html/000_Index.html#_freezing_arch_rules) are helpful to deal will legacy code bases. The default storage implementation maintains a text file as part of the code base including all "frozen" violations. To measure code quality improvements over time, it would be cool to be able to expose these information as SonarQube metrics. This would not only allow to browse violations inside of SonarQube directly but also report the violations as KPI and track progress over time.

Looking into this, a couple of things need to be done:
- Provide an alternative storage mechanism which manages violations in a more machine friendly format. Also all available meta information need to be exposed in a structured way, like source code location (if applicable). Format could be json or xml. The ViolationStore API needs to be extended for this, as today, violations are treated as `List<String>`.
- Write a SonarQube plugin for the Java code analyzer that parses these information and generates metrics/measurements at the Sonar API. There are plug-ins which do something similar, e.g. https://github.com/sonargraph/sonar-sonargraph-integration

Any thoughts on feasibility or usefulness? Comments welcome :-)

**Comment by hankem** [comment]
`FreezingArchRule` already provides [extension points](https://www.archunit.org/userguide/html/000_Index.html#_extension); you can in particular specify a custom [`ViolationStore`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/library/freeze/ViolationStore.html).
It should definitely be possible to implement this interface to use a machine friendly json/xml file.

**Comment by stefanroeck** [comment]
@hankem thanks or response. ViolationStore API treats all violations as Strings:
`void save(ArchRule rule, List<String> violations)`
instead, something like this would be more versatile
`void save(ArchRule rule, EvaluationResult result)`
With that in place, a JsonViolationStore could use experimental API `EvaluationResult#handleViolations(ViolationHandler<?> violationHandler)` to get access to all different violation types, e.g. `com.tngtech.archunit.core.domain.Dependency` and extract relevant information for persistence, like offending classes, source code location, etc.
Downside is that this needs to be done for every domain object that potentially is stored inside of a ConditionEvent. 
Persistence would then look like this
```
{
  "rule": "no classes should depend on classes that reside in a package 'com.google.common..'",
  "violatingObjects": [
    {
      "type": "depdendency",
      "message": "Method <com.acme.CustomerOrganization.setCustomerPlants(java.util.List)> calls method <com.google.common.collect.ImmutableList.of(java.lang.Object)> in (CustomerOrganization.java:21)",
      "originClass": "com.acme.CustomerOrganization",
      "targetClass": "com.google.common.collect.ImmutableList",
      "sourceCodeLocation": "(CustomerOrganization.java:21)"
    }
  ]
}
```

**Comment by aaschmid** [comment]
@hankem @codecholeric we are wondering if the above approach is the right one. We would like to create a pull request and don't want to run in the wrong direction... 

If you could scretch out what or how you want it, this wold guide us into the right direction. Thanks.

**Comment by hankem** [comment]
I must admit that I didn't get the point yet why `List<String> violations` isn't good enough for your SonarQube metrics. (For the frozen rules I'm using in my own project, I – so far manually – watch the `TextFileBasedViolationStore`'s files to shrink over time, so I thought it was basically all about exposing this line count to SonarQube... 😉 But you apparently want to do more than that.)

Could you maybe explain again why you want to be able to deserialize the full `EvaluationResult` and not only its failure report's details (the `List<String> violations`)? Is that only, as you said in https://github.com/TNG/ArchUnit/issues/425#issue-707267457,
> to browse violations inside of SonarQube directly

?

The issue I see is that the [`ConditionEvent`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/ConditionEvent.html) interface doesn't impose constaints other than that it must provide its description lines as a `List<String>` – and that _"the corresponding objects"_ (a `Collection<?>`) can be supplied to a [`Handler`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/ConditionEvent.Handler.html). It is totally unconstrained what a rule's _"corresponding objects"_ are, so in order to do something, as you said in https://github.com/TNG/ArchUnit/issues/425#issuecomment-701909101,

> for every domain object that potentially is stored inside of a `ConditionEvent`

, it seems that you'd have to introduce a restriction, i.e. a breaking change.

**Comment by codecholeric** [comment]
The assumption about `ConditionEvent` being totally unrestricted is unfortunately correct. There also simply is not always a (single) source file that comprises a violation.
Take a cycle violation for example -> no class by itself is violating this rule. But a number of classes together do. So which is now "the location" of the violation? In the end it could only be multiple lines in multiple files that together create the violation. That is also why the `ViolationHandler.handle(..)` method takes a collection of `violatingObjects`.

On the upside it would maybe be possible to handle a specific subset good enough for many cases. One could e.g. do sth. like

```
result.handleViolations(new ViolationHandler<Object>() {
    @Override
    public void handle(Collection<Object> violatingObjects, String message) {
        if (violatingObjects.size() != 1) {
            return;
        }

        Object violatingObject = violatingObjects.get(0);
        if (violatingObject instanceof HasSourceCodeLocation) {
            ((HasSourceCodeLocation) violatingObject).getSourceCodeLocation() // ... do something with the location
        }
        if (violatingObject instanceof HasName.AndFullName) {
           ((HasName.AndFullName) violatingObject).getFullName() // ... do something with the name
        }
    }
});
```

**Comment by stefanroeck** [comment]
Based on the given advice, we came up with a custom ViolationStore implementation that:
- stores violations of multiple rules in a single XML file for better processing and readability
- uses stable ids for each ArchRule
- helds additional metadata per ArchRule like category

I'm not sure if that's something for the standard library but in case somebody is interested, here are the most relevant classes: https://gist.github.com/stefanroeck/0e7b2002eb0e801b8ff619e6738048db

As this fulfills our needs for now, I'm closing this ticket.
