### ISSUE TITLE
Option for clearing classes cache after all ArchTests in a test class have run

### ISSUE THREAD

**Issue by thmuch** [TNG/ArchUnit#44]
We're running some ArchTests using the performance optimized version with the AnalyzeClasses annotation:
```
@RunWith(ArchUnitRunner.class)
@AnalyzeClasses(packages = "de.whatever")
public class ArchUnitTest {
   @ArchTest
   public static final ArchRule SOME_RULE = ...;
}
```
It seems the JavaClasses cache is not freed after running the tests in this class. (We're running into memory problems in the unit tests that are executed after ArchUnit. For performance reasons our tests use the same JVM instance.)

Is there an option for clearing the cache after all ArchTests in a test class have run?

**Comment by thmuch** [comment]
Or maybe this is not intended behaviour and the "classes" field in ArchUnitRunner.SharedCache should not be static?

**Comment by codecholeric** [comment]
I'm afraid this works as intended, because originally I thought, it would be a neat feature to import every set of locations only once, between different test instances. I.e. the cache also works by location, if you import the same set of URLs, it should reuse the imported classes.
One thing you could check is, if your tests always import different sets of classes, where they could in fact import the same classes. What I mean, if you have `ATest` with `@AnalyzeClasses(packages = "
my.app.foo")` and `BTest` with `@AnalyzeClasses(packages = "my.app.bar")`, ArchUnit will see, that these are different URLs to import, and do two imports. If both `ATest` and `BTest` would declare `@AnalyzeClasses(packages = "my.app")`, the package should (within the same classpath) be resolved to the same set of URLs leading to only one import. So maybe by doing a slightly bigger import, suitable for your whole suite, you might in fact safe performance, with respect to both memory and runtime. Of course this only holds, if you have many test classes with only slightly different URL sets.

If you have only one test with a massive set of classes, and this set is just draining your memory, then you're out of luck with the official support at the moment, sorry!! I'll release a new version of ArchUnit in the close future, and I've created #45  to solve your issue (feel free to comment, if you think I miss something)

In the mean time, you could try to use the following quick and dirty workaround:

```
public class CleanCacheWorkaround {
    public void cleanCache() {
        try {
            Class<?> clazz = Class.forName(ArchUnitRunner.class.getName() + "$SharedCache");
            Field cacheField = getAccessibleField(clazz, "cache");
            Object cache = cacheField.get(null);
            clearCacheField(cache, "cachedByTest");
            clearCacheField(cache, "cachedByLocations");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private void clearCacheField(Object cache, String fieldName) throws NoSuchFieldException, IllegalAccessException {
        Field mapField = getAccessibleField(cache.getClass(), fieldName);
        Map<?, ?> map = (Map<?, ?>) mapField.get(cache);
        map.clear();
    }

    private Field getAccessibleField(Class<?> clazz, String cache) throws NoSuchFieldException {
        Field cacheField = clazz.getDeclaredField(cache);
        cacheField.setAccessible(true);
        return cacheField;
    }
}
```
and in your test
```
@AfterClass
public static void cleanCache() {
    new CleanCacheWorkaround().cleanCache();
}
```

I did a quick debugging check, and it seems to work, but let me know if there should be a problem.

**Comment by thmuch** [comment]
We're testing a monolithic application, so there are quite a few classes... And so far we've got only one ArchUnit test class (i.e. one @AnalyzeClasses) with several tests.

Anyway, #45 looks like the configuration option I was looking for :-)

No need to hurry though, you're workaround for clearing the cache works like charm.

Thanks!
