### ISSUE TITLE
Only access specific class in package

### ISSUE THREAD

**Issue by sblumenstock-doubleSlash** [TNG/ArchUnit#443]
Hey, 
how can I make sure, that classes outside of my service package can ONLY access the Service java class inside this package? 

- package
- service
   - service A
      - ...Service.java

So now I want that classes in package should only access serviceA with the Service Java Class inside.
Thank you!

**Comment by sblumenstock-doubleSlash** [comment]
Is there noway to achieve this?

**Comment by codecholeric** [comment]
Yeah, that should be possible :smiley: Try something like

```
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.resideInAPackage;
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.resideOutsideOfPackage;

// ...

classes().that().resideOutsideOfPackage("..service..").should().onlyDependOnClassesThat(
      resideOutsideOfPackage("..service..").or(resideInAPackage("..service.serviceA.."))
)
```

Instead of `resideInAPackage("..service.serviceA..")` you could also use something like `belongToAnyOf(MyConcreteService.class)` to only allow access to one specific class in the package (I could not tell exactly tell from your question if that is what you want or access to a sub-package...).
Does that help you?

**Comment by sblumenstock-doubleSlash** [comment]
Yeah that helped me a lot!
Is it possible to exchange `resideInAPackage("..service.serviceA..")` with `simpleNameEndingWith()`?

**Comment by codecholeric** [comment]
Yes, sure, any `DescribedPredicate` can be used (also a custom one, if needed)
