### ISSUE TITLE
Violations not detected by ArchUnit

### ISSUE THREAD

**Issue by enriquemolinari** [TNG/ArchUnit#446]
Trying to understand why ArchUnit does not detect the cases below... 
(1) I guess this one is because the compiler remove that unused variable at all and nothing is translated to bycode. 
(3) Casting is just for the compiler nothing goes into bytecode.
(2) Why is not detected? can this be fixed?

Thanks!!!

```
package app.ui;
import app.business.AServiceImpl;

public class View {
 public void aMethod( ) {
  AServiceImpl a; // (1)
  Class a2 = AServiceImpl.class; // (2)
  System.out.println(a2.getName());
  if (AServiceImpl.class.equals(this.getClass())) { // (2)
   ....
  }
  Object o = new Object();
  AServiceImpl b = (AServiceImpl)o; // (3)
 }
}
	
 @Test
 public void arch() {
  JavaClasses jc = new ClassFileImporter().importPackages("app");
  noClasses().that()
   .resideInAnyPackage("app.ui..")
   .should()
   .accessClassesThat()
   .resideInAPackage("app.business")
   .check(jc);
 }
```

**Comment by codecholeric** [comment]
ArchUnit does currently not handle all the information the bytecode would offer, e.g. the constant pool (compare #131).
Local variables without use like (1) are not detected at the moment. If you call a method or access a field on this concrete local variable, it will be detected.
Generic properties of `Class<?>` are currently also not detected, the only way to find this in the bytecode would again be the constant pool. Because all the accesses / dependencies are to generic `Class<?>` in the bytecode.
Casts like (3) could be detected (they are related closely to e.g. #417) but it hasn't been implemented yet :disappointed: 
Does that answer your questions?

**Comment by enriquemolinari** [comment]
Many thanks for your reply. ArchUnit is an excellent tool, hope can be improved further.

**Comment by codecholeric** [comment]
I'm gonna close this for now, since it's a little undirected. (2) has been implemented meanwhile, about (1) I'm not sure, because the compiler might also remove it if it's unused and and unused local variable will also never cause a real maintenance problem. For (3) I have created #710
