### ISSUE TITLE
General rule to test that class and its test are both at the same package

### ISSUE THREAD

**Issue by ars-java** [TNG/ArchUnit#475]
It will be convenient to have `GeneralCodingRules.TEST_SHOULD_HAVE_SAME_PACKAGE` rule to test that classes `Xxx` from `/src/` and `XxxTest` from `/test/` are both at the same package

**Comment by hankem** [comment]
You can define a custom `@ArchTest` like in https://github.com/TNG/ArchUnit/issues/20#issuecomment-328225761.

**Comment by ars-java** [comment]
Yes, I can. But I think that it's a useful common and reusable feature to add it to the library. It's more fundamental then restrictions for joda-time or JUL

**Comment by codecholeric** [comment]
I agree, even though I wonder if the naming pattern should be customizable :thinking: 
Like `GeneralCodingRules.testsShouldResideInTheSamePackageIdentifyingTestsByName("$Test")`), and someone else could write `...IdentifyingTestsByName("$IntegrationTest")` or `...IdentifyingTestsByName("$Tests")` for example.
Anyway, if you have time I would be happy to support you with a PR for this feature :wink: Or if anybody else wants to contribute. I think it would be a good starter task :smiley: Otherwise I have to put it in my pipeline and implement it when I get to it, but looking at my task pipeline that could take a while :disappointed:

**Comment by Rossalli** [comment]
Hi, @codecholeric! Could you please assign this to me? I would like to try help with this issue :)

Thanks!

**Comment by mslowiak** [comment]
@Rossalli are you still working on that one? can I pick this up?

**Comment by Rossalli** [comment]
Hi @mslowiak, I'm working on that :)

**Comment by thatsIch** [comment]
@Rossalli how is your progress?

**Comment by codecholeric** [comment]
Since the last comment from @Rossalli is from almost a year ago and there has been no reply to the last ping for over a month I would consider this issue open for grabs again...

**Comment by mslowiak** [comment]
@codecholeric So, can I pick this up? :)

**Comment by codecholeric** [comment]
Yes, feel free to pick it up! (Sorry if you're really still working on it @Rossalli, but without any life sign for so long I can't block the issue forever)

**Comment by codecholeric** [comment]
@mslowiak I assigned you to it for transparency, hope that's okay :wink:
