### ISSUE TITLE
Issue a warning if we check an annotation with RetentionPolicy.SOURCE

### ISSUE THREAD

**Issue by thmuch** [TNG/ArchUnit#48]
When executing an ArchRule like `noClasses().should().beAnnotatedWith(SuppressWarnings.class)`ArchUnit reports no violations, even if there are SuppressWarnings annotations on some of the classes.

The reason is that SuppressWarnings has RetentionPolicy.SOURCE, i.e. ArchUnit cannot query these annotations.

Would it be possible for ArchUnit to issue some warning (or better: fail the test?) if we're checking a SOURCE annotation?

**Comment by codecholeric** [comment]
I guess this warning would make sense, since you're not the first one falling into that pit :wink: 
Originally I thought, that I can't validate anything for `beAnnotatedWith(string)` or `beAnnotatedWith(predicate)`, so I won't validate the class case either, but I guess that's no good reason to make it worse, just cause some other part is bad.
It's probably best to just throw an exception, if an impossible argument is used, same with `implement(concreteClass)`, where I skipped such a check with the same reasoning.
