### ISSUE TITLE
How to detect cycles between classes in the same package?

### ISSUE THREAD

**Issue by MLThal** [TNG/ArchUnit#483]
I have two classes in the same package. Both depend on each other, so there are cyclic dependencies:

```
import mypackage.MyClass2;

public class MyClass1{
  private MyClass2 class2;

  public MyClass1() {
    class2= new MyClass2();
  }

  public void call() {
    class2.call();
  }
}
```
and
```
import mypackage.MyClass1;

public class MyClass2{
  private MyClass1 class1;

  public MyClass2() {
    class1= new MyClass1();
  }

  public void call() {
    class1.call();
  }
}
```
However, this test does not fail:

```
@ArchTest
  public static final ArchRule check_freeofcycles =
      slices().matching("..mypackage.(*)..").should().beFreeOfCycles();
```

It only fails, if they are in different subpackages, e.g.
* mypackage.Class1 and mypackage.slice.Class2
* mypackage.slice1.Class1 and mypackage.slice2.Class2

How can I test for cyclic dependencies in the same package?

**Comment by codecholeric** [comment]
This is not one of the standard use cases of ArchUnit, because a) there are frameworks that heavily propagate cyclic dependencies between classes (like Hibernate) and b) the graph will grow quite complex if each class forms a node by itself. That said IMHO cycles are always hard for the brain to comprehend, so if your constraints allow it and you want to prevent cycles between any two classes you could try something like

```
@ArchTest
public static final ArchRule classes_should_not_have_cyclic_dependencies =
    slices().assignedFrom(className())
        .namingSlices("Class [$1]")
        .should().beFreeOfCycles();

private static SliceAssignment className() {
    return new SliceAssignment() {
        @Override
        public String getDescription() {
            return "class name";
        }

        @Override
        public SliceIdentifier getIdentifierOf(JavaClass javaClass) {
            return SliceIdentifier.of(javaClass.getName());
        }
    };
}
```

Using `assignedFrom(SliceAssignment)` you can customize very freely, which classes should form a "slice". The above will sort each `JavaClass` in its own slice with the same name as the `JavaClass` (thus no two classes end up in the same, because the fully qualified class name is the slice identifier). I have no idea how the performance will be, if you have a big number of classes (like x * 10e5). But we did improve the performance of the algorithm meanwhile and added some upper limit to the number of cycles found, so it might work (I would be happy if you let me know, if/how well it performs on which number of classes).
Does that help you?

**Comment by MLThal** [comment]
Thank you for you reply. This helps. If I understood this correctly, this checks for dependencies over all classes, correct? Is it possible to apply this only on specific packages (and their subpackages)? I cannot see a way to combine `matching()` and `assignedFrom()` to shrink the scope. 

Futhermore: Is there a way to return the real class name instead of "class name" in the `getDescription()` method? Maybe using the SliceIdentifier?

Thanks in advance for your help!

**Comment by codecholeric** [comment]
Yes, this checks over all classes, you can return `SliceIdentifier.ignore()` for all classes you're not interested in though. So you could check 

```
if (!javaClass.getName().contains(".interesting_package.")) {
    return SliceIdentifier.ignore();
}
```

Or you could of course only import the classes of the relevant package in the first place.

As for your second question, I'm not sure I understand. The description "class name" is only for the rule description, i.e. to form the rule text "slices assigned from class name...". I don't think it makes sense to return a specific class name here?

For the text description of the single "slices" in the violation you can refer to the parts of the `SliceIdentifier` in `namingSlices(..)`. That's what I did when I wrote `namingSlices("Class [$1]")`. That means "take the first element of the respective slice identifier (i.e. the class name) and put it into the template, e.g. `Class [com.foo.Bar]`". This will then result in `Class [com.foo.Bar] -> Class [com.baz.Quux] -> Class [com.foo.Bar]`. If you only write `namingSlices("$1")` you would get `com.foo.Bar -> com.baz.Quux -> com.foo.Bar`.

**Comment by MLThal** [comment]
Thanks, I will try it :)
