### ISSUE TITLE
getCallsFromSelf in inherited class does return call to parent class

### ISSUE THREAD

**Issue by uhafner** [TNG/ArchUnit#496]
When I do have the following class setup:

```
class A {
   void method a() {
      doSomething();
   }
}

class B extends A {

}
```

then I get for an `ArchCondition<JavaMethod>` that analyzes the methods of `B` (in our case method `B.a()`) via the statement 
`Set<JavaCall<?>> callsFromSelf = method.getCallsFromSelf();` only the call `A.a()`. What I would expect is that I get the actual method `doSomething()` since the method is not overwritten in `B`. It seems that the virtual call to the base class method is actually done via a concrete call to the method in `super`.

(Full example at https://github.com/jenkinsci/plugin-util-api-plugin/blob/master/src/test/java/io/jenkins/plugins/util/PluginArchitectureRules.java#L138)

Is there a simple way to check the actual implementation of `A.a()`? Or the other way around: is it possible to skip methods in child classes that are not overwritten in `methods().that().areDeclaredInClassesThat()`.

**Comment by codecholeric** [comment]
I'm not completely sure I understand everything. I can say that from ArchUnit's point of view `B.getMethods()` should not return `method_a`, since `method_a` has not been overridden. Also `B.getCallsFromSelf()` should not include the call `method_a() -> doSomething()`, but only `A.getCallsFromSelf()` should.

If you have `B extends A` and you check

```
methods().that().areDeclaredInClassesThat().areAssignableTo(A.class)
```

then you will match the method `A.method_a()`, because you check all methods in the hierarchy downwards from `A` on. Is your problem, that you want to only check methods in proper subclasses of `A` in this example?

Can you maybe give a concrete example for your case, what you would expect and what happens instead? Because I'm not completely sure I understand the problem (to me it sounds like you have some call `B -> A.method_a()`? That would be surprising to me in the simple example above, where `method_a()` has not been overridden, and there is no explicit call `B -> A` anywhere :thinking:)

**Comment by uhafner** [comment]
Ok, after digging a little bit deeper into the class files I found out that the problematic method is generated in the byte code by `javac`. If a base class is marked as package private then not overwritten methods from the base class will be copied to the sub class (while the copied method simply invokes the base class method). So this is nothing that ArchUnit can handle.

Setup 1:

```
abstract class A {
    public void method() {

    }
}
public class B extends A {

}
```

Output of javap:

```
Compiled from "B.java"
public class io.jenkins.plugins.analysis.warnings.B extends io.jenkins.plugins.analysis.warnings.A {
  public io.jenkins.plugins.analysis.warnings.B();
  public void method();
}
```

Setup 2:

```
public abstract class A {
    public void method() {

    }
}
public class B extends A {

}
```

Output of javap:

```
Compiled from "B.java"
public class io.jenkins.plugins.analysis.warnings.B extends io.jenkins.plugins.analysis.warnings.A {
  public io.jenkins.plugins.analysis.warnings.B();
}
```

**Comment by codecholeric** [comment]
Ah, I see :smile: I have also stumbled over these cases. One thing that comes to my mind that could try in your condition is to add 

```
if (method.getModifiers().contains(JavaModifier.SYNTHETIC)) {
    return;
}
```

I would hope that the method the compiler generates to "fix" this visibility issue would be flagged as synthetic...

**Comment by uhafner** [comment]
Yes, that helps! Now I can simply ignore these methods.
