### ISSUE TITLE
JUnit 5: Migrate to Extension Model

### ISSUE THREAD

**Issue by ebramirez** [TNG/ArchUnit#504]
Hi everyone,

Currently ArchUnit JUnit 5 extension [plugs it's own Test Engine](https://junit.org/junit5/docs/current/user-guide/#launcher-api-engines-custom), but this has the disadvantage that `@ArchTest` annotation discovery in tests always runs even when the test in the test suit or package are not annotated with it.

Switching the implementation to the [Declarative Extension Model](https://junit.org/junit5/docs/current/user-guide/#extensions) would make sure that the ArchUnit test discovery only runs when there are actually test annotated with the `@ArchTest` annotation.

You can find an example if this in [TestContainer](https://www.testcontainers.org/)'s implementation of [JUnit 5](https://github.com/testcontainers/testcontainers-java/tree/master/modules/junit-jupiter) extension.

**Comment by codecholeric** [comment]
I looked into the extension model back then and could not find a way to satisfy ArchUnit's requirements with this API. Could you elaborate how you would suggest to write an equivalent thing to the current `TestEngine` using this API?
My problem back then was, that ArchUnit wants to treat fields as tests, which goes against the whole model of the Jupiter API. I felt ArchUnit's requirements are more similar to requirements that frameworks like Cucumber have, which also provides a custom test engine (-> https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine).
But if you have an idea how to reach the same behavior with the JUnit 5 extension model, I'm all ears :smiley: Because that would reduce the amount of code to maintain a lot!

Other than that I'm not sure where your pain points at the moment are, do you think the test discovery of the ArchUnit `TestEngine` adds too much overhead? Maybe you could try something like conditionally excluding the engine in certain environments?

**Comment by codecholeric** [comment]
I'm gonna close this for now, due to inactivity. Feel free to reopen, if you want to discuss / elaborate further!

**Comment by ebramirez** [comment]
Sorry for not replying earlier. It is ok to close it if there is no alternative way.

I should have done more research. I came to this conclusion when I was analyzing some flamegraphs of some test runs and I saw the ArchUnit classes coming up even on tests that where not related to them. But is a very minor issue.

Thanks for taking the time in giving a detailed answer.

**Comment by codecholeric** [comment]
No problem, I always appreciate ideas to simplify things, no matter if it turns out feasible or not :smiley: :+1:
