### ISSUE TITLE
Frozen rules not updated when new violation occurs

### ISSUE THREAD

**Issue by gopf** [TNG/ArchUnit#510]
We have frozen our architecture violations and therefore get feedback when we get new violations.

Sometimes we can't immediately fix the new violation, though, so we want to update the frozen state. Setting `freeze.store.default.allowStoreUpdate=true` doesn't work, though. Only deleting the stored.rules entry and the corresponding violation file works, but then we get a new violation file and lose the history.

Shouldn't `freeze.store.default.allowStoreUpdate=true` allow the update of existing rule violations?

**Comment by codecholeric** [comment]
ArchUnit assumes, that you never want to allow **new** violations :wink: 
The configuration `freeze.store.default.allowStoreUpdate=true` is the default, but only allows ArchUnit to automatically reduce the violation store if violations are fixed (i.e. you never have to delete resolved violations from the violation store yourself, it happens automatically when they are solved, so they can't be reintroduced 2 weeks later). 
There is no support to allow new violations to occur, because the whole premise of `FreezingArchRule` is "okay, we have a bad state right now, but from now on we only want to get better". Producing new violations and being okay with it is intentionally not supported :wink: (of course you can always do this by recreating the whole violations file, or manually patch in the new violations).

If you use Git and you recreate the file, shouldn't it be automatically detected as changed file though, if there is sufficient similarity? (i.e. not like you have 10 violations and want to add 990, but rather you have 990 and want to add 10)
Otherwise you can probably just recreate the violation store somewhere else and copy over the violation difference to keep your history... In IntelliJ e.g. just create the store somewhere else, mark the two matching files in your file tree, start a diff (e.g. CRTL + D) and just take over the new violations.

**Comment by hankem** [comment]
> deleting the stored.rules entry and the corresponding violation file works, but then we get a new violation file and lose the history

If I _were_ in such a situation (I'd never admit that I've used this for something else than renaming ArchRules... 😜), I'd rename the new violation file to the old name and revert the `stored.rules` change; this should give you a commit that only adds new violations to the existing store.

**Comment by gopf** [comment]
IMHO adding new violations is a valid use case.

I am using ArchUnit to guide a tricky refactoring. I'm trying to add new functionality in a pluggable way. Doing it as a true plugin isn't possible yet, for reasons, so I defined a rule that classes outside of a package 'newmodule' shouldn't access classes in a package 'newmodule'. That way all my plugin code is neatly separated, and the rest of the application shouldn't know about the code in the plugin.

There are known violations for which we don't yet have a clean solution, and as I add more functionality this list grows, but I want the tests to fail if I add a dependency inadvertently, and to be able to update the list if there is a new case that I can't solve immediately.

Yes, I can delete the whole store and recreate, or dig around and find the rule that needs to be updated and just delete that one, but it's a bit fiddly, requires some knowledge of the store layout, and it feels like there should be an easy way to let ArchUnit manage the updates. I expected 'update' to deal with this case as well, but maybe you are right that by default update should only allow violations to be reduced. Maybe another option could be used to permit the 'extend violations' case.
