### ISSUE TITLE
mayNotBeAccessedByAnyLayer will ingore self layer checking

### ISSUE THREAD

**Issue by cksiow** [TNG/ArchUnit#517]
Issue:
 mayNotBeAccessedByAnyLayer method will only check others layer but not self layer, is this a bug?

Reproduce Step:
 layeredArchitecture()
                //define layer
                .layer("Controller").definedBy(..controller..)
                .layer("ServiceAPI").definedBy("..service.api..")
                .layer("ServiceImpl").definedBy("..service.impl..")
 .whereLayer("ServiceImpl").mayNotBeAccessedByAnyLayer();

When service implementation class is called by controller layer's class, it work, but when service implementation class calling another service implementation class, it will not show the error

Expected:

Even service implementation class calling another service implementation class should show the error since service implemetation class not allow accessed by any layer.

**Comment by codecholeric** [comment]
This is actually expected behavior. `LayeredArchitecture` only validates dependencies between different layers, not within the same one. One reason is also, that what a "service" is, is not generally defined, but depends on the project convention.
So the only way would be to disallow all dependencies between classes within the same layer, but that is just not feasible, because then even the parameter type of a service method could be a violating dependency.

If you want to assert vertical dependencies you can either look at `SliceRuleDefinition` (the mental model so far is `LayeredArchitecture` defines a "horizontal" layering, `SliceRuleDefinition` defines a "vertical" slicing by domain) or write some additional custom rule to ensure this aspect.

Usually the way to use ArchUnit is to build up a safety net of several different rules for your architecture.

----

BTW: You can see what happens when you disallow accesses within the same layer by using something like

```
classes().that().resideInAPackage("..service..")
    .should().onlyHaveDependentClassesThat().resideInAnyPackage("..controller..")
```

I think you can quickly see then, that such a generic rule doesn't provide value, and any more specific rule depends on the concrete project conventions.

**Comment by codecholeric** [comment]
Closed due to inactivity, feel free to open if you have more questions :slightly_smiling_face:
