### ISSUE TITLE
onlyBeAccessed() with more then one condition?

### ISSUE THREAD

**Issue by Poeschl** [TNG/ArchUnit#54]
Is there a possibility to specify two or more conditions for the onlyBeAccessed() call?

For example:
```java
classes().that().areAnnotatedWith(Service.class)
            .should().onlyBeAccessed().byClassesThat().areAnnotatedWith(Controller.class)
            .orShould().onlyBeAccessed().byClassesThat().areAnnotatedWith(RestController.class);
```

**Comment by codecholeric** [comment]
I've just checked this, and I think it fails, if for example a Service is accessed by both an `@Controller` and an `@RestController`, since then condition 1 is violated for the access from `@RestController` and condition 2 is violated by `@Controller`, so the syntax considers the OR-conjunction as violated.
I think what you want is

```
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.equivalentTo;
import static com.tngtech.archunit.core.domain.properties.HasType.Functions.GET_TYPE;

private static final DescribedPredicate<HasType> CONTROLLER =
    GET_TYPE.is(equivalentTo(Controller.class))
        .or(GET_TYPE.is(equivalentTo(RestController.class)));

classes().that().areAnnotatedWith(Service.class)
    .should().onlyBeAccessed().byClassesThat().areAnnotatedWith(CONTROLLER);
```

Because then it checks the OR-ed predicate on classes accessing `@Service` instead of `@Service` being accessed by either only `@Controller` or only `@RestController`.
Principally, if you run into problems like this, you can always write custom conditions and predicates, e.g.

```
private static final DescribedPredicate<JavaAnnotation> CONTROLLER =
        new DescribedPredicate<JavaAnnotation>("@Controller or @RestController") {

    @Override
    public boolean apply(JavaAnnotation input) {
        return input.getType().isEquivalentTo(Controller.class)
                || input.getType().isEquivalentTo(RestController.class);
    }
};

classes().that().areAnnotatedWith(Service.class)
    .should().onlyBeAccessed().byClassesThat().areAnnotatedWith(CONTROLLER);
```

There are various points, where you can plug in custom logic, e.g.

```
classes().that(myCustomPredicate)
```

or

```
classes().should(myCustomCondition)
```

Does this help you with your problem?

**Comment by Poeschl** [comment]
👍 it does. Thanks for the fast reply
