### ISSUE TITLE
isAnnotatedWith is not work when i run unit test by command line

### ISSUE THREAD

**Issue by GeeJoe** [TNG/ArchUnit#573]
```java
com.tngtech.archunit.core.domain.JavaClass#isAnnotatedWith(java.lang.Class<? extends java.lang.annotation.Annotation>)
```
This method is not work when I run unit test by command line:
```shell
gradle testDebugUnitTest --tests {my_unit_test}
```
But it works well when I run on Android Studio by click the run button
![image](https://user-images.githubusercontent.com/13412420/114687364-4375d780-9d46-11eb-8a99-78831507bf08.png)

here is my code:
```kotlin
   private fun isValidTargetClass(javaClass: JavaClass): Boolean {
        return !javaClass.isAnnotatedWith(IgnoreDenyDependencyToSelf::class.java)
    }
```
```kotlin
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
@MustBeDocumented
annotation class IgnoreDenyDependencyToSelf(val reason: String)
```

**Comment by hankem** [comment]
What do you mean by _"This method is not work"?_ We'll need a few more details: How does your specific unit test look like, and in particular: how do you import classes in ArchUnit? (I can only guess that you get an unexpected failure, or don't get an expected failure. This may depend on the scope of imported classes, which might differ when the test is run from the IDE or via Gradle.)

**Comment by GeeJoe** [comment]
Finally I found out that it's my fault:
In my test case I have am importOption likes this：
```
class KandianImplArchUnitIgnoreTest : ImportOption {
    override fun includes(location: Location): Boolean {
        if (location.isArchive  || location.isJar ) return false // here i ignore jar and archive
 
    }
}
```
When I run the test by clicking Android Studio's run button，the annotation's `isArchive` and `isJar` return false, but both of them return true when I run the test by command line `gradle testDebugUnitTest`

what are `isArchive` and `isJar` actual mean, and why the result are different when run from the IDE or via Gradle ?

**Comment by codecholeric** [comment]
To answer your questions:

* `isJar` means class files come from a JAR file, instead of a file path (e.g. inside of `my-app.jar` instead of just being compiled to some folder `build/classes/main`)
* `isArchive` is a more general version if `isJar`, because with JDK 9 there were other type of archives introduced (namely JRT, where classes of the JDK e.g. come from for JDK >= 9). So `isArchive || isJar` doesn't really make sense here, because if `isArchive is `false`, then `isJar` will always be `false` as well)

To explain your confusion why this behaves differently with Gradle and IntelliJ: Both create the classpath in a different way, so your class files are read from different sort of locations. IntelliJ compiles all the classes to file paths, then puts all these file paths on the classpath (e.g. `build/classes/main`). Gradle on  the other hand creates a JAR file for each module and then puts those JARs on the classpath.

To solve your problem you either have to find a way to conditionally ignore the locations, depending on the build tool you use (maybe there is a system property you can use, or some other criteria). Or you find a way to do it agnostic of the way the build tool creates the classpath. For example you could maybe look for locations that contain your app root name, like `location.contains("/myapp/")` which could maybe catch JAR files within `/myapp/` as well as file paths, as long as the root is called the same on all systems.

**Comment by GeeJoe** [comment]
Thank you :D

**Comment by hankem** [comment]
Can we close this issue, or is there anything that can be done within ArchUnit?

**Comment by GeeJoe** [comment]
Sorry, I forget to close it :D
