### ISSUE TITLE
How to get all members of a JavaClass that is directly defined at the class

### ISSUE THREAD

**Issue by GeeJoe** [TNG/ArchUnit#604]
```
interface I {
  fun name(): String
}

class A : I {
  private val tag = "TAG"

  fun methodA() {
  }

  override fun name(): String {
    return "hello"
  }
}
```

I want to get all the members of Class A except member "name()" since the method "name()" is the implementation of interface I, how can I do that? 

I tried to achieve it by using the following code

```
fun JavaMember.isDirectlyMemberOf(javaClass: JavaClass): Boolean {
    return this.owner == javaClass
}

fun JavaClass.getDirectlyMembers(): List<JavaMember> {
    return allMembers
            .filter {
                it.isDirectlyMemberOf(this)
            }
}

```
But it seems not work because the `name()`'s owner is Class A(I thought it was interface I...)

**Comment by hankem** [comment]
Do I understand correctly that you want to compute all members that are not member of the superclass or any interface?

**Comment by GeeJoe** [comment]
yes

**Comment by GeeJoe** [comment]
I tried via the following code
```kotlin
fun JavaClass.getAllDirectlyMembers(): List<JavaMember> {
    return this.allMembers.filter { it.isDirectlyMemberOf(this) }
}

fun JavaMember.isDirectlyMemberOf(javaClass: JavaClass): Boolean {
    javaClass.allInterfaces.forEach {
        it.allMembers.forEach {
            if (it.hasSameSignature(this)) {
                return false
            }
        }
    }
    if (this.fullName.startsWith("java.lang.Object")) {
        return false
    }
    return true
}

fun JavaMember.hasSameSignature(target: JavaMember): Boolean {
    return this.getSignature() == target.getSignature()
}

fun JavaMember.getSignature(): String {
    return "$name:$descriptor"
}
```
But I have to import the whole project to do this since some superclass or interface is not in my package. Import the whole project will cause OOM because the project is super huge....

Is there any other way to do this?

**Comment by hankem** [comment]
Your approach looks in principle good to me! 👍  (If you're not interested in members from the class hierarchy, I'd use `members` instead of `allMembers` to exclude them already in first place.)

Even if not explicitly imported, interfaces should [by default be imported from the classpath](https://www.archunit.org/userguide/html/000_Index.html#_dealing_with_missing_classes) (unless [`resolveMissingDependenciesFromClassPath`](https://www.archunit.org/userguide/html/000_Index.html#_configuring_the_resolution_behavior) is explicitly set to `false`).

I think the following (Java) code should work: (Note that [ArchUnit 0.18.0](https://github.com/TNG/ArchUnit/releases/tag/v0.18.0) renamed `allInterfaces` to `allRawInterfaces`.)
```java
Collection<JavaMember> getOwnMembers(JavaClass javaClass) {
    Map<String, JavaMember> memberBySignature = javaClass.getMembers().stream()
            .collect(toMap(this::getSignature, identity()));
    javaClass.getClassHierarchy().forEach(superclass -> removeMembers(superclass, memberBySignature));
    javaClass.getAllRawInterfaces().forEach(interfaceClass -> removeMembers(interfaceClass, memberBySignature));
    return memberBySignature.values();
}

String getSignature(JavaMember member) {
    return member.getName() + member.getDescriptor();
}

void removeMembers(JavaClass javaClass, Map<String, JavaMember> memberBySignature) {
    javaClass.getMembers().forEach(member -> memberBySignature.remove(getSignature(member)));
}
```
(Note that removing superclass-members by signature also removes constructors with the same parameters, which may or may not be desired, but you can easily adjust that according to your requirements.)

**Comment by GeeJoe** [comment]
Thanks, your advice helps a lot!
I did set the `resolveMissingDependenciesFromClassPath` to false before and now I remove the config in `archunit.properties`

Thank you!
