### ISSUE TITLE
How to restrict the using of some of library in a class ?

### ISSUE THREAD

**Issue by Georgy-Ryabov** [TNG/ArchUnit#64]
Hi Peter, I very like the idea of the ArchUnit.

My question is it possible to create a rule that does not allow to use some third-party libraries?

For instance, there are several libraries for test assertions, but I want a team use only one in test classes.

From my point of view, I can simply check imports of test classes and raise a fail if import in a "blacklist".

**Comment by codecholeric** [comment]
Hi Georgy, I think what you want is possible, but there might be several ways, so it depends a little on your use case. First of all, ArchUnit has no concept of imports, since it only analyzes bytecode.
However, I think you could achieve what you want either by naming:

```
@ArchTest
public static final ArchRule rule_via_package = noClasses().that().haveNameNotMatching(".*Test")
        .should().accessClassesThat().resideInAPackage("org.junit..");
```

That works, if your external library has a distinguishing package. Or you could use the source of your Java classes, which is not integrated in the default fluent API, but can easily be added:

```
@ArchTest
public static final ArchRule rule_via_source = 
    noClasses().that(haveSourceMatching(".*/test/.*"))
        .should().accessClassesThat(haveSourceMatching(".*junit.*\\.jar.*"));

private static DescribedPredicate<JavaClass> haveSourceMatching(final String regex) {
    return new DescribedPredicate<JavaClass>("have source matching '%s'", regex) {
        @Override
        public boolean apply(JavaClass input) {
            return input.getSource().isPresent()
                    && input.getSource().get().getUri().toString().matches(regex);
        }
    };
}
```

Of course you can mix and match those approaches, like restricting the classes by name and the targets by source, etc.
Note that this only catches accesses though, so a dependency like an annotation is not captured. I'm working on improving this in the next version (you could add this yourself though, if you need it, I can also copy & paste some code here :wink:)
But for test assertions it should work, since those are real accesses in bytecode, i.e. method calls, etc.
Does this help you?

**Comment by Georgy-Ryabov** [comment]
Peter, I'll try your solution. Thank you.

My case is the next:

One of the rule.
I write tests using testng and three assertion libs are accessible from the tests.
I want to use only Hamcrest assertions, but not testng or assertj.

This is not actually architecture rules but with this, I'd like to help novices in the team and rid of code mess.

**Comment by Georgy-Ryabov** [comment]
For code source approach I look towards https://github.com/forge/roaster
I already use it to extract useful statistic from my test.

**Comment by codecholeric** [comment]
Roaster looks neat, I might play around with that myself a little :wink: Might cover the source aspect that is missing from ArchUnit, for static code analysis.
For your use case, you should be fine, to do sth. like this:

```
@Test
public void only_use_Hamcrest() {
    JavaClasses classes = new ClassFileImporter().importPackages("com.myapp");

    ArchRule rule = noClasses()
            .should().accessClassesThat()
                .haveFullyQualifiedName(org.assertj.core.api.Assertions.class.getName())
            .orShould().accessClassesThat()
                .resideInAPackage("org.testng")
            .because("we consistently want to use Hamcrest in our tests");

    rule.check(classes);
}
```

(There is no specific TestNG support for ArchUnit up to now, like the `ArchUnitRunner` for JUnit 4)

**Comment by Georgy-Ryabov** [comment]
Peter, thank you for help and ArchUnit.

**Comment by Georgy-Ryabov** [comment]
Yeah, that is solved.
