### ISSUE TITLE
Let `@AnalyzeClasses` default to scan the package of the annotated class

### ISSUE THREAD

**Issue by odrotbohm** [TNG/ArchUnit#719]
Currently I have to write:

```java
package com.acme.sample;

@AnalyzeClasses(packagesOf = MyTestClass.class) 
class MyTestClass { … }
```

to analyze all classes contained in the very same package as the test class is located in. It would be nice if an "empty" annotation would simply default to that.

```java
package com.acme.sample;

@AnalyzeClasses // scans com.acme.sample by default
class MyTestClass { … }
```

Currently, the suggested arrangement seems to kick of scanning of the entire JVM and classpath, which is unlikely to be a useful default, is it?

**Comment by codecholeric** [comment]
I agree that just `@AnalyzeClasses` has a little bit of a surprising default behavior. The reason it is like this at the moment was that I originally considered the use case for this default to be for example

```
@AnalyzeClasses(importOptions = DoNotIncludeArchives.class)
```

I.e. I don't want to specify any packages, I just exclude all dependencies by saying to ignore any JAR or JRT... But this turned out to be a little unreliable, because it might then depend on the environment. Run it with the build tool, suddenly things are JARs that were just plain compiled class files on some path in your IDE :thinking:

Thinking about my own use cases I also pretty much always use `packagesOf` or something similar and seldomly the whole classpath with some filter. 

I see the benefit of taking the package of the class by default, because that would make it very simple to just put the test in the root and it will test the project. And it's consistent to similar cases of other frameworks.

Only problem is that for people following the above pattern this would be a breaking change that could lead to existing tests not testing anything anymore (because the test e.g. resides alone in some subpackage, etc.). But maybe with a dominant breaking change announcement in the release notes it's alright :thinking:

**Comment by hankem** [comment]
Just an idea: Should we leave `@AnalyzeClasses` as it is and additionally provide some `@AnalyzeClassesInThisPackage`? 🤔

I don't know whether users would actually suffer from the suggested change, but it would certainly be annoying if somebody who doesn't know about the new behavior – because I don't think that the name `@AnalyzeClasses` communicates it – has to debug why a test behaves differently in one package than in another, or even worse: loses test coverage without noticing...

**Comment by codecholeric** [comment]
Yes, that is also what I'm afraid of. But I'm not sure if yet another annotation really makes this better, because it still keeps surprising behavior of the default.
Another way to do it would be to introduce a new property in `archunit.properties`, e.g. `junit.disableAnalyzeClassesLegacyBehavior` which by default would be `false` in the next one or two releases but then prints a warning "WARN: Using legacy behavior for `@AnalyzeClasses`. You can disable this warning with property x. Note that this will change the behavior in way y". After two releases we would remove the property and change the default behavior for good :thinking: 
Can't think of other good ways for this case unfortunately (without introducing another annotation) :disappointed: But I also kind of would like only one annotation :thinking: 
Or we could do it with release of `1.0` assuming that people will study the release notes more carefully for breaking changes than usual :thinking:

**Comment by odrotbohm** [comment]
Does it make sense to issue an 1.0 RC release to allow people to upgrade to that version and report issues or adapt their codebase prior to the 1.0 release?

**Comment by codecholeric** [comment]
I was already planning on that :slightly_smiling_face: But to do this I want to merge #847 and #833, which will still need a little work :grimacing:
