### ISSUE TITLE
Feature request: add ability to scan all projects

### ISSUE THREAD

**Issue by vladislav2402** [TNG/ArchUnit#720]
Hello!
I faced with a problem that I cannot scan all projects with ArchUnit
Architecture looks like this:
```
MainPackage:
        service1:
             main
             test
        service2:
             main
             test
        service3:
             main
             test
```
I want to implement hierarchy test that checks that one parent class have only one child.
Parent classes is declared in one of modules above, but child class could be in any of them
When I read documentation I didn't find solution

**Comment by hankem** [comment]
> I cannot scan all projects with ArchUnit

When you have multiple build modules (I imagine e.g. Maven or Gradle modules) and want to test their overall architecture, you could introduce a new module that includes all others in a single classpath (if you don't have that already), and add your ArchUnit tests there; just make sure you import all classes that you need. (Or did I misunderstand your issue?)

**Comment by vladislav2402** [comment]
> > I cannot scan all projects with ArchUnit
> 
> When you have multiple build modules (I imagine e.g. Maven or Gradle modules) and want to test their overall architecture, you could introduce a new module that includes all others in a single classpath (if you don't have that already), and add your ArchUnit tests there; just make sure you import all classes that you need. (Or did I misunderstand your issue?)

I have about 15 packages and include each of them seems not good

**Comment by hankem** [comment]
Sorry, I probably still don't understand your issue / expectation. ArchUnit obviously cannot test code that is not made available. 🤷‍♂️

**Comment by codecholeric** [comment]
I think there are just two options: a) make all relevant classes available on the classpath (e.g. by declaring one module that depends on all the relevant modules under test). Or b) simply depend on compile order and use a file path (i.e. make sure all modules are compiled before ArchTests run, then specify the file paths where to look for classfiles, e.g. all `target/classes/...` folders). Option a) is usually the smoother one though, because then you refer to packages, etc., to pick up the classes instead of needing to know where classes are compiled to.

**Comment by codecholeric** [comment]
Gonna close this for now, as this is not really ArchUnit related. ArchUnit can pick up classes from the classpath or from file paths, so one of both must be provided, there is no way around it. But feel free to reopen if you have any more questions about this!
