### ISSUE TITLE
Annotation not recognized in some cases unless you analyze the package

### ISSUE THREAD

**Issue by daniel-kr** [TNG/ArchUnit#728]
Hello,

we would like to upgrade from ArchUnit `0.14.1` to `0.22.0`. However, in the new version, we stumbled over several issues that seem to be quite similar to the one mentioned in #450.

It is again about our use case that we want to ensure that "plugin" classes may only depend on "platform" classes that are annotated with a special annotation `@PublicApi`. The details are well described by my colleague in #450 . Important is that we don't want ArchUnit to analyze the code of the "platform" but only the code of a "plugin" since analyzing the "platform" for every "plugin" would have a huge performance impact. Of course, the "platform" classes are on the classpath anyway.

There are several cases where ArchUnit does not recognize the presence of the annotation and reports the dependencies to an `ApiClass` as violations. 

1. Class references like `ApiClass.class`
2. `instanceOf` checks
3. Checks for generic type parameters like `List<ApiClass>`
4. Exception declarations on a method signature like `throws ApiClass`
5. Members of annotations like `@Test(expected = ApiClass.class)`
6. Array types like `ApiClass[]`

1 - 3 are related to new features of the new version of ArchUnit. These features are great by the way.
4 - 6 are regressions that worked before on version `0.14.1`.

I uploaded a simple project that demonstrates all of these cases: https://github.com/daniel-kr/arch-unit-test

I found the following workarounds, each of which solves the problem in all of the 6 cases:

- For each "plugin", analyzing the "platform" code as well. As said, this has a performance impact that we want to avoid.
- Adding a reference to `ApiClass` to the `DependentClass` that is different from the cases mentioned above. For example, adding an attribute with the type of `ApiClass`. However, this would mean that our plugin developers need to add those dummies to all classes that only reference an API class in a way mentioned above. We would like to avoid this as well.

Is this something that can be changed/fixed?

Thanks in advance!

Kind regards,
Daniel

**Comment by codecholeric** [comment]
Thanks a lot for raising this issue and providing such a great example :smiley: :+1:
I think for convenience all of those cases should be fixed, i.e. we should transitively import annotations in these cases.
What I'm not exactly sure about is why in cases 4 - 6 this were automatically picked up in `0.14.1` :thinking: This must have been an accidental side effect of some old logic we removed on the way :thinking:
One thing you could maybe do for the time now, as a workaround until we have fixed this, is to use a custom class resolver that goes one level deeper for platform classes:

```
public class CustomClassResolver implements ClassResolver {
    private final ClassFileImporter classFileImporter = new ClassFileImporter();
    private final ClassResolverFromClasspath defaultResolver = new ClassResolverFromClasspath();

    @Override
    public void setClassUriImporter(ClassUriImporter classUriImporter) {
        defaultResolver.setClassUriImporter(classUriImporter);
    }

    @Override
    public Optional<JavaClass> tryResolve(String typeName) {
        if (!typeName.startsWith("org.example.archunittest.platform")) {
            return defaultResolver.tryResolve(typeName);
        }
        try {
            ArchConfiguration.get().setClassResolver(ClassResolverFromClasspath.class);
            URL url = getClass().getResource("/" + typeName.replace(".", "/") + ".class");
            return url != null ? Optional.of(classFileImporter.importUrl(url).get(typeName)) : Optional.empty();
        } finally {
            ArchConfiguration.get().setClassResolver(CustomClassResolver.class);
        }
    }
}
```

Then set in `src/test/resources/archunit.properties` (compare the [user guide](https://www.archunit.org/userguide/html/000_Index.html#_configuring_the_resolution_behavior) )

```
classResolver=org.example.archunittest.CustomClassResolver
```

It looks a little convoluted (because you have to reset the class resolver around the nested `ClassFileImporter` call to break the chain), but it might work for now and not cost too much performance? Of course I don't know your real setup...

Other than that we will try to enhance this to transitively load annotations in your described cases!

**Comment by daniel-kr** [comment]
Thank you very much for the detailed answer and especially for the suggested workaround! 😃 
I am glad to hear that you are going to fix that. ☺️ 
Unfortunately, while the workaround works great on my example project, it somehow does not work in our context. 😞 I haven't found the difference yet. When I debug, I see that the "platform" classes are correctly imported and that they also have the `@PuplicApi` annotation stored in the corresponding field of `JavaClass`. But for some reason, Arch Unit then reports all references to "platform" classes as violations, so this makes it even worse. I will investigate further on this and try to find the difference between the example and our project. At the moment, it is really strange. 🤷

**Comment by daniel-kr** [comment]
Hey! I finally found the time to upgrade our product to ArchUnit 0.23.1. It works like a charm now with our product. Thank you very much for fixing the issue! 😃

**Comment by codecholeric** [comment]
Why not 1.0.0-rc1? :wink: We need feedback :grin:
