### ISSUE TITLE
default method implementation in interfaces

### ISSUE THREAD

**Issue by murilophilips** [TNG/ArchUnit#738]
Hi,

I was asked to write a rule that verifies all files in a package are interfaces without default implementations on them.
I was able to write the rule for checking they're interfaces, but I noticed the JavaModifier class doesn't have the "default" keyword in it. Should it be there? Is there a better way to do this?

Thank you in advance.

**Comment by codecholeric** [comment]
I think there is no "modifier" for `default`, the way to detect it is that you find interface methods that don't have a `JavaModifier.ABSTRACT`. Because any interface method that is not a default method will automatically be abstract, and vice versa a default method never is abstract.

So, I think what you want to do is something like

```
ArchRuleDefinition.methods()
  .that().areDeclaredInClassesThat().areInterfaces()
  .should().haveModifier(JavaModifier.ABSTRACT)
  .as("interface methods should not have default implementations")
```

Does that help you?

**Comment by murilophilips** [comment]
It does. I actually had already coded it that way as a workaround, but it's great to validate it's the correct approach. Thank you so much!

**Comment by codecholeric** [comment]
I'll close the issue then for now :slightly_smiling_face: Feel free to reopen if there should still be some other unclear aspects!
