### ISSUE TITLE
Class xxx is not contained in any component when using PlantUmlDiagram

### ISSUE THREAD

**Issue by zhangchunzhao12** [TNG/ArchUnit#773]
I have used archunit for months, and it's very useful to our project, but I got an issue:
I choose PlantUmlDiagram to check rule
classes().should(adhereToPlantUmlDiagram(pumlFileName, consideringOnlyDependenciesInDiagram())).check(target);
In the demo，I have three package: P1, P2, P3
So I draw plantUml: P1, P2 as components
[P1Test] <<..P1..>> as P1
[P2Test] <<..P2..>> as P2
If P3 dependent to P1, there would be an error: you could treat com.plantuml.App as P3
Exception in thread "main" java.lang.IllegalStateException: Class com.plantuml.App is not contained in any component
        at com.tngtech.archunit.library.plantuml.JavaClassDiagramAssociation.getComponentOf(JavaClassDiagramAssociation.java:87)
        at com.tngtech.archunit.library.plantuml.JavaClassDiagramAssociation.getPackageIdentifiersFromComponentOf(JavaClassDiagramAssociation.java:67)
        at com.tngtech.archunit.library.plantuml.PlantUmlArchCondition.check(PlantUmlArchCondition.java:146)
        at com.tngtech.archunit.library.plantuml.PlantUmlArchCondition.check(PlantUmlArchCondition.java:92)
        at com.tngtech.archunit.lang.ArchRule$Factory$SimpleArchRule.evaluate(ArchRule.java:218)
This is not I expected, because I not expect P3 to be involved, and the error also showed that P3 in not in the uml diagram
I theck the code:
    public void check(JavaClass item, ConditionEvents events) {
        if (allDependenciesAreIgnored(item)) {
            return;
        }
        String[] allAllowedTargets = FluentIterable
                .from(javaClassDiagramAssociation.getPackageIdentifiersFromComponentOf(item))
                .append(javaClassDiagramAssociation.getTargetPackageIdentifiers(item))
                .toArray(String.class);

        ArchCondition<JavaClass> delegate = onlyHaveDependenciesInAnyPackage(allAllowedTargets)
                .ignoreDependency(ignorePredicate);

        delegate.check(item, events);
    }
	If class in P3 import P1, allDependenciesAreIgnored(item) would return true, and cause the error

Is this an intent design or it is not expected ?
And could you help providing some solution because I realy wan't P3 to be involved;
Hoping for your reply, thanks very much!

**Comment by codecholeric** [comment]
AFAIS the behavior is as intended. The PlantUML rule is strict about the classes supplied to the rule, because otherwise that opens danger of using it wrongly (e.g. the components actually don't contain the classes, so the test would always be green, but for real nothing is tested). 

Thus, you can only control the behavior with respect to dependencies of the supplied classes. This is because typically your component P1 will depend on a lot of classes outside of your project that you don't care about. For example `java.lang.String`. Most users would not want to add `java..` to their diagram (even though it also might make sense in some cases if you really care about the dependencies of your code to all libraries).

To get back to your problem, what you probably want to do is filter the classes you supply to the rule to not contain P3. Say you have `..p1..`, `..p2..` and `..p3..`. You only want to test the dependencies between `..p1..` and `..p2..` but you don't care about `..p3..`. Then a way to do it would be

```
classes().that().resideOutsideOfPackage("..p3..").should(adhereToPlantUmlDiagram(..))
```

**Comment by zhangchunzhao12** [comment]
Actually in the real condition, I could not figure out P3 when I feed those jars in to archuint; I get jars from classpath, but for different modules, I would get different classpath. so maybe I only know what I care about and need to filter out other jars,  is there more convenient way to meet this ? Thanks very much for your help!

**Comment by codecholeric** [comment]
Yes, you can always do

```
classes().that().resideInAnyPackage(allPackagesInTheDiagram).should(adhereToPlantUmlDiagram(..))
```

That would cut the input down to only that classes that are in the diagram anyway.
