### ISSUE TITLE
Maven's compiler plugin 3.10.0 breaks testing

### ISSUE THREAD

**Issue by TomerFi** [TNG/ArchUnit#793]
Hello

Thank you for this awesome library!
❤️ 

This is not an actual issue, but I see that _Discussions_ is not activated for this repository.

I wanted to share some info, recently, [maven-compiler-plugin 3.10.0](https://github.com/apache/maven-compiler-plugin/releases/tag/maven-compiler-plugin-3.10.0) was released.
It brings forth some new features and bug fixes and accidentally broke my existing tests with the unexpected appearance of _pacakge-info.class_ files.

Here's the [failing workflow](https://github.com/TomerFi/alexa-skill-shabbat-times/runs/5196280297?check_suite_focus=true#step:4:439).
This, of course, works well with version _3.9.x_ of the _maven-compiler-plugin_.

As a quick fix, I created a simple [custom ImportOption implementation](https://github.com/TomerFi/alexa-skill-shabbat-times/commit/51ce485a7504f6ea9e23f2698befedc0b7f022ed) and used it within the _AnalyzeClasses_ annotation.

I think it will be useful for other users too,
I'll soon open a PR here adding this _ImportOption_ implementation.

See you there.
😉 👋🏻

**Comment by codecholeric** [comment]
Yes, this sounds like a reasonable addition to the default `ImportOptions`, thanks for contributing :smiley:

**Comment by codecholeric** [comment]
BTW: I hadn't even seen that GitHub now features discussions :+1: I'll look into that, if it makes sense for ArchUnit, because so far I'm just tagging issues as "discussion', but that's of course not optimal :wink:

**Comment by TomerFi** [comment]
Highly recommended, serves as a great place for users to ask questions, share ideas, and more, instead of opening issues.
There's also a button for creating an issue from a discussion, so if a question turns out to be a bug, it's a pretty useful feature.

**Comment by TomerFi** [comment]
perhaps _package-info_ classes are included in the classes set as well:

https://github.com/TNG/ArchUnit/blob/a26307dea2d4e75dbdccf01fbd20918c8c64453c/archunit/src/main/java/com/tngtech/archunit/core/domain/JavaPackage.java#L65

Regardless, I don't think they should be excluded,
you can use annotations with _package-info_ classes,
this might be something users want to verify with _ArchUnit_.

**Comment by codecholeric** [comment]
Yes, so far I considered it intended to add the `package-info` as `JavaClass`. You can of course argue if "java class" is the correct domain object for that :wink: It would likely be cleaner to have a separate object, but that would have been a major refactoring which I did not want to prioritize so far (like where would they live in the structure, how would you access them if you obtain `JavaClasses`, would you need to return something different from `ClassFileImporter` then, that contains `JavaClasses` and `JavaPackageInfo`, etc.).
And yes, I consider them quite useful, because you can annotate package info and by that specify meta-information. I already had implementations where you could for example annotate the package info via `@ArchitectureComponent(name = "Foo", mayDependOn = {"Bar", "Baz"}` and by that establish one `ArchRule` to govern the dependencies of a growing ecosystem of components/packages in a quite maintainable way where developers never would need to extend the rule but only declare their components.

**Comment by codecholeric** [comment]
I have enabled discussions for now, let's see how this will work and if users like them :slightly_smiling_face:
