### ISSUE TITLE
Make ArchConditions#createMessage(T, String) public

### ISSUE THREAD

**Issue by daniel-shuy** [TNG/ArchUnit#826]
`ArchConditions#createMessage(T, String)` is really useful when creating custom `ArchCondition`s, but because it is `private`, it is inaccessible. It would be nice if it was changed to `public`.

**Comment by hankem** [comment]
I wonder whether `ConditionEvents`  could offer an _all-round carefree package_ like this:
```java
    public <T extends HasDescription & HasSourceCodeLocation> void addEventWithFormattedMessage(
            T object,
            boolean satisfied,
            String messageContentFormat,
            Object... messageContentArgs
    ) {
        String message = String.format("%s %s in %s",
                object.getDescription(),
                String.format(messageContentFormat, messageContentArgs),
                object.getSourceCodeLocation()
        );
        add(new SimpleConditionEvent(object, satisfied, message));
    }
```
I'm not entirely happy with that name... `addEventWithFormattedMessage` doesn't really communicate that the "message content" (or "core message"? Or "custom part"? 🤔) gets the object's description prepended and the source code location appended, right?

**Comment by daniel-shuy** [comment]
@hankem yeah it would be pretty difficult to convey that with a single method. I think having 2 methods is still alright, eg.
```java
@Override
public void check(JavaClass javaClass, ConditionEvents events) {
    String message = ArchConditions.createMessage(javaClass, ...);
    events.add(new SimpleConditionEvent(javaClass, ..., message));
}
```

It would also allow for more flexibility, eg. customizing the message, or using the default created message to create a custom `ConditionEvent`.

**Comment by hankem** [comment]
`ArchConditions#createMessage` has IMO a similar issue when it comes to communicating what it does – but I guess that it can be okay  in any case with an according JavaDoc and/or a better name.

I like the function on `ConditionEvents` because it might be more discoverable for users than a static helper function on `ArchConditions` – but we can still have both, so apologies for hijacking your issue with another idea... 😉
Anyways, I've pushed a PoC to demonstrate how `ConditionEvents.addEventWithFormattedMessage` would simplify `ArchConditions` to the branch [`ConditionEvents.addEventWithFormattedMessage`](https://github.com/TNG/ArchUnit/commits/ConditionEvents.addEventWithFormattedMessage), see in particular 3ae3f61a259fb7d51336b9570fde01909a70b048.

**Comment by fdesande-diconium** [comment]
I'm having a similar issue when I'm trying to use the method `PlantUmlArchCondition.adhereToPlantUmlDiagram(URL, PlantUmlArchCondition.Configuration)`. The interface `PlantUmlArchCondition.Configuration` is package private so it works fine in Java, but t's inaccesible in Kotlin because of the KotlinJVM.

Please, make `PlantUmlArchCondition.Configuration` public
