### ISSUE TITLE
Stateless Session Beans

### ISSUE THREAD

**Issue by blauerklaus** [TNG/ArchUnit#848]
First things first: I really like your work very, very much. Thanks for this great work.

I try to write a rule to assure the statless character of these Beans.

So I took my inspiration from https://github.com/TNG/ArchUnit-Examples, SessionBeanRulesTest.java
`public void stateless_session_beans_should_not_have_state()`

When I have following (totally stripped down) stateless Bean the test fails. And I think it should not.
```
package com.tngtech.archunit.example.layers;

import javax.ejb.Local;
import javax.ejb.Stateless;

@Stateless
@Local(SomeBusinessInterface.class)
public class ClassViolatingSessionBeanRules implements SomeBusinessInterface {
    public static final Integer CONSTANT = new Integer(42);
}
```
The following Bean is not so different and the Test is green. What is correct in my opinion.
```
package com.tngtech.archunit.example.layers;

import javax.ejb.Local;
import javax.ejb.Stateless;

@Stateless
@Local(SomeBusinessInterface.class)
public class ClassViolatingSessionBeanRules implements SomeBusinessInterface {
    public static final int CONSTANT = 42;
}
```
Unfortunately I'm not smart enough and I didn't find a solution. Do you have an idea? 

PS: Same 'wrong-positive'-problem with this one:
```
package com.tngtech.archunit.example.layers;

import javax.ejb.Local;
import javax.ejb.Stateless;

@Stateless
@Local(SomeBusinessInterface.class)
public class ClassViolatingSessionBeanRules implements SomeBusinessInterface {
    public static final int CONSTANT = OtherClass.getAnswer(); // static method in OtherClass

}
```

**Comment by codecholeric** [comment]
Glad you like the library :smile: I think you actually stumbled over some simplification in the ArchUnit example :grimacing: Because it does not distinguish between instance fields and static fields, while the latter don't really pose any "state".
I think you could fix it either by

```
noClasses().should()
    .setFieldWhere(
        TARGET_IS_STATELESS_SESSION_BEAN
            .and(TARGET_IS_INSTANCE_FIELD)
            .and(ACCESS_ORIGIN_IS_OUTSIDE_OF_CONSTRUCTION))
// ...

private static final DescribedPredicate<JavaFieldAccess> TARGET_IS_INSTANCE_FIELD =
    DescribedPredicate.describe("is instance field", access -> {
        Optional<JavaField> field = access.getTarget().resolveMember();
        return field.isPresent() && !field.get().getModifiers().contains(STATIC);
    });
```

(this would limit the fields that cause violations to instance fields, ignoring static fields)
or you modify

```
private static final DescribedPredicate<JavaAccess<?>> ACCESS_ORIGIN_IS_OUTSIDE_OF_CONSTRUCTION =
    not(originOwnerEqualsTargetOwner()).or(originNeitherConstructorNorStaticInitializerNorPostConstruct());

private static DescribedPredicate<JavaAccess<?>> originNeitherConstructorNorStaticInitializerNorPostConstruct() {
    return Get.origin().is(not(constructor()).and(not(staticInitializer())).and(not(annotatedWith("javax.annotation.PostConstruct"))));
}

private static DescribedPredicate<JavaCodeUnit> staticInitializer() {
    return DescribedPredicate.describe("static initializer", codeUnit -> codeUnit instanceof JavaStaticInitializer);
}
```

(this would treat setting a field from a static initializer as part of construction which is IMHO also correct, but would then cause a violation if you have a mutable static field :open_mouth: inside of your stateless session bean class)

The reason why your cases behave surprising is unfortunately compiler magic :grimacing: I.e. for constant primitives declared in place like your first `int` the compiler does some inlining, so this constant actually vanishes inside of the bytecode. But the other two cases with boxed type or reference to another class can't be inlined so they cause a violation :man_shrugging: 

Does that help you? We should probably update the ArchUnit example to consider static fields correctly!

**Comment by blauerklaus** [comment]
Wow, thank your for the quick and detailed answer! 👍 In particular the explanation with the compiler magic.

Before I opened this issue yesterday, I tried to find a solution which goes in the direction of your 2nd proposal. Although the argumentation "static fields are not really state" is not wrong. Anyway in my case the 2nd Approach was and is more interesting for me🤩.

The problem is: Your modified ACCESS_ORIGIN_IS_OUTSIDE_OF_CONSTRUCTION doesn't work 😳. At least not in the way I hoped:

Given the following stateless Bean:
```
package com.tngtech.archunit.example.layers;

import javax.ejb.Local;
import javax.ejb.Stateless;

@Stateless
@Local(SomeBusinessInterface.class)
public class ClassViolatingSessionBeanRules implements SomeBusinessInterface {
    public static final Integer CONSTANT = new Integer(42);
    public static Integer MUTABLE_FIELD = new Integer(4711);
}
```
I'd like the CONSTANT-Line to pass and the MUTABLE-Line to fail and if I understood you correctly, you expect exactly that, right?

But the test says: "everything is OK". 🧐

I think, there is no point in the code at which there is a check on modifier final. And this is not easy at all, because we have to deal with JavaCodeUnit which is in fact static but can not be final, i suppose. It only contains a set of JavaFieldAccess-Object who's target then can be final or not.

I could imagine that the compiler does something like this:
```
public class ClassViolatingSessionBeanRules implements SomeBusinessInterface {
    public static final Integer;
    public static Integer MUTABLE_FIELD;
    static {
        CONSTANT = new Integer(42);
        MUTABLE_FIELD = new Integer(4711);
    }
}
```
But I'm not smart enough to understand this in detail. And perhaps this is generally 'a little bit akademisch' 🤔 and one could argue that this is another point for the "static fields are not really state" argument.

Perhaps it's better to define a independent Test which assures that no class (or no stateless session bean) should have mutable static fields. What do you think?

**Comment by codecholeric** [comment]
Yeah, to me it sounds a little bit like a separate issue that might best be covered in an explicit test. In particular if it's something you don't want in general (if you only want it for SSBs, then maybe it could go like this, but even then it could be a separate rule that SSBs should not have mutable static fields, because it's a separate aspect from state IMHO :man_shrugging:)

As to why it's not working as expected, that is probably because ArchUnit here doesn't check if the field is immutable, it checks if the field is not in fact mutated. So if you add some random place that changes your `MUTABLE_FIELD` you should see a violation. You could also check that static fields are final, but that's again separate test from the "SSBs should not have state" aspect. In particular, because as soon as dependency injection comes into play for SSBs `final` modifiers are often not possible anymore (e.g. set in `@PostConstruct`, etc.)

**Comment by blauerklaus** [comment]
Thank you very much for the explanation! ArchUnit is even smarter than i thought! Did I mention, that I like it? 

I agree with you: There are two separate aspects, so i wrote two tests. Suddenly everything is easier to write, to read and to maintain :-)

Thanks for your help! I ow you a beer!

**Comment by codecholeric** [comment]
Glad you like ArchUnit :smile: Maybe we'll meet somewhere like a conference once, then I'm happy about that :beer: :joy: 
Can I close this issue then? Or do you have further questions/problems?

**Comment by blauerklaus** [comment]
Closed without the proposed beer? When it's ok for you, I can live with it ;-) we will catch up on the beer later...

**Comment by codecholeric** [comment]
Well, I would say close for now and if we ever get the chance to say cheers somewhere, we'll do that then :wink:
