### ISSUE TITLE
Bundle POM with Maven artifacts

### ISSUE THREAD

**Issue by ddidier** [TNG/ArchUnit#859]
Hi,

I need to install some (101 at the moment) Maven artifacts with `mvn maven-install-plugin:install-file`. The ArchUnit artifacts are the only one not having their POM bundled in `/META-INF/maven/`. I know there is the option [generatePom](https://maven.apache.org/plugins/maven-install-plugin/install-file-mojo.html#generatePom) but this is quite annoying since I would have a special case only for ArchUnit. I don't know Gradle but [found this](https://stackoverflow.com/questions/58665551/include-pom-xml-in-jar-with-gradle).

Thanks

**Comment by codecholeric** [comment]
AFAIS this would be some manual tinkering that might prove brittle in the future :thinking: Because Gradle doesn't seem to support it out of the box. In the end it could also be deactivated with Maven though, it's just by default that this info would be generated. I checked some popular libraries, Asm, Guava, Apache-Commons-Lang3, Guice, Mockito, JUnit-Jupiter, Weld, AssertJ, Spring-Core and out of these **only** Guava, Apache-Commons-Lang3, Weld and AssertJ were published with this info. So it doesn't seem to me that there is really a strong convention to have this info within the artifact :thinking: 

Could you describe your use case a little? Why you have to install these files via `install-file`? Also can you give some examples of these 101 Maven artifacts that have the info? Just to help me make the decision to introduce something that negatively influences the maintainability of the ArchUnit build.

**Comment by ddidier** [comment]
I just introduced a Spring dependency, and there is no POM either as you wrote... So don't bother, I will do something different. Thanks for your answer.

**Comment by codecholeric** [comment]
I think the more robust way would be to download the POM separately when you download the archive. It also follows a convention on Maven Central (I had a little script for something like this in the past because of some proxy issues in some environment). So you can curl JAR and POM together...
Good luck on finding a somewhat convenient solution!
