### ISSUE TITLE
Is it possible to create an  ArchUnit test to verify that repositories etc. are not used by other modules

### ISSUE THREAD

**Issue by slaverda** [TNG/ArchUnit#864]
How can I create an Arch Unit test that verifies that module internals are not used by other modules.
Module internals include things like model, repositories, service implementations etc.

The only thing that should be used by other modules are: api, service-interface, and configurations.

**Comment by slaverda** [comment]
@hankem In my case the modules are different gradle sub-projects but for this topic we can treat them as different jars. So How can I verify that the internal API (internal packages/classes) are not used/called from outside jars.

I tried couple of things as:

1. `ArchRule r1 = noClasses()
  .that().resideInAPackage("..presentation..")
  .should().dependOnClassesThat()
  .resideInAPackage("..persistence..");`

2. ```
ArchRule rule = classes()
    .should().onlyDependOnClassesThat(
        resideOutsideOfPackages("package")
            .or(type(OrderPlaced.class)));
```
But both cases not working in terms of different jar files... I was thinking to try something with `JavaClass#getSourceCodeLocation()` but at first wanted to ask if the ArchUnit API provide us that functionality.

**Comment by codecholeric** [comment]
If I understand you correctly, then what you want is very likely accomplishable via `JavaClass#getSource()`. However, if you would stick to the convention, that every JAR exports exactly one unique root package, then that would be much easier to assert and more robust. Because otherwise if the classes are added as files, e.g. via `target/classes` will make a difference to being added as JAR files to the classpath.

I don't think that at the moment there is a super convenient solution for what you want. However, a quite powerful solution would be some custom code using the `Slices` API, like the following (which you can maybe adjust to your needs):

```
@ArchTest
static final ArchRule jars_should_only_access_each_other_through_api_package = slices()
    .assignedFrom(jars())
    .namingSlices("Jar $1")
    .should(onlyBeAccessedThroughApi());

private static SliceAssignment jars() {
  return new SliceAssignment() {
    @Override
    public SliceIdentifier getIdentifierOf(JavaClass javaClass) {
      return javaClass.getSource().flatMap(s -> {
        String[] parts = s.getUri().toString().split("\\.jar!/", 2);
        if (parts.length < 2) {
          return Optional.empty();
        } else {
          return Optional.of(SliceIdentifier.of(parts[0].replaceAll(".*/", "")));
        }
      }).orElse(SliceIdentifier.ignore());
    }

    @Override
    public String getDescription() {
      return "jars";
    }
  };
}

private static ArchCondition<Slice> onlyBeAccessedThroughApi() {
  return new ArchCondition<>("only be accessed through API") {
    private final Map<JavaClass, Slice> classesToJars = new HashMap<>();

    @Override
    public void init(Collection<Slice> allJars) {
      allJars.forEach(jar -> jar.forEach(c -> classesToJars.put(c, jar)));
    }

    @Override
    public void check(Slice jar, ConditionEvents events) {
      jar.getDependenciesToSelf().stream()
        .filter(clazz -> !clazz.getTargetClass().getName().contains(".api."))
        .flatMap(violatingInwardsDependency ->
          Optional.ofNullable(classesToJars.get(violatingInwardsDependency.getOriginClass())).stream())
        .distinct()
        .forEach(violatingJar -> events.add(
            SimpleConditionEvent.violated(
              violatingJar,
              violatingJar.getDescription() + " has non-API dependency on " + jar.getDescription())
            ));
    }
  };
}
```

This "slices" your project according to the JAR files (which are taken from the source). All classes not from JARs are ignored. Then for each JAR all incoming dependencies are checked if the package contains `.api.` (you can replace that with any other condition for you API of course). If the target is not in a package `.api.` the originating JAR is flagged as a violation (in real life you would probably want to add the details of the dependencies to make it easier to locate the exact violation).

Again, I don't think "JAR" is the best concept to model modularization. Because JAR files are in the end just some technical packaging. I can unpack them and throw them on the classpath as files and my app will work the same. Thus, I think using e.g. a package convention is a better idea for modularization :man_shrugging:

**Comment by slaverda** [comment]
That is piece of art! Thank you!
