### ISSUE TITLE
loose junit 4.12 dependency

### ISSUE THREAD

**Issue by jangalinski** [TNG/ArchUnit#90]
In my junit 5 project I have to manually exclude junit 4.12 from archunit,  it would be nicer to not have that dependency transitively referenced.

**Comment by codecholeric** [comment]
Can you tell me, which ArchUnit dependency you are using? I'm just asking because I don't see, how the ArchUnit Core POM would pull in JUnit 4 -> https://search.maven.org/remotecontent?filepath=com/tngtech/archunit/archunit/0.8.2/archunit-0.8.2.pom
Is it possible, that you use `com.tngtech.archunit:archunit-junit`? I admit that this artifact is named a little confusingly, since it only refers to JUnit 4 support :wink: 
In the next release of ArchUnit, this artifact will be explicitly called `archunit-junit4`, since then ArchUnit will include extended JUnit 5 support.
If you depend on `archunit-junit`, simply change the dependency to `archunit` and your problem should vanish. 
Alternatively I would be very happy about feedback of my current JUnit 5 implementation -> https://github.com/TNG/ArchUnit/issues/34#issuecomment-405123575

**Comment by jangalinski** [comment]
Yes, I am talking about the archunit-junit artifact. It would be possible to use with junit-5 and legacy junit4 support, but I do not need the transitive dependency.

**Comment by jangalinski** [comment]
Good news with the native junit5 support ... I can wait, its only one exclusion ... will happily check any snapshots.

Removing the transitive dep to junit4 is more of a general aspect ... When I set up my test deps, I never think "maybe some of the test-libs already brings junit4 so I do not mention it" ... if I do need junit4, I always have that dep on testCompile. So you could always set it to provided in 3rd party libs imho, but this might become a philosophical discussion.
