### ISSUE TITLE
Specify file name for freeze?

### ISSUE THREAD

**Issue by keiki85** [TNG/ArchUnit#902]
Hello,

maybe I'm missing something in the documentation.

We have several freeze files named with the UUID. 

If we ran several of our tests we want to know which one got changed without failing. Is there an easy way to specify a file name?

Best regards

**Comment by hankem** [comment]
I probably didn't understand the question correctly, but maybe it already helps to mention that the `stored.rules` properties file maps tests to violation file names (which are UUIDs by default) like in [this example](https://github.com/TNG/ArchUnit-Examples/blob/main/example-plain/src/test/resources/frozen/stored.rules). You can rename the violation files as you like, as long as you adapt the mapping in `stored.rules` consistently. (I actually do so when I want to have a semantic file names that make the mapping more memorizable for me.)

**Comment by keiki85** [comment]
Thank you. You understood my question completely. :+1: 

Probably because I was myself not introducing the archunit tests I am not fully aware of all the features.

**Comment by hankem** [comment]
Well, the [section about _Freezing Arch Rules_ in the _ArchUnit User Guide_](https://www.archunit.org/userguide/html/000_Index.html#_freezing_arch_rules) basically just states
> By default FreezingArchRule will use a simple ViolationStore based on plain text files.

but doesn't document further details of this default store (yet).

If a short sentence about `stored.rules` would have helped you, we should IMO add it.

**Comment by keiki85** [comment]
Yes it would have helped me. For me I looked more in the javadoc to know what's going on. But I guess on both side a reference can help.

**Comment by codecholeric** [comment]
Honestly, I never documented this, because for me this was an implementation detail. I never intended this to be adjusted (and I also personally never had the need, if I want to look up a rule I'll just go mapping-file `stored.rules` -> violations :man_shrugging:) If we document this now, then the internal format of the text based violation store is suddenly public API and if we decide to refactor it we can't do it anymore without a breaking change. I would rather avoid this.
Maybe we could tackle this use case with some additional logging or sth like that? Maybe you can give a little more context on what problem you actually want to solve?

**Comment by keiki85** [comment]
Problem:
@codecholeric  I fully understand this. If there is the mapping file for me there is also no need to adjust it.

We have a dozen of tests each with its own freeze file.
I wanna know which test corresponds to which freeze file.

I didn't know about stored.rules file as I was not involved in introducing the tests.
