### ISSUE TITLE
Not all classes in scope sometimes

### ISSUE THREAD

**Issue by liechtir** [TNG/ArchUnit#956]
Hi

I definitely have proof now that ArchUnit does somehow not show all results when the code base is huge. Our product has roughly 1.4mio lines of production and roughly 4mio of test code.

I have an arch unit rule that checks that all constructors of our own classes are called max once, and the caller of that constructor must be a factory (a class annotated with '@Factory').

When I run that rule on all source code using the scope of
`new ClassFileImporter().importPackages("com.product")` (in the debugger I can see that importedClasses.size()=>(int) 20625 )
it finds roughly 7000 violations.

When I run the very same rule on a more tight scoped package, such as 
`new ClassFileImporter().importPackages("com.product.some.more.specific.package")`  (in the debugger I can see that importedClasses.size()=>(int) 1227)
it finds 40 violations.

So far so good, it makes sense to have less violations inside a deeper package.

However, when I filter the 7000 violations of all source code for constructors that are inside 'com.product.some.more.specific.package', I can find 28 of the 40 reported only.

It seems that a very broad scope of imported classes does not find all violations.

When doing some comparison of java file numbers:
in com.product we have 31'811 *.java files, so the reported number of 20625 seems to be too little. Also, our java files sometimes contain more than one class (i.e. inner classes)

in com.product.some.more.specific.package we have 1530 *.java files, so the reported number of 1227 seems also here to be too little.

When I search for all class files in my product folder and count them, I get:
```
$ find . -type f -iname "*.class" | wc -l
35262
```
Within the more specific package it is 1935.

I get the very same results when executing the arch unit test in eclipse or maven.

Is there a better way of importing all classes to the scope?

**Comment by codecholeric** [comment]
The problem is that `new ClassFileImporter().importPackages("...")` highly depends on your classpath. Besides checking what violations are found on the subpackage when you import the outer package, it might make sense to compare the classes in that package. I.e. if you filter all classes imported via `new ClassFileImporter().importPackages("com.product")` by package `com.product.some.more.specific.package`, do you get the same result as doing `new ClassFileImporter().importPackages("com.product.some.more.specific.package")`?

You could also do a diff of the classes found via `find` and the classes found via `new ClassFileImporter().importPackages("com.product")` and see if you can find some difference in the ones that are included vs not?

Otherwise, there would also be the option to really import the file paths via `new ClassFileImporter().importPath("/my/compiled/classes")` and see if it makes a difference.

In general, it is hard for me to really provide some answers from the info you have provided so far. Because I don't know how your project is set up (build tool, project structure, OS, Java version, ...), nor if you use any import options or if you've customized `archunit.properties`, etc. So I can just try to give you some hints how to find the reason yourself. Otherwise, I would need those mentioned details, or some way to reproduce the issue myself.

**Comment by liechtir** [comment]
> So I can just try to give you some hints how to find the reason yourself. Otherwise, I would need those mentioned details, or some way to reproduce the issue myself.
Thank you very much for those hints. I will check with the filter, compare and give the imports of paths a try to see differences in the behaviour (if any) and come back to you. Due to my workload this will take me a few days, talk to you soon and have a great weekend!

**Comment by liechtir** [comment]
I could do some first tests and what I found so far was, that importing all packages and then filter for the more specific ones shows the same number of loaded classes than importing the more specific one, so this is consistent:
```
@Test
    public void readAllClasses() {
        ArchRule rule = ArchRuleDefinition.classes().should(new ArchCondition<JavaClass>("be found") {
            long classesFound = 0l;
            long classesMoreSpecific = 0l;

            @Override
            public void finish(ConditionEvents events) {
                System.out.println("found classes total:" + classesFound);
                System.out.println("found classes moreSpecific:" + classesMoreSpecific);
                classesFound = 0l;
                classesMoreSpecific = 0l;
            }

            @Override
            public void check(JavaClass cls, ConditionEvents events) {
                classesFound++;
                if (cls.getFullName().contains("com.product")) {
                    classesMoreSpecific++;
                }
            }
        });
        rule.check(new ClassFileImporter().importPackages("com.product"));
        rule.check(new ClassFileImporter().importPackages("com.product.some.more.specific.package"));
    }
```

Outputs
```
found classes total:20437
found classes moreSpecific:1033

found classes total:1033
found classes moreSpecific:1033
```

I then printed all classes found and compared with the output of `find . -type f -iname "*.java"`
It is obvious now that the issues lays in the classes that get imported from the src/test/java

ArchUnit finds certain Test classes in src/test/java, but not all. The major part is not imported.
I will try to find out why and investigate further, maybe play around with the import of paths.

**Comment by codecholeric** [comment]
Thanks for investigating this further! I guess with such a project you have a multi module setup, right? Is it possible that some test classes are just missing because you do something like only selectively packaging `test-jars`? And that thus only those test classes are on the classpath of your module using ArchUnit?

**Comment by liechtir** [comment]
Yes it was a maven setup issue. The test code didn't make it across to to the 'all' maven component that we use to have all product code at hand for such unit tests that want to check code style rules etc.
Sorry to bother you, your comments pushed me on the right track thanks for that! Kudos!

**Comment by codecholeric** [comment]
No worries, glad I could help :smiley:
