### ISSUE TITLE
Static layeredArchitecture() function does not return LayeredArchitecture

### ISSUE THREAD

**Issue by timotuunanen** [TNG/ArchUnit#986]
Hi.

I am using v1.0.0

In version 0.23.1 we were able to do the following:

```
layeredArchitecture()
        .layer("Application").definedBy("..application..")
        ...
```
, but in the latest version `.layer()` results unresolved reference as `layeredArchitecture()` returns DependencySettings instead of LayeredArchitecture. Is this intentional as javadoc still guides to use it the same way as in previous version?

**Comment by hankem** [comment]
Since [v1.0.0-rc1](https://github.com/TNG/ArchUnit/releases/tag/v1.0.0-rc1), 
> `layeredArchitecture()` now forces to decide how to deal with dependencies by adding `.considering`…`Dependencies()` in the beginning of the declaration. To restore the old behavior declare it as `layeredArchitecture().consideringAllDependencies()` (see #892).

This had unfortunately been overseen [in the JavaDoc](https://javadoc.io/doc/com.tngtech.archunit/archunit/1.0.0-rc1/com/tngtech/archunit/library/Architectures.html#layeredArchitecture()) (also [for 1.0.0](https://javadoc.io/doc/com.tngtech.archunit/archunit/1.0.0/com/tngtech/archunit/library/Architectures.html#layeredArchitecture())) and only been fixed with #977 (currently not released yet).

**Comment by hankem** [comment]
@timotuunanen, can we close this issue already?

**Comment by codecholeric** [comment]
Closing this, since there hasn't been any activity. Feel free to reopen if your issue is not solved!

**Comment by hankem** [comment]
[Release 1.0.1 with the fix](https://javadoc.io/doc/com.tngtech.archunit/archunit/1.0.1/com/tngtech/archunit/library/Architectures.html#layeredArchitecture()) is anyways available now.
